# Generated by Django 5.2.9 on 2026-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_product_name', models.CharField(max_length=255)),
                ('competitor_name', models.CharField(max_length=255)),
                ('competitor_sku', models.CharField(blank=True, max_length=100)),
                ('competitive_advantage', models.TextField(blank=True)),
                ('price_difference_percent', models.FloatField(default=0.0)),
                ('is_direct_competitor', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField()),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('upc', models.CharField(blank=True, help_text='Universal Product Code', max_length=12)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_model', models.CharField(choices=[('flat', 'Flat Fee'), ('per_unit', 'Per Unit'), ('tiered', 'Tiered'), ('subscription', 'Subscription')], default='flat', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_subscription', models.BooleanField(default=False, help_text='Is this a subscription product?')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One-Time')], default='one_time', max_length=20)),
                ('subscription_term', models.IntegerField(blank=True, help_text='Contract term in months (e.g., 12, 24)', null=True)),
                ('auto_renewal', models.BooleanField(default=False, help_text='Automatically renew subscription')),
                ('esg_certified', models.BooleanField(default=False)),
                ('carbon_footprint', models.FloatField(blank=True, help_text='kg CO2e per unit', null=True)),
                ('esg_certifications', models.CharField(blank=True, max_length=255)),
                ('sustainability_notes', models.TextField(blank=True)),
                ('tco2e_saved', models.FloatField(default=0.0, help_text='Tonnes of CO2e saved by customer')),
                ('product_is_active', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bundle_name', models.CharField(max_length=255)),
                ('product_bundle_description', models.TextField(blank=True)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_bundle_is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_comparison_name', models.CharField(max_length=255)),
                ('product_comparison_is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended')], default='required', max_length=20)),
            ],
        ),
    ]
