# Generated by Django 5.2.7 on 2025-11-06 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('upc', models.CharField(blank=True, help_text='Universal Product Code', max_length=12)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_model', models.CharField(choices=[('flat', 'Flat Fee'), ('per_unit', 'Per Unit'), ('tiered', 'Tiered'), ('subscription', 'Subscription')], default='flat', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('esg_certified', models.BooleanField(default=False)),
                ('carbon_footprint', models.FloatField(blank=True, help_text='kg CO2e per unit', null=True)),
                ('esg_certifications', models.CharField(blank=True, max_length=255)),
                ('sustainability_notes', models.TextField(blank=True)),
                ('tco2e_saved', models.FloatField(default=0.0, help_text='Tonnes of CO2e saved by customer')),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('min_quantity', models.IntegerField()),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='products.product')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('competitor_name', models.CharField(max_length=255)),
                ('competitor_sku', models.CharField(blank=True, max_length=100)),
                ('competitive_advantage', models.TextField(blank=True)),
                ('price_difference_percent', models.FloatField(default=0.0)),
                ('is_direct_competitor', models.BooleanField(default=True)),
                ('our_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_mappings', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('products', models.ManyToManyField(through='products.BundleItem', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productbundle'),
        ),
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('products', models.ManyToManyField(related_name='comparisons', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('dependency_type', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended')], default='required', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='products.product')),
                ('required_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'required_product')},
            },
        ),
    ]
