# Generated by Django 5.2.7 on 2025-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_renewal',
            field=models.BooleanField(default=False, help_text='Automatically renew subscription'),
        ),
        migrations.AddField(
            model_name='product',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One-Time')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_subscription',
            field=models.BooleanField(default=False, help_text='Is this a subscription product?'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_term',
            field=models.IntegerField(blank=True, help_text='Contract term in months (e.g., 12, 24)', null=True),
        ),
    ]
