# Generated by Django 5.2.9 on 2026-01-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_taxrate_taxrule'),
        ('products', '0007_product_image_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.ForeignKey(blank=True, help_text='Override system tax rules', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.taxrate'),
        ),
    ]
