# Generated by Django 5.2.9 on 2026-01-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_promotion_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdependency',
            options={'verbose_name_plural': 'product dependencies'},
        ),
        migrations.RenameField(
            model_name='productdependency',
            old_name='product',
            new_name='primary_product',
        ),
        migrations.AddField(
            model_name='productdependency',
            name='dependent_product',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdependency',
            name='message',
            field=models.CharField(blank=True, help_text='Message to show the user', max_length=255),
        ),
        migrations.AlterField(
            model_name='productdependency',
            name='dependency_type',
            field=models.CharField(choices=[('mandatory', 'Mandatory (Must include)'), ('recommended', 'Recommended (Suggest to user)'), ('incompatible', 'Incompatible (Cannot include both)')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='productdependency',
            unique_together={('primary_product', 'dependent_product', 'dependency_type')},
        ),
        migrations.RemoveField(
            model_name='productdependency',
            name='required_product',
        ),
    ]
