# Generated by Django 5.2.9 on 2026-01-26 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_accountingintegration_event_type'),
        ('products', '0011_alter_productdependency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='deferred_revenue_account',
            field=models.ForeignKey(blank=True, help_text='Contract Liability account (IFRS 15)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_deferred_revenue', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='revenue_account',
            field=models.ForeignKey(blank=True, help_text='Earned Income account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_revenue', to='accounting.chartofaccount'),
        ),
    ]
