# Generated by Django 5.2.9 on 2026-01-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_accountingintegration_event_type'),
        ('products', '0012_productcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_capital_asset',
            field=models.BooleanField(default=False, help_text='IAS 16: Capitalize on purchase'),
        ),
        migrations.AddField(
            model_name='product',
            name='nrv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net Realizable Value for impairment testing', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ssp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standalone Selling Price (Max)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ssp_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standalone Selling Price (Min)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valuation_method',
            field=models.CharField(choices=[('fifo', 'FIFO'), ('avco', 'Weighted Average'), ('specific', 'Specific Identification')], default='avco', max_length=20),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='asset_account',
            field=models.ForeignKey(blank=True, help_text='Inventory/Capital Asset account (IAS 16)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_assets', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='cogs_account',
            field=models.ForeignKey(blank=True, help_text='Cost of Goods Sold account (IAS 2)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_cogs', to='accounting.chartofaccount'),
        ),
    ]
