# Generated by Django 5.2.9 on 2026-01-28 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_taxrate_taxrule'),
        ('products', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.ForeignKey(blank=True, help_text='Override system tax rules', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxrate'),
        ),
    ]
