# Generated by Django 5.2.9 on 2026-01-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='tenant',
        ),
    ]
