# Generated by Django 5.2.9 on 2026-01-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_supplier_tenant'),
        ('purchasing', '0005_alter_purchaseorder_supplier_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='suppliers.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
