# Generated by Django 5.2.9 on 2026-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_preferred_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_serial_numbers',
            field=models.BooleanField(default=False, help_text='Track individual items with unique serial numbers'),
        ),
    ]
