# Generated by Django 5.2.9 on 2026-01-26 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_accountingintegration_event_type'),
        ('assets', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='impairment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_impairment_loss', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='revaluation_surplus_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_revaluation_surplus', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='accumulated_impairment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='component_of',
            field=models.ForeignKey(blank=True, help_text='Support for IAS 16 component approach', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='is_intangible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='is_leased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='lease_term_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='revaluation_surplus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='AssetImpairment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impairment_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impairments', to='assets.fixedasset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_fair_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluations', to='assets.fixedasset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
