# Generated by Django 5.2.9 on 2026-01-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_journalentry_exchange_rate_and_more'),
        ('assets', '0002_assetcategory_impairment_account_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField()),
                ('disposal_type', models.CharField(choices=[('sale', 'Sale'), ('scrap', 'Scrap/Write-off'), ('donation', 'Donation'), ('theft_loss', 'Theft/Loss')], max_length=20)),
                ('disposal_proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_at_disposal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accumulated_depreciation_at_disposal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_book_value_at_disposal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gain_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='assets.fixedasset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
