# Generated by Django 5.2.9 on 2026-01-29 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetdisposal'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='total_estimated_units',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total units expected from the asset', max_digits=12),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='units_consumed_to_date',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production'), ('sum_of_years_digits', 'Sum of Years Digits'), ('no_depreciation', 'No Depreciation')], default='straight_line', max_length=20),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('sold', 'Sold'), ('fully_depreciated', 'Fully Depreciated'), ('under_maintenance', 'Under Maintenance')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateField()),
                ('location_confirmed', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('non_functional', 'Non-Functional')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='assets.fixedasset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
