# Generated by Django 5.2.7 on 2025-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, help_text="e.g., 'credit', 'refund'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('type_is_active', models.BooleanField(default=True, help_text='Whether this type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Adjustment Types',
                'ordering': ['order', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='CreditAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('credit', 'Credit'), ('refund', 'Refund'), ('discount', 'Discount')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_description', models.TextField()),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('adjustment_is_active', models.BooleanField(default=True)),
                ('adjustment_created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('pdf_url', models.URLField(blank=True)),
                ('invoice_is_active', models.BooleanField(default=True)),
                ('invoice_created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_is_active', models.BooleanField(default=True)),
                ('payment_created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('bank_account', 'Bank Account'), ('wallet', 'Digital Wallet')], max_length=20)),
                ('display_info', models.CharField(help_text="Masked display info (e.g., '**** 4242', '+254 *** 1234')", max_length=100)),
                ('provider_payment_method_id', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('payment_method_is_active', models.BooleanField(default=True)),
                ('method_created_at', models.DateTimeField(auto_now_add=True)),
                ('method_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(db_index=True, help_text="e.g., 'stripe', 'paypal'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('provider_is_active', models.BooleanField(default=True, help_text='Whether this provider is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Payment Providers',
                'ordering': ['order', 'provider_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_config_name', models.CharField(choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], help_text="e.g., 'stripe', 'paypal'", max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_key', models.TextField()),
                ('secret_key', models.TextField()),
                ('webhook_secret', models.TextField()),
                ('config_is_active', models.BooleanField(default=True)),
                ('config_created_at', models.DateTimeField(auto_now_add=True)),
                ('config_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, help_text="e.g., 'card', 'mobile_money'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('type_is_active', models.BooleanField(default=True, help_text='Whether this type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Payment Types',
                'ordering': ['order', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_annually', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in the plan')),
                ('plan_is_active', models.BooleanField(default=True)),
                ('plan_created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(db_index=True, help_text="e.g., 'starter', 'pro'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('tier_is_active', models.BooleanField(default=True, help_text='Whether this tier is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Plan Tiers',
                'ordering': ['order', 'tier_name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('trialing', 'Trialing')], default='trialing', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_trial_end_date', models.DateTimeField(blank=True, help_text='End date of subscription trial period', null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('subscription_is_active', models.BooleanField(default=True)),
                ('subscription_created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(db_index=True, help_text="e.g., 'active', 'canceled'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('status_is_active', models.BooleanField(default=True, help_text='Whether this status is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Subscription Statuses',
                'ordering': ['order', 'status_name'],
            },
        ),
    ]
