# Generated by Django 5.2.7 on 2025-12-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmenttype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='creditadjustment',
            name='adjustment_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic adjustment type (replaces adjustment_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_adjustments', to='billing.adjustmenttype'),
        ),
        migrations.AddField(
            model_name='creditadjustment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='creditadjustment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_adjustments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='name_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic provider (replaces name field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs', to='billing.paymentprovider'),
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='billing.paymentproviderconfig'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic payment type (replaces type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='billing.paymenttype'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='plantier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic tier (replaces tier field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='billing.plantier'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='creditadjustment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_adjustments', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionstatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='adjustmenttype',
            unique_together={('tenant', 'type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentprovider',
            unique_together={('tenant', 'provider_name')},
        ),
        migrations.AlterUniqueTogether(
            name='paymenttype',
            unique_together={('tenant', 'type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='plantier',
            unique_together={('tenant', 'tier_name')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionstatus',
            unique_together={('tenant', 'status_name')},
        ),
    ]
