# Generated by Django 5.2.9 on 2026-01-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('products', '0007_product_image_product_thumbnail'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 16.00)', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules apply first')),
                ('region', models.CharField(blank=True, choices=[('KE', 'Kenya'), ('US', 'United States'), ('GB', 'United Kingdom'), ('EU', 'European Union')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='billing.taxrate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
