# Generated by Django 5.2.7 on 2025-11-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_notes_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Enable this provider globally')),
                ('config', models.JSONField(default=dict, help_text='Provider-specific configuration (API keys, secrets). Should be encrypted in production.')),
                ('supported_currencies', models.JSONField(default=list, help_text="List of supported currency codes (e.g., ['USD', 'KES', 'EUR'])")),
                ('supports_subscriptions', models.BooleanField(default=True)),
                ('supports_one_time', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Payment Provider Configuration',
                'verbose_name_plural': 'Payment Provider Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, help_text='Payment provider used (stripe, mpesa, paypal, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, help_text='Provider-specific transaction/payment ID', max_length=200),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='Tenant ID if this is for subscription billing', max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, db_index=True, help_text='Customer ID if this is for customer checkout', max_length=50, null=True)),
                ('type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('bank_account', 'Bank Account'), ('wallet', 'Digital Wallet')], max_length=20)),
                ('display_info', models.CharField(help_text="Masked display info (e.g., '**** 4242', '+254 *** 1234')", max_length=100)),
                ('provider_payment_method_id', models.CharField(help_text="Provider's payment method ID (e.g., Stripe pm_xxx, M-Pesa phone number)", max_length=200)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='billing.paymentproviderconfig')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=50)),
                ('is_enabled_for_subscription', models.BooleanField(default=False, help_text="Use this provider to pay for tenant's own subscription")),
                ('is_enabled_for_customers', models.BooleanField(default=False, help_text="Allow tenant's customers to use this provider for checkout")),
                ('tenant_credentials', models.JSONField(blank=True, default=dict, help_text='Tenant-specific credentials (e.g., their own Stripe account, M-Pesa till)')),
                ('priority', models.IntegerField(default=0, help_text='Display order (higher = shown first)')),
                ('custom_label', models.CharField(blank=True, help_text='Custom display name for this provider (optional)', max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_configs', to='billing.paymentproviderconfig')),
            ],
            options={
                'verbose_name': 'Tenant Payment Configuration',
                'verbose_name_plural': 'Tenant Payment Configurations',
                'ordering': ['-priority', 'provider__name'],
                'unique_together': {('tenant_id', 'provider')},
            },
        ),
    ]
