# Generated by Django 5.2.9 on 2026-01-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_chartofaccount_account_type_and_more'),
        ('billing', '0003_taxrate_taxrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='account',
            field=models.ForeignKey(blank=True, help_text='GL Account for Tax Liability/Receivable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_rates', to='accounting.chartofaccount'),
        ),
    ]
