# Generated by Django 5.2.9 on 2026-01-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_taxrate_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrule',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='taxrule',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='taxrule',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='TaxRate',
        ),
        migrations.DeleteModel(
            name='TaxRule',
        ),
    ]
