# Generated by Django 5.2.7 on 2025-11-25 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, unique=True)),
                ('is_throttled', models.BooleanField(default=False)),
                ('throttle_reason', models.TextField(blank=True)),
                ('custom_api_limit', models.IntegerField(blank=True, null=True)),
                ('custom_storage_limit_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_db_connections', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tenant_id'],
            },
        ),
        migrations.CreateModel(
            name='TenantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('api_calls_count', models.IntegerField(default=0)),
                ('api_calls_limit', models.IntegerField(default=10000)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_limit_gb', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('active_db_connections', models.IntegerField(default=0)),
                ('max_db_connections', models.IntegerField(default=20)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['tenant_id', '-measured_at'], name='infrastruct_tenant__c11a0b_idx')],
            },
        ),
    ]
