# Generated by Django 5.2.9 on 2026-01-09 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_alerts', '0001_initial'),
        ('infrastructure', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcorrelationgroup',
            name='affected_tenants',
            field=models.ManyToManyField(blank=True, related_name='correlation_groups', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertcorrelationgroup',
            name='alerts',
            field=models.ManyToManyField(blank=True, related_name='correlation_groups', to='global_alerts.alertinstance'),
        ),
        migrations.AddField(
            model_name='alertcorrelationgroup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correlation_groups_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertcorrelationgroup',
            name='root_cause_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correlation_children', to='global_alerts.alertinstance'),
        ),
        migrations.AddField(
            model_name='alertescalationpath',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_paths_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertnotificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='target_tenants',
            field=models.ManyToManyField(blank=True, related_name='alert_rules_targeted', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='alert_rules_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='applies_to_tenants',
            field=models.ManyToManyField(blank=True, related_name='alert_suppressions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppression_rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Modules that this module depends on', related_name='dependent_modules', to='infrastructure.appmodule'),
        ),
        migrations.AddField(
            model_name='capacityplanning',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_planning_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacityplanning',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_planning', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='infrastructurealert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_alerts_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infrastructurealert',
            name='affected_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_alerts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='infrastructurealert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_alerts_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infrastructureaudit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_changes_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infrastructureaudit',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_changes_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduledependency',
            name='dependent_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_dependencies', to='infrastructure.appmodule'),
        ),
        migrations.AddField(
            model_name='moduledependency',
            name='required_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_modules', to='infrastructure.appmodule'),
        ),
        migrations.AddField(
            model_name='moduleprovisionworkflow',
            name='app_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_workflows', to='infrastructure.appmodule'),
        ),
        migrations.AddField(
            model_name='moduleprovisionworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_provision_workflows_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleprovisionworkflow',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancebaseline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_baselines', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='resourcealert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_alerts_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_alerts_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_allocated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='allocated_to_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='resourcemonitoring',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_monitoring', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='resourcealert',
            name='resource_monitoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='infrastructure.resourcemonitoring'),
        ),
        migrations.AddField(
            model_name='resourcequota',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_quotas', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='resourceusagereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_reports_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceusagereport',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_reports', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantmoduleprovision',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmoduleprovision',
            name='app_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_provisions', to='infrastructure.appmodule'),
        ),
        migrations.AddField(
            model_name='tenantmoduleprovision',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmoduleprovision',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_installed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmoduleprovision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_provisions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantmoduleprovision',
            name='uninstalled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_uninstalled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='alertnotificationpreference',
            unique_together={('user', 'alert_type', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='moduledependency',
            unique_together={('dependent_module', 'required_module')},
        ),
        migrations.AlterUniqueTogether(
            name='performancebaseline',
            unique_together={('baseline_type', 'service_name', 'environment', 'tenant', 'baseline_period')},
        ),
        migrations.AddIndex(
            model_name='resourcemonitoring',
            index=models.Index(fields=['resource_type', 'service_name', 'tenant', '-last_updated'], name='infrastruct_resourc_80fd3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcequota',
            unique_together={('tenant', 'resource_type')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantmoduleprovision',
            unique_together={('tenant', 'app_module')},
        ),
    ]
