# Generated by Django 5.2.9 on 2026-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_interstoretransfer_interstoretransferline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch tracking for FIFO', max_length=100),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='last_valuation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
