# Generated by Django 5.2.9 on 2026-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockadjustment_journal_entry'),
        ('products', '0017_alter_product_preferred_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'ordering': ['product', 'warehouse', 'acquisition_date'], 'verbose_name': 'Stock Level', 'verbose_name_plural': 'Stock Levels'},
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('product', 'warehouse', 'location', 'batch_number')},
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for FEFO', null=True),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='acquisition_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
