# Generated by Django 5.2.9 on 2026-02-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stocklevel_options_and_more'),
        ('products', '0018_product_has_serial_numbers'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=50)),
                ('zone_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Zone',
                'verbose_name_plural': 'Warehouse Zones',
                'ordering': ['warehouse', 'zone_code'],
                'unique_together': {('warehouse', 'zone_code')},
            },
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='inventory.warehousezone'),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('current_status', models.CharField(choices=[('in_stock', 'In Stock'), ('allocated', 'Allocated'), ('dispatched', 'Dispatched'), ('sold', 'Sold'), ('returned', 'Returned'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('maintenance', 'Maintenance')], default='in_stock', max_length=20)),
                ('acquisition_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Serial Number',
                'verbose_name_plural': 'Serial Numbers',
                'ordering': ['product', 'serial_number'],
                'unique_together': {('product', 'serial_number')},
            },
        ),
    ]
