# Generated by Django 5.2.9 on 2026-02-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_warehousezone_stocklocation_zone_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='interstoretransferline',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_out_lines', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='interstoretransferline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='Comma-separated serial numbers being transferred'),
        ),
        migrations.AddField(
            model_name='interstoretransferline',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_in_lines', to='inventory.stocklocation'),
        ),
    ]
