"""
Model Card Service.
Generates standardize Model Cards for transparency and documentation, 
based on "Model Cards for Model Reporting" (Mitchell et al., 2019).
"""

import json
import os
from datetime import datetime
from typing import Dict, Any, Optional
from ml_models.engine.models.foundation.base_model import BaseModel
from ml_models.infrastructure.config.settings import config

class ModelCardService:
    """
    Service for generating and managing ML Model Cards.
    """
    
    def __init__(self):
        self.output_dir = os.path.join(config.model_storage_path, "model_cards")
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_card(self, model: BaseModel, validation_data_summary: Dict[str, Any]) -> str:
        """
        Generates a Model Card in JSON and Markdown formats.
        """
        spec = model.model_spec
        card_data = {
            "model_details": {
                "name": spec.name,
                "id": spec.model_id,
                "version": spec.version,
                "type": spec.model_type.value,
                "algorithm": spec.algorithm,
                "created_at": model.created_at.isoformat(),
                "last_trained": model.last_trained.isoformat() if model.last_trained else None
            },
            "intended_use": {
                "primary_uses": [spec.description],
                "primary_users": ["Sales Teams", "Marketing Managers"],
                "out_of_scope_uses": ["Legal final decisions", "Financial guarantee"]
            },
            "factors": {
                "relevant_factors": ["Industry", "Lead Source", "Engagement Type"],
                "evaluation_factors": ["Accuracy", "F1-Score", "Recall"]
            },
            "metrics": model.performance_metrics,
            "training_data": {
                "features": [f.name for f in spec.features],
                "target": spec.target_variable
            },
            "quantitative_analyses": {
                "validation_summary": validation_data_summary
            },
            "ethical_considerations": {
                "data_bias": "Historical sales data may reflect past biases in territory assignment.",
                "transparency": "Model provides human-readable explanations via XAI service."
            }
        }
        
        # Save JSON
        filename = f"{spec.model_id}_{spec.version}.json"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            json.dump(card_data, f, indent=2)
            
        # Generating Markdown summary
        md_content = self._generate_markdown(card_data)
        md_filepath = filepath.replace(".json", ".md")
        with open(md_filepath, 'w') as f:
            f.write(md_content)
            
        return filepath

    def _generate_markdown(self, data: Dict[str, Any]) -> str:
        details = data["model_details"]
        return f"""# Model Card: {details['name']}

## Model Details
- **ID**: {details['id']}
- **Version**: {details['version']}
- **Type**: {details['type']}
- **Algorithm**: {details['algorithm']}
- **Created**: {details['created_at']}

## Intended Use
- {data['intended_use']['primary_uses'][0]}

## Performance Metrics
{json.dumps(data['metrics'], indent=2)}

## Ethical Considerations
- **Bias**: {data['ethical_considerations']['data_bias']}
- **Transparency**: {data['ethical_considerations']['transparency']}

---
*Generated by SalesCompass ML Governance*
"""
