# Generated by Django 5.2.9 on 2026-01-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('hr', '0002_payrollrun_payrollline'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursed_expenses', to='hr.payrollrun'),
        ),
    ]
