# Generated by Django 5.2.9 on 2026-01-25 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('expenses', '0002_expensereport_payroll_run'),
        ('logistics', '0002_shipment_stop_number_deliveryroute_shipment_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default tax rate for this category', max_digits=5),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_capital_expenditure',
            field=models.BooleanField(default=False, help_text='Default flag for CAPEX tracking'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='is_capex',
            field=models.BooleanField(default=False, help_text='Overridable capitalization flag'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='related_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition_expenses', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='related_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_expenses', to='logistics.deliveryroute'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='related_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_expenses', to='logistics.shipment'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='is_accrued',
            field=models.BooleanField(default=False, help_text='Indicates if the accrual entry has been posted to GL'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash/Petty Cash'), ('bank', 'Bank Transfer'), ('payroll', 'Payroll Reimbursement')], default='cash', max_length=20),
        ),
    ]
