# Generated by Django 5.2.9 on 2026-02-03 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensecategory_default_vat_rate_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid/Reimbursed'), ('pending_approval', 'Pending Approval')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ExpenseApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(help_text='Sequence number of this step (1, 2, 3...)')),
                ('name', models.CharField(help_text="e.g. 'Manager Approval', 'Finance Review'", max_length=100)),
                ('approver_role', models.CharField(blank=True, help_text="e.g. 'manager', 'finance_admin'. System will resolve this dynamically.", max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Step required only if amount >= this value', max_digits=12)),
                ('approver_user', models.ForeignKey(blank=True, help_text='Specific user approver', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddField(
            model_name='expensereport',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_reports', to='expenses.expenseapprovalstep'),
        ),
        migrations.CreateModel(
            name='ExpenseApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expenseapprovalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='expenses.expenseapprovalworkflow'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='approval_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expenseapprovalworkflow'),
        ),
        migrations.CreateModel(
            name='ExpensePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_amount_per_transaction', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed amount for a single line item', max_digits=12, null=True)),
                ('max_amount_daily', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed daily total (per user)', max_digits=12, null=True)),
                ('action_on_violation', models.CharField(choices=[('block', 'Block Submission'), ('warn', 'Show Warning')], default='warn', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Applies to specific category. If null, applies globally.', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Expense Policies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='expenseapprovalstep',
            unique_together={('workflow', 'step_order')},
        ),
    ]
