# Generated by Django 5.2.9 on 2026-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type_name', models.CharField(db_index=True, help_text="e.g., 'email_open', 'link_click'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('action_type_is_active', models.BooleanField(default=True, help_text='Whether this action type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Action Types',
                'ordering': ['order', 'action_type_name'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_rule_name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('leads', 'Leads'), ('cases', 'Cases'), ('opportunities', 'Opportunities')], max_length=50)),
                ('rule_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('territory', 'Territory-Based'), ('load_balanced', 'Load Balanced'), ('criteria', 'Criteria-Based')], max_length=50)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text="Matching criteria, e.g., {'country': 'US', 'industry': 'Tech'}")),
                ('rule_is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('priority', models.IntegerField(default=1, help_text='Priority of the rule (lower numbers = higher priority)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentRuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type_name', models.CharField(db_index=True, help_text="e.g., 'round_robin', 'territory'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('rule_type_is_active', models.BooleanField(default=True, help_text='Whether this rule type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Assignment Rule Types',
                'ordering': ['order', 'rule_type_name'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavioral_scoring_rule_name', models.CharField(help_text="Rule name, e.g., 'Email Open Scoring'", max_length=200)),
                ('action_type', models.CharField(choices=[('email_open', 'Email Open'), ('link_click', 'Link Click'), ('web_visit', 'Website Visit'), ('form_submit', 'Form Submission'), ('content_download', 'Content Download'), ('landing_page_visit', 'Landing Page Visit')], max_length=50)),
                ('points', models.IntegerField(help_text='Points to award for this action')),
                ('time_decay_factor', models.FloatField(default=1.0, help_text="Multiplier for time-based decay of this action's value")),
                ('business_impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=50)),
                ('rule_is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Account', 'Account'), ('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Product', 'Product'), ('Case', 'Case')], max_length=50)),
                ('field_name', models.CharField(help_text="Internal field name (e.g., 'industry_sector')", max_length=100)),
                ('field_label', models.CharField(help_text="Display label (e.g., 'Industry Sector')", max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Checkbox'), ('select', 'Dropdown'), ('textarea', 'Text Area')], default='text', max_length=20)),
                ('field_options', models.JSONField(blank=True, default=list, help_text='Options for select fields')),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.TextField(blank=True, help_text='Help text to display with the field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemographicScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographic_scoring_rule_name', models.CharField(help_text="Rule name, e.g., 'Job Title Scoring'", max_length=200)),
                ('field_name', models.CharField(help_text="Field to evaluate, e.g., 'job_title', 'industry', 'company_size'", max_length=100)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('in', 'In List'), ('gt', 'Greater Than'), ('lt', 'Less Than')], default='equals', max_length=20)),
                ('field_value', models.CharField(help_text='Value to match against', max_length=500)),
                ('points', models.IntegerField(help_text='Points to award when condition is met')),
                ('rule_is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office 365')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('integration_is_active', models.BooleanField(default=True, help_text='Whether this integration is active')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, help_text='API key or access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token for OAuth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type_name', models.CharField(db_index=True, help_text="e.g., 'text', 'number'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('field_type_is_active', models.BooleanField(default=True, help_text='Whether this field type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Field Types',
                'ordering': ['order', 'field_type_name'],
            },
        ),
        migrations.CreateModel(
            name='ModelChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_choice_name', models.CharField(db_index=True, help_text="e.g., 'Account', 'Lead'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('model_choice_is_active', models.BooleanField(default=True, help_text='Whether this model choice is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Model Choices',
                'ordering': ['order', 'model_choice_name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_choice_name', models.CharField(db_index=True, help_text="e.g., 'leads', 'accounts'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('module_choice_is_active', models.BooleanField(default=True, help_text='Whether this module choice is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Module Choices',
                'ordering': ['order', 'module_choice_name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('leads', 'Leads'), ('accounts', 'Accounts'), ('opportunities', 'Opportunities'), ('cases', 'Cases'), ('proposals', 'Proposals'), ('products', 'Products'), ('tasks', 'Tasks'), ('dashboard', 'Dashboard'), ('reports', 'Reports'), ('commissions', 'Commissions')], max_length=50)),
                ('custom_label', models.CharField(help_text="e.g., 'Prospects' instead of 'Leads'", max_length=100)),
                ('module_label_is_active', models.BooleanField(default=True, help_text='Whether this module label is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(db_index=True, help_text="e.g., 'equals', 'contains'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('operator_is_active', models.BooleanField(default=True, help_text='Whether this operator is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Operator Types',
                'ordering': ['order', 'operator_name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(choices=[('sales', 'Sales Pipeline'), ('support', 'Support Pipeline'), ('onboarding', 'Customer Onboarding'), ('renewal', 'Renewal Process')], max_length=50)),
                ('pipeline_stage_name', models.CharField(help_text="Stage name, e.g., 'Discovery', 'Negotiation', 'Closed Won'", max_length=100)),
                ('stage_description', models.TextField(blank=True, help_text='Description of the pipeline stage')),
                ('order', models.IntegerField(default=0)),
                ('probability', models.DecimalField(decimal_places=2, default=0.0, help_text='Default probability for this stage (0-100)', max_digits=5)),
                ('is_won_stage', models.BooleanField(default=False, help_text='Whether this stage represents a won opportunity')),
                ('is_lost_stage', models.BooleanField(default=False, help_text='Whether this stage represents a lost opportunity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type_name', models.CharField(db_index=True, help_text="e.g., 'sales', 'support'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('pipeline_type_is_active', models.BooleanField(default=True, help_text='Whether this pipeline type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pipeline Types',
                'ordering': ['order', 'pipeline_type_name'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200, unique=True)),
                ('setting_label', models.CharField(max_length=200)),
                ('setting_description', models.TextField(blank=True, help_text='Description of the setting')),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Dropdown'), ('json', 'JSON')], default='text', max_length=20)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_group_name', models.CharField(help_text='Name of the setting group', max_length=200, unique=True)),
                ('setting_group_description', models.TextField(blank=True, help_text='Description of the setting group')),
                ('setting_group_is_active', models.BooleanField(default=True, help_text='Whether this setting group is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type_name', models.CharField(db_index=True, help_text="e.g., 'text', 'number'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('setting_type_is_active', models.BooleanField(default=True, help_text='Whether this setting type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Setting Types',
                'ordering': ['order', 'setting_type_name'],
            },
        ),
    ]
