# Generated by Django 5.2.7 on 2025-11-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomationRule',
        ),
    ]
