# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0002_initial'),
        ('settings_app', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='assignmentrule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='assignmentruletype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='assignmentrule',
            name='rule_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic rule type (replaces rule_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='settings_app.assignmentruletype'),
        ),
        migrations.AddField(
            model_name='behavioralscoringrule',
            name='action_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic action type (replaces action_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='behavioral_scoring_rules', to='settings_app.actiontype'),
        ),
        migrations.AddField(
            model_name='behavioralscoringrule',
            name='business_impact_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic business impact (replaces business_impact field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavioral_scoring_rules_by_impact', to='settings_app.behavioralscoringrule'),
        ),
        migrations.AddField(
            model_name='behavioralscoringrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='demographicscoringrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='provider_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic provider (replaces provider field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_integrations', to='marketing.emailprovider'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='field_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic field type (replaces field_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_fields', to='settings_app.fieldtype'),
        ),
        migrations.AddField(
            model_name='modelchoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='model_name_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic model name (replaces model_name field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_fields', to='settings_app.modelchoice'),
        ),
        migrations.AddField(
            model_name='modulechoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='assignmentrule',
            name='module_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic module (replaces module field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='settings_app.modulechoice'),
        ),
        migrations.AddField(
            model_name='modulelabel',
            name='module_key_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic module key (replaces module_key field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='module_labels', to='settings_app.modulechoice'),
        ),
        migrations.AddField(
            model_name='modulelabel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='operatortype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='demographicscoringrule',
            name='operator_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic operator (replaces operator field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demographic_scoring_rules', to='settings_app.operatortype'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pipelinetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='pipeline_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic pipeline type (replaces pipeline_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_stages', to='settings_app.pipelinetype'),
        ),
        migrations.AddField(
            model_name='setting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='settinggroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='setting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings_app.settinggroup'),
        ),
        migrations.AddField(
            model_name='settingtype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='setting',
            name='setting_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic setting type (replaces setting_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='settings_app.settingtype'),
        ),
        migrations.AlterUniqueTogether(
            name='actiontype',
            unique_together={('tenant_id', 'action_type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentruletype',
            unique_together={('tenant_id', 'rule_type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldtype',
            unique_together={('tenant_id', 'field_type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='modelchoice',
            unique_together={('tenant_id', 'model_choice_name')},
        ),
        migrations.AlterUniqueTogether(
            name='modulechoice',
            unique_together={('tenant_id', 'module_choice_name')},
        ),
        migrations.AlterUniqueTogether(
            name='operatortype',
            unique_together={('tenant_id', 'operator_name')},
        ),
        migrations.AlterUniqueTogether(
            name='pipelinetype',
            unique_together={('tenant_id', 'pipeline_type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='settingtype',
            unique_together={('tenant_id', 'setting_type_name')},
        ),
    ]
