# Generated by Django 6.0.2 on 2026-02-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settinggroup',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='settingtype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='settingtype',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='SettingGroup',
        ),
        migrations.DeleteModel(
            name='SettingType',
        ),
    ]
