# Generated by Django 5.2.7 on 2025-11-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_delete_automationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('model_name', models.CharField(choices=[('Account', 'Account'), ('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Product', 'Product'), ('Case', 'Case')], max_length=50)),
                ('field_name', models.CharField(help_text="Internal field name (e.g., 'industry_sector')", max_length=100)),
                ('field_label', models.CharField(help_text="Display label (e.g., 'Industry Sector')", max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Checkbox'), ('select', 'Dropdown'), ('textarea', 'Text Area')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/dropdown fields')),
                ('default_value', models.TextField(blank=True)),
                ('help_text', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['model_name', 'order'],
                'unique_together': {('tenant_id', 'model_name', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='ModuleLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('module_key', models.CharField(choices=[('leads', 'Leads'), ('accounts', 'Accounts'), ('opportunities', 'Opportunities'), ('cases', 'Cases'), ('proposals', 'Proposals'), ('products', 'Products'), ('tasks', 'Tasks'), ('dashboard', 'Dashboard'), ('reports', 'Reports'), ('commissions', 'Commissions')], max_length=50)),
                ('custom_label', models.CharField(help_text="e.g., 'Prospects' instead of 'Leads'", max_length=100)),
                ('custom_label_plural', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('tenant_id', 'module_key')},
            },
        ),
    ]
