# Generated by Django 5.2.7 on 2025-11-22 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_customfield_modulelabel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('leads', 'Leads'), ('cases', 'Cases'), ('opportunities', 'Opportunities')], max_length=50)),
                ('rule_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('territory', 'Territory-Based'), ('load_balanced', 'Load Balanced'), ('criteria', 'Criteria-Based')], max_length=50)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text="Matching criteria, e.g., {'country': 'US', 'industry': 'Tech'}")),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('is_active', models.BooleanField(default=True)),
                ('last_assigned_index', models.IntegerField(default=0)),
                ('assignees', models.ManyToManyField(help_text='Users to distribute records to', related_name='assignment_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
