# Generated by Django 5.2.7 on 2025-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_assignmentrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('pipeline_type', models.CharField(choices=[('sales', 'Sales Pipeline'), ('support', 'Support Pipeline'), ('onboarding', 'Customer Onboarding'), ('renewal', 'Renewal Process')], max_length=50)),
                ('name', models.CharField(help_text="Stage name, e.g., 'Discovery', 'Negotiation', 'Closed Won'", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order in the pipeline')),
                ('probability', models.IntegerField(default=0, help_text='Win probability percentage (0-100)')),
                ('required_fields', models.JSONField(blank=True, default=list, help_text='Fields that must be filled before moving to this stage')),
                ('approval_required', models.BooleanField(default=False, help_text='Requires manager approval to enter this stage')),
                ('is_closed', models.BooleanField(default=False, help_text='Marks the end of the pipeline (won/lost)')),
                ('is_won', models.BooleanField(default=False, help_text='Indicates a successful outcome')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for visual representation', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pipeline_type', 'order'],
                'unique_together': {('tenant_id', 'pipeline_type', 'name')},
            },
        ),
    ]
