# Generated by Django 5.2.7 on 2025-11-22 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_pipelinestage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Endpoint URL to POST events to')),
                ('events', models.JSONField(default=list, help_text="Event types to subscribe to, e.g., ['lead.created', 'opportunity.won']")),
                ('secret', models.CharField(help_text='Secret for HMAC signature verification', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=200)),
                ('key_prefix', models.CharField(help_text='First 8 characters of the key for identification', max_length=8)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the full key', max_length=64)),
                ('scopes', models.JSONField(default=list, help_text="List of allowed permissions, e.g., ['accounts:read', 'leads:write']")),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office 365')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('access_token', models.TextField(help_text='Encrypted OAuth access token')),
                ('refresh_token', models.TextField(help_text='Encrypted OAuth refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_calendar', models.BooleanField(default=False, help_text='Sync calendar events')),
                ('sync_contacts', models.BooleanField(default=False, help_text='Sync contacts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider', 'email_address')},
            },
        ),
    ]
