# Generated by Django 5.2.7 on 2025-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_webhook_apikey_emailintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(help_text="Rule name, e.g., 'Email Open Scoring'", max_length=200)),
                ('action_type', models.CharField(choices=[('email_open', 'Email Open'), ('link_click', 'Link Click'), ('web_visit', 'Website Visit'), ('form_submit', 'Form Submission'), ('content_download', 'Content Download'), ('landing_page_visit', 'Landing Page Visit')], max_length=50)),
                ('points', models.IntegerField(help_text='Points to award for this action')),
                ('frequency_cap', models.IntegerField(default=0, help_text='Max times this action scores per lead per day (0 = unlimited)')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DemographicScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(help_text="Rule name, e.g., 'Enterprise Company Scoring'", max_length=200)),
                ('field_name', models.CharField(help_text="Field to evaluate, e.g., 'job_title', 'industry', 'company_size'", max_length=100)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('in', 'In List'), ('gt', 'Greater Than'), ('lt', 'Less Than')], default='equals', max_length=20)),
                ('field_value', models.CharField(help_text='Value to match against', max_length=500)),
                ('points', models.IntegerField(help_text='Points to award if condition matches')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreDecayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('decay_enabled', models.BooleanField(default=False, help_text='Enable automatic score decay')),
                ('decay_rate', models.FloatField(default=5.0, help_text='Percentage to decay per period (e.g., 5 = 5% decay)')),
                ('decay_period_days', models.IntegerField(default=30, help_text='Days between decay applications')),
                ('min_score', models.IntegerField(default=0, help_text='Minimum score floor (decay stops here)')),
                ('last_decay_run', models.DateTimeField(blank=True, help_text='Last time decay was applied', null=True)),
            ],
            options={
                'verbose_name': 'Score Decay Configuration',
                'verbose_name_plural': 'Score Decay Configurations',
            },
        ),
    ]
