# Generated by Django 5.2.7 on 2025-12-16 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('totp', 'Time-based OTP'), ('hotp', 'HMAC-based OTP'), ('sms', 'SMS'), ('email', 'Email'), ('hardware', 'Hardware Token'), ('push_notification', 'Push Notification')], max_length=20)),
                ('device_name', models.CharField(help_text='Friendly name for the device', max_length=100)),
                ('secret_key', models.CharField(help_text='Secret key for TOTP/HOTP', max_length=32)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary MFA device?')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='List of backup codes')),
                ('backup_codes_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MFA Device',
                'verbose_name_plural': 'MFA Devices',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales_rep', 'Sales Representative'), ('sales_manager', 'Sales Manager'), ('account_manager', 'Account Manager'), ('sales_director', 'Sales Director'), ('ceo', 'CEO'), ('admin', 'Administrator')], max_length=50)),
                ('territory', models.CharField(blank=True, choices=[('north_america', 'North America'), ('emea', 'EMEA'), ('apac', 'APAC'), ('latam', 'Latin America')], max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('onboarding', 'Onboarding'), ('leave', 'On Leave'), ('terminated', 'Terminated')], default='onboarding', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('quota_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quota_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='quarterly', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate (e.g. 10.0 for 10%)', max_digits=5)),
                ('territory_performance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Performance score within assigned territory (0-100)', max_digits=5)),
                ('territory_quota_attainment', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of territory quota attained', max_digits=5)),
                ('territory_conversion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Lead to opportunity conversion rate in territory (%)', max_digits=5)),
                ('territory_revenue_contribution', models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue contribution to assigned territory', max_digits=12)),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_assignable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_identifier', models.CharField(help_text="Unique identifier for the app (e.g., 'reachout', 'tenants')", max_length=100)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this app is visible to the role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role App Permission',
                'verbose_name_plural': 'Role App Permissions',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('permission_added', 'Permission Added'), ('permission_removed', 'Permission Removed'), ('role_assigned', 'Role Assigned'), ('role_unassigned', 'Role Unassigned'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted')], max_length=20)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before change')),
                ('new_value', models.TextField(blank=True, help_text='New value after change')),
                ('reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Role Permission Audit',
                'verbose_name_plural': 'Role Permission Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(db_index=True, help_text="e.g., 'sales_rep', 'sales_manager'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('role_is_active', models.BooleanField(default=True, help_text='Whether this role is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Team Roles',
                'ordering': ['order', 'role_name'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_name', models.CharField(db_index=True, help_text="e.g., 'north_america', 'emea'", max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('territory_is_active', models.BooleanField(default=True, help_text='Whether this territory is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Territories',
                'ordering': ['order', 'territory_name'],
            },
        ),
        migrations.CreateModel(
            name='UserAccessReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_cycle', models.CharField(choices=[('quarterly', 'Quarterly'), ('semi_annually', 'Semi-Annually'), ('annually', 'Annually'), ('on_demand', 'On Demand')], max_length=50)),
                ('review_type', models.CharField(choices=[('role_based', 'Role Based'), ('permission_based', 'Permission Based'), ('data_access', 'Data Access'), ('system_access', 'System Access')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('access_confirmed', models.BooleanField(blank=True, help_text='Whether access was confirmed or revoked', null=True)),
                ('access_revoked_reason', models.TextField(blank=True, help_text='Reason if access was revoked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Access Review',
                'verbose_name_plural': 'User Access Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('session_start', 'Session Start'), ('session_end', 'Session End'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('mfa_setup', 'MFA Setup'), ('mfa_disable', 'MFA Disable'), ('permission_change', 'Permission Change'), ('role_change', 'Role Change'), ('data_access', 'Data Access'), ('data_export', 'Data Export'), ('data_import', 'Data Import'), ('record_create', 'Record Create'), ('record_update', 'Record Update'), ('record_delete', 'Record Delete'), ('file_upload', 'File Upload'), ('file_download', 'File Download'), ('api_call', 'API Call'), ('settings_change', 'Settings Change'), ('configuration_change', 'Configuration Change')], max_length=100)),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource accessed', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the resource accessed', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of the action in seconds', null=True)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certification_type', models.CharField(choices=[('access_review', 'Access Review'), ('role_verification', 'Role Verification'), ('permission_audit', 'Permission Audit'), ('compliance_check', 'Compliance Check')], max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Reason for certification')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('next_review_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'User Certification',
                'verbose_name_plural': 'User Certifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingWorkflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('steps_completed', models.JSONField(blank=True, default=list, help_text='List of completed onboarding steps')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_days', models.IntegerField(default=7, help_text='Estimated days to complete onboarding')),
                ('profile_setup_complete', models.BooleanField(default=False)),
                ('security_setup_complete', models.BooleanField(default=False)),
                ('tutorial_complete', models.BooleanField(default=False)),
                ('integration_setup_complete', models.BooleanField(default=False)),
                ('team_invitation_sent', models.BooleanField(default=False)),
                ('team_invitation_accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Onboarding Workflow',
                'verbose_name_plural': 'User Onboarding Workflows',
            },
        ),
    ]
