# Generated by Django 5.2.7 on 2025-11-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('manufacturing', 'Manufacturing'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('energy', 'Energy'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('esg_engagement', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('sustainability_goals', models.TextField(blank=True)),
                ('health_score', models.FloatField(default=0.0)),
                ('clv', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned')], default='active', max_length=20)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('ccpa_consent', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('communication_preference', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('none', 'None')], default='email', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('esg_influence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Inferred from engagement with ESG materials', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
