# Generated by Django 5.2.7 on 2025-12-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.organizationmember'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='quota_period_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic quota period (replaces quota_period field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_members_by_period', to='accounts.organizationmember'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic status (replaces status field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_members_by_status', to='accounts.organizationmember'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='roleapppermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='rolepermissionaudit',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='rolepermissionaudit',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='rolepermissionaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permission_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_team_roles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='role_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic role (replaces role field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_members', to='accounts.teamrole'),
        ),
        migrations.AddField(
            model_name='territory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_territories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='territory_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic territory (replaces territory field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_members', to='accounts.territory'),
        ),
        migrations.AddField(
            model_name='useraccessreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_reviews_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccessreview',
            name='subject_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='certifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useronboardingworkflow',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_workflow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mfadevice',
            unique_together={('user', 'device_name')},
        ),
        migrations.AlterUniqueTogether(
            name='roleapppermission',
            unique_together={('role', 'app_identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='teamrole',
            unique_together={('tenant', 'role_name')},
        ),
        migrations.AlterUniqueTogether(
            name='territory',
            unique_together={('tenant', 'territory_name')},
        ),
    ]
