# Generated by Django 5.2.7 on 2025-12-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_identifier', models.CharField(help_text="Unique identifier for the app (e.g., 'reachout', 'tenants')", max_length=100)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this app is visible to the role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role App Permission',
                'verbose_name_plural': 'Role App Permissions',
                'unique_together': {('role', 'app_identifier')},
            },
        ),
    ]
