# Generated by Django 5.2.9 on 2026-01-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned')], default='active', max_length=20),
        ),
    ]
