# Generated by Django 5.2.7 on 2025-12-11 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_roleapppermission'),
        ('settings_app', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales_rep', 'Sales Representative'), ('sales_manager', 'Sales Manager'), ('account_manager', 'Account Manager'), ('sales_director', 'Sales Director'), ('ceo', 'CEO'), ('admin', 'Administrator')], max_length=50)),
                ('territory', models.CharField(blank=True, choices=[('north_america', 'North America'), ('emea', 'EMEA'), ('apac', 'APAC'), ('latam', 'Latin America')], max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('onboarding', 'Onboarding'), ('leave', 'On Leave'), ('terminated', 'Terminated')], default='onboarding', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('quota_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quota_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='quarterly', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate (e.g. 10.0 for 10%)', max_digits=5)),
                ('territory_performance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Performance score within assigned territory (0-100)', max_digits=5)),
                ('territory_quota_attainment', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of territory quota attained', max_digits=5)),
                ('territory_conversion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Lead to opportunity conversion rate in territory (%)', max_digits=5)),
                ('territory_revenue_contribution', models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue contribution to assigned territory', max_digits=12)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.organizationmember')),
                ('quota_period_ref', models.ForeignKey(blank=True, help_text='Dynamic quota period (replaces quota_period field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_members_by_period', to='accounts.organizationmember')),
                ('role_ref', models.ForeignKey(blank=True, help_text='Dynamic role (replaces role field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_members', to='settings_app.teamrole')),
                ('status_ref', models.ForeignKey(blank=True, help_text='Dynamic status (replaces status field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_members_by_status', to='accounts.organizationmember')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('territory_ref', models.ForeignKey(blank=True, help_text='Dynamic territory (replaces territory field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_members', to='settings_app.territory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
            },
        ),
    ]
