# Generated by Django 5.2.9 on 2026-01-12 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_role_alter_accesscontrol_role'),
        ('accounts', '0004_account_annual_revenue_account_billing_address_line1_and_more'),
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermissionaudit',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to='access_control.role'),
        ),
        # Delete RoleAppPermission first (it has FK to Role)
        migrations.DeleteModel(
            name='RoleAppPermission',
        ),
        # Then delete Role
        migrations.DeleteModel(
            name='Role',
        ),
    ]
