# Generated by Django 5.2.7 on 2025-12-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizationmember'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(db_index=True, help_text="e.g., 'sales_rep', 'sales_manager'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('role_is_active', models.BooleanField(default=True, help_text='Whether this role is active')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_team_roles', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Team Roles',
                'ordering': ['order', 'role_name'],
                'unique_together': {('tenant', 'role_name')},
            },
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic role (replaces role field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_members', to='accounts.teamrole'),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_name', models.CharField(db_index=True, help_text="e.g., 'north_america', 'emea'", max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('territory_is_active', models.BooleanField(default=True, help_text='Whether this territory is active')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_territories', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Territories',
                'ordering': ['order', 'territory_name'],
                'unique_together': {('tenant', 'territory_name')},
            },
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='territory_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic territory (replaces territory field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_members', to='accounts.territory'),
        ),
    ]
