# Generated by Django 5.2.9 on 2026-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_rolepermissionaudit_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='csr_ready',
            field=models.BooleanField(default=False, help_text='Whether the account is ready for CSR reporting'),
        ),
        migrations.AddField(
            model_name='account',
            name='esg_certified',
            field=models.BooleanField(default=False, help_text='Whether the account has ESG certification'),
        ),
        migrations.AddField(
            model_name='account',
            name='overall_esg_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overall ESG score', max_digits=5),
        ),
        migrations.AddField(
            model_name='account',
            name='sustainability_goals',
            field=models.TextField(blank=True, help_text='Sustainability goals for the account'),
        ),
        migrations.AddField(
            model_name='account',
            name='tco2e_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tonnes of CO2 equivalent saved', max_digits=10),
        ),
    ]
