# Generated by Django 5.2.9 on 2026-01-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_csr_ready_account_esg_certified_and_more'),
        ('products', '0009_pricelist_pricelistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='price_list',
            field=models.ForeignKey(blank=True, help_text='Assigned price list for this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='products.pricelist'),
        ),
    ]
