# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('auto_winner', models.BooleanField(default=False, help_text='Automatically declare winner')),
                ('winner_variant', models.CharField(blank=True, choices=[('A', 'Variant A'), ('B', 'Variant B'), ('C', 'Variant C'), ('D', 'Variant D')], max_length=1, null=True)),
                ('is_winner_declared', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, help_text='When the test started', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the test ended', null=True)),
                ('confidence_level', models.FloatField(default=95.0, help_text='Confidence level for statistical significance (%)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ABTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('conversion_at', models.DateTimeField(blank=True, help_text='When a conversion event occurred', null=True)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value of conversion', max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ABTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.CharField(choices=[('A', 'Variant A'), ('B', 'Variant B'), ('C', 'Variant C'), ('D', 'Variant D')], max_length=1)),
                ('assignment_rate', models.FloatField(default=0.5, help_text='Proportion of recipients (0.0-1.0)')),
                ('question_text', models.TextField(blank=True, help_text='Question for survey-based tests')),
                ('follow_up_question', models.TextField(blank=True, help_text='Follow-up question if needed')),
                ('delivery_delay_hours', models.IntegerField(default=0, help_text='Delay in hours before sending')),
                ('sent_count', models.IntegerField(default=0, help_text='Number of emails sent')),
                ('open_count', models.IntegerField(default=0, help_text='Number of emails opened')),
                ('click_count', models.IntegerField(default=0, help_text='Number of links clicked')),
                ('conversion_count', models.IntegerField(default=0, help_text='Number of conversions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(db_index=True, help_text="e.g., 'hero', 'features'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('type_is_active', models.BooleanField(default=True, help_text='Whether this type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Block Types',
                'ordering': ['order', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_name', models.CharField(help_text='Name of the campaign', max_length=255)),
                ('campaign_description', models.TextField(blank=True, help_text='Description of the campaign')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_audience_size', models.IntegerField(default=0)),
                ('actual_reach', models.IntegerField(default=0)),
                ('campaign_is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchpoint_date', models.DateTimeField(help_text='When the interaction occurred')),
                ('weight', models.FloatField(default=1.0, help_text='Attribution weight (0.0 - 1.0)')),
                ('attribution_model', models.CharField(choices=[('first_touch', 'First Touch'), ('last_touch', 'Last Touch'), ('linear', 'Linear'), ('time_decay', 'Time Decay'), ('u_shaped', 'U-Shaped')], default='first_touch', max_length=50)),
                ('revenue_share', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated revenue share based on weight and opportunity value', max_digits=14)),
                ('attribution_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign Attribution',
                'verbose_name_plural': 'Campaign Attributions',
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('merge_data', models.JSONField(blank=True, default=dict, help_text='Data for personalization')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_name', models.CharField(db_index=True, help_text="e.g., 'draft', 'scheduled'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('status_is_active', models.BooleanField(default=True, help_text='Whether this status is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Campaign Statuses',
                'ordering': ['order', 'status_name'],
            },
        ),
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DripEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('next_execution_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DripStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_type', models.CharField(choices=[('email', 'Send Email'), ('wait', 'Wait')], default='email', max_length=20)),
                ('wait_days', models.PositiveIntegerField(default=0)),
                ('wait_hours', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_name', models.CharField(help_text='Name of the email campaign', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('recipients', models.JSONField(default=list, help_text='List of recipient emails or criteria')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_send_time', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_provider', models.CharField(choices=[('ses', 'Amazon SES'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('native', 'Django Email')], default='native', max_length=20)),
                ('tracking_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(db_index=True, help_text="e.g., 'newsletter', 'transactional'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('category_is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Email Categories',
                'ordering': ['order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('spam', 'Marked as Spam'), ('unsubscribed', 'Unsubscribed')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the event')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office 365')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('integration_is_active', models.BooleanField(default=True, help_text='Whether this integration is active')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, help_text='API key or access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token for OAuth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(db_index=True, help_text="e.g., 'gmail', 'outlook'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('provider_is_active', models.BooleanField(default=True, help_text='Whether this provider is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Email Providers',
                'ordering': ['order', 'provider_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(help_text='Name of the email template', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML content of the email')),
                ('preview_text', models.TextField(blank=True, help_text='Preview text that appears in email clients')),
                ('category', models.CharField(choices=[('newsletter', 'Newsletter'), ('transactional', 'Transactional'), ('follow_up', 'Follow-up'), ('welcome', 'Welcome'), ('reminder', 'Reminder'), ('promotional', 'Promotional'), ('other', 'Other')], default='other', max_length=20)),
                ('template_is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_name', models.CharField(help_text='Name of the landing page', max_length=255)),
                ('page_slug', models.SlugField(help_text='URL slug for the landing page', unique=True)),
                ('title', models.CharField(help_text='Page title for SEO', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('page_is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features'), ('testimonials', 'Testimonials'), ('pricing', 'Pricing'), ('cta', 'Call to Action'), ('faq', 'FAQ'), ('text', 'Text Content'), ('image', 'Image'), ('video', 'Video'), ('form', 'Contact Form')], max_length=20)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0, help_text='Order of the block on the page')),
                ('block_is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(db_index=True, help_text="e.g., 'reminder', 'notification'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('category_is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Message Categories',
                'ordering': ['order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(help_text='Name of the message template', max_length=255)),
                ('message_template_description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Message content with merge tag support')),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('in_app', 'In-App Message'), ('push', 'Push Notification'), ('slack', 'Slack Message')], max_length=20)),
                ('category', models.CharField(choices=[('reminder', 'Reminder'), ('notification', 'Notification'), ('alert', 'Alert'), ('update', 'Update'), ('other', 'Other')], default='other', max_length=20)),
                ('template_is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(db_index=True, help_text="e.g., 'sms', 'in_app'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('type_is_active', models.BooleanField(default=True, help_text='Whether this type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Message Types',
                'ordering': ['order', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='NurtureCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('trigger_event', models.CharField(help_text='Event that starts the nurture (e.g., form submission, page visit)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NurtureCampaignEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='active', max_length=20)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NurtureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField(help_text='Order of the step in the sequence')),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Days to wait after trigger or previous step before sending')),
                ('delay_hours', models.PositiveIntegerField(default=0, help_text='Additional hours to wait (added to delay_days)')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('segment_type', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=20)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Criteria for dynamic segments')),
                ('member_count', models.IntegerField(default=0, help_text='Number of contacts in this segment')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SegmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ABAutomatedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(help_text='Name of the A/B test', max_length=255)),
                ('test_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('sample_size', models.IntegerField(default=100)),
                ('winner', models.CharField(blank=True, choices=[('A', 'Variant A'), ('B', 'Variant B'), ('C', 'Variant C'), ('D', 'Variant D')], max_length=1, null=True)),
                ('winning_metric', models.CharField(blank=True, help_text='Metric that determined the winner', max_length=50)),
                ('test_created_at', models.DateTimeField(auto_now_add=True)),
                ('test_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
