# Generated by Django 5.2.7 on 2025-11-07 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('winner_variant', models.CharField(blank=True, max_length=10)),
                ('min_responses', models.IntegerField(default=1000)),
                ('confidence_level', models.FloatField(default=0.95)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('plain_text_content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('html_content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('variant', models.CharField(choices=[('A', 'Variant A'), ('B', 'Variant B')], max_length=1)),
                ('assignment_rate', models.FloatField(default=0.5)),
                ('ab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketing.abtest')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.emailtemplate')),
                ('landing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.landingpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features'), ('testimonials', 'Testimonials'), ('pricing', 'Pricing'), ('cta', 'Call to Action'), ('faq', 'FAQ'), ('text', 'Text Content'), ('image', 'Image'), ('video', 'Video'), ('form', 'Contact Form')], max_length=20)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='marketing.landingpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('target_list', models.JSONField(blank=True, default=list)),
                ('segment_filter', models.JSONField(blank=True, default=dict)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_replied', models.IntegerField(default=0)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='marketing.marketingcampaign'),
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('email_provider', models.CharField(choices=[('ses', 'Amazon SES'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('native', 'Django Email')], default='native', max_length=20)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.emailtemplate')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='marketing.marketingcampaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='abtest',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='marketing.marketingcampaign'),
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingcampaign')),
            ],
            options={
                'unique_together': {('campaign', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('open_rate', models.FloatField(default=0.0, help_text='Percentage of emails opened')),
                ('click_rate', models.FloatField(default=0.0, help_text='Percentage of emails clicked')),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Percentage of conversions')),
                ('total_sent', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='marketing.marketingcampaign')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['campaign', 'date'], name='marketing_c_campaig_4e8f0d_idx'), models.Index(fields=['date'], name='marketing_c_date_4cf383_idx')],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.marketingcampaign')),
            ],
            options={
                'unique_together': {('email', 'tenant_id')},
            },
        ),
    ]
