# Generated by Django 5.2.7 on 2025-12-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('merge_data', models.JSONField(blank=True, default=dict, help_text='Data for personalization')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(db_index=True, help_text="e.g., 'draft', 'scheduled'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('status_is_active', models.BooleanField(default=True, help_text='Whether this status is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Campaign Statuses',
                'ordering': ['order', 'status_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text='Name of the email campaign', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('recipients', models.JSONField(default=list, help_text='List of recipient emails or criteria')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_send_time', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_provider', models.CharField(choices=[('ses', 'Amazon SES'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('native', 'Django Email')], default='native', max_length=20)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('bounce_count', models.IntegerField(default=0)),
                ('complaint_count', models.IntegerField(default=0)),
                ('campaign_created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, help_text="e.g., 'newsletter', 'transactional'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('category_is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Email Categories',
                'ordering': ['order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office 365')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('integration_is_active', models.BooleanField(default=True, help_text='Whether this integration is active')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, help_text='API key or access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token for OAuth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(db_index=True, help_text="e.g., 'gmail', 'outlook'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('provider_is_active', models.BooleanField(default=True, help_text='Whether this provider is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Email Providers',
                'ordering': ['order', 'provider_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Name of the email template', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML content of the email')),
                ('preview_text', models.TextField(blank=True, help_text='Preview text that appears in email clients')),
                ('category', models.CharField(choices=[('newsletter', 'Newsletter'), ('transactional', 'Transactional'), ('follow_up', 'Follow-up'), ('welcome', 'Welcome'), ('reminder', 'Reminder'), ('promotional', 'Promotional'), ('other', 'Other')], default='other', max_length=20)),
                ('template_is_active', models.BooleanField(default=True)),
                ('template_created_at', models.DateTimeField(auto_now_add=True)),
                ('template_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Name of the landing page', max_length=255)),
                ('page_slug', models.SlugField(help_text='URL slug for the landing page', unique=True)),
                ('title', models.CharField(help_text='Page title for SEO', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('page_is_active', models.BooleanField(default=True)),
                ('page_created_at', models.DateTimeField(auto_now_add=True)),
                ('page_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features'), ('testimonials', 'Testimonials'), ('pricing', 'Pricing'), ('cta', 'Call to Action'), ('faq', 'FAQ'), ('text', 'Text Content'), ('image', 'Image'), ('video', 'Video'), ('form', 'Contact Form')], max_length=20)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0, help_text='Order of the block on the page')),
                ('block_is_active', models.BooleanField(default=True)),
                ('block_created_at', models.DateTimeField(auto_now_add=True)),
                ('block_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, help_text="e.g., 'reminder', 'notification'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('category_is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Message Categories',
                'ordering': ['order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Name of the message template', max_length=255)),
                ('message_template_description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Message content with merge tag support')),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('in_app', 'In-App Message'), ('push', 'Push Notification'), ('slack', 'Slack Message')], max_length=20)),
                ('category', models.CharField(choices=[('reminder', 'Reminder'), ('notification', 'Notification'), ('alert', 'Alert'), ('update', 'Update'), ('other', 'Other')], default='other', max_length=20)),
                ('template_is_active', models.BooleanField(default=True)),
                ('template_created_at', models.DateTimeField(auto_now_add=True)),
                ('template_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, help_text="e.g., 'sms', 'in_app'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('type_is_active', models.BooleanField(default=True, help_text='Whether this type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Message Types',
                'ordering': ['order', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, help_text="e.g., 'hero', 'features'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('type_is_active', models.BooleanField(default=True, help_text='Whether this type is active')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Block Types',
                'ordering': ['order', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text='Name of the campaign', max_length=255)),
                ('campaign_description', models.TextField(blank=True, help_text='Description of the campaign')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_audience_size', models.IntegerField(default=0)),
                ('actual_reach', models.IntegerField(default=0)),
                ('campaign_is_active', models.BooleanField(default=True)),
                ('campaign_created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ABAutomatedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Name of the A/B test', max_length=255)),
                ('test_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('sample_size', models.IntegerField(default=100)),
                ('winner', models.CharField(blank=True, choices=[('A', 'Variant A'), ('B', 'Variant B')], max_length=1, null=True)),
                ('winning_metric', models.CharField(blank=True, help_text='Metric that determined the winner', max_length=50)),
                ('test_created_at', models.DateTimeField(auto_now_add=True)),
                ('test_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='marketing.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchpoint_date', models.DateTimeField(help_text='When the interaction occurred')),
                ('weight', models.FloatField(default=1.0, help_text='Attribution weight (0.0 - 1.0)')),
                ('attribution_model', models.CharField(choices=[('first_touch', 'First Touch'), ('last_touch', 'Last Touch'), ('linear', 'Linear'), ('time_decay', 'Time Decay'), ('u_shaped', 'U-Shaped')], default='first_touch', max_length=50)),
                ('revenue_share', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated revenue share based on weight and opportunity value', max_digits=14)),
                ('attribution_created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='marketing.campaign')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_attributions', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Campaign Attribution',
                'verbose_name_plural': 'Campaign Attributions',
            },
        ),
    ]
