# Generated by Django 5.2.9 on 2026-01-09 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('leads', '0002_initial'),
        ('marketing', '0001_initial'),
        ('opportunities', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abautomatedtest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abtest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='abtestresponse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='abtestvariant',
            name='ab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketing.abtest'),
        ),
        migrations.AddField(
            model_name='abtestvariant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='abtestresponse',
            name='ab_test_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='marketing.abtestvariant'),
        ),
        migrations.AddField(
            model_name='blocktype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_new_tests', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='abautomatedtest',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_attributions', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_attributions', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='marketing.campaignstatus'),
        ),
        migrations.AddField(
            model_name='dripcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dripcampaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dripenrollment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='dripenrollment',
            name='drip_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='marketing.dripcampaign'),
        ),
        migrations.AddField(
            model_name='dripenrollment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AddField(
            model_name='dripenrollment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dripstep',
            name='drip_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='marketing.dripcampaign'),
        ),
        migrations.AddField(
            model_name='dripstep',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dripenrollment',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.dripstep'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='email_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_list', to='marketing.emailcampaign'),
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailevent',
            name='email_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='marketing.emailcampaign'),
        ),
        migrations.AddField(
            model_name='emailevent',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.campaignrecipient'),
        ),
        migrations.AddField(
            model_name='emailevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_email_integrations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_email_integrations_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailprovider',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='provider_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic provider (replaces provider field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_email_integrations_ref', to='marketing.emailprovider'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='email_provider_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic email provider (replaces email_provider field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to='marketing.emailprovider'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic category (replaces category field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_templates', to='marketing.emailcategory'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dripstep',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='abtestvariant',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='abautomatedtest',
            name='variant_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests_as_variant_a', to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='abautomatedtest',
            name='variant_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests_as_variant_b', to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='abtestvariant',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpageblock',
            name='block_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic block type (replaces block_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landing_page_blocks', to='marketing.blocktype'),
        ),
        migrations.AddField(
            model_name='landingpageblock',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='marketing.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpageblock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic category (replaces category field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='marketing.messagecategory'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='message_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic message type (replaces message_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='marketing.messagetype'),
        ),
        migrations.AddField(
            model_name='nurturecampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurturecampaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nurturecampaignenrollment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AddField(
            model_name='nurturecampaignenrollment',
            name='nurture_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.nurturecampaign'),
        ),
        migrations.AddField(
            model_name='nurturecampaignenrollment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nurturestep',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='nurturestep',
            name='nurture_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='marketing.nurturecampaign'),
        ),
        migrations.AddField(
            model_name='nurturestep',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nurturecampaignenrollment',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.nurturestep'),
        ),
        migrations.AddField(
            model_name='segment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nurturecampaign',
            name='target_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurture_campaigns', to='marketing.segment'),
        ),
        migrations.AddField(
            model_name='segmentmember',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AddField(
            model_name='segmentmember',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_members', to='marketing.segment'),
        ),
        migrations.AddField(
            model_name='segmentmember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='blocktype',
            unique_together={('tenant', 'type_name')},
        ),
        migrations.AddIndex(
            model_name='campaignattribution',
            index=models.Index(fields=['tenant', 'campaign'], name='marketing_c_tenant__f8b357_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignattribution',
            index=models.Index(fields=['tenant', 'lead'], name='marketing_c_tenant__617246_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignattribution',
            index=models.Index(fields=['tenant', 'opportunity'], name='marketing_c_tenant__b13044_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignstatus',
            unique_together={('tenant', 'status_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dripenrollment',
            unique_together={('drip_campaign', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='emailcategory',
            unique_together={('tenant', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='emailprovider',
            unique_together={('tenant', 'provider_name')},
        ),
        migrations.AlterUniqueTogether(
            name='messagecategory',
            unique_together={('tenant', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='messagetype',
            unique_together={('tenant', 'type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='nurturestep',
            unique_together={('nurture_campaign', 'step_number')},
        ),
        migrations.AlterUniqueTogether(
            name='nurturecampaignenrollment',
            unique_together={('nurture_campaign', 'lead')},
        ),
        migrations.AlterUniqueTogether(
            name='segmentmember',
            unique_together={('segment', 'contact')},
        ),
    ]
