# Generated by Django 5.2.7 on 2025-12-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignattribution',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_attributions', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='marketing.campaignstatus'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='email_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_list', to='marketing.emailcampaign'),
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_email_integrations_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_email_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailprovider',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='provider_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic provider (replaces provider field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_email_integrations', to='marketing.emailprovider'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='email_provider_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic email provider (replaces email_provider field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to='marketing.emailprovider'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic category (replaces category field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_templates', to='marketing.emailcategory'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='abautomatedtest',
            name='variant_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests_as_variant_a', to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='abautomatedtest',
            name='variant_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests_as_variant_b', to='marketing.emailtemplate'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='landingpageblock',
            name='block_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic block type (replaces block_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landing_page_blocks', to='marketing.blocktype'),
        ),
        migrations.AddField(
            model_name='landingpageblock',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='marketing.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpageblock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic category (replaces category field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='marketing.messagecategory'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='message_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic message type (replaces message_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='marketing.messagetype'),
        ),
        migrations.AlterUniqueTogether(
            name='blocktype',
            unique_together={('tenant', 'type_name')},
        ),
        migrations.AddIndex(
            model_name='campaignattribution',
            index=models.Index(fields=['tenant', 'campaign'], name='marketing_c_tenant__f8b357_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignattribution',
            index=models.Index(fields=['tenant', 'lead'], name='marketing_c_tenant__617246_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignattribution',
            index=models.Index(fields=['tenant', 'opportunity'], name='marketing_c_tenant__b13044_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignstatus',
            unique_together={('tenant', 'status_name')},
        ),
        migrations.AlterUniqueTogether(
            name='emailcategory',
            unique_together={('tenant', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='emailprovider',
            unique_together={('tenant', 'provider_name')},
        ),
        migrations.AlterUniqueTogether(
            name='messagecategory',
            unique_together={('tenant', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='messagetype',
            unique_together={('tenant', 'type_name')},
        ),
    ]
