# Generated by Django 5.2.7 on 2025-11-21 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('in_app', 'In-App Message'), ('push', 'Push Notification'), ('slack', 'Slack Message')], max_length=20)),
                ('content', models.TextField(help_text='Message content with merge tag support')),
                ('category', models.CharField(choices=[('reminder', 'Reminder'), ('notification', 'Notification'), ('alert', 'Alert'), ('update', 'Update'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('merge_tags', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='subject',
            new_name='subject_line',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='plain_text_content',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('newsletter', 'Newsletter'), ('transactional', 'Transactional'), ('follow_up', 'Follow-up'), ('welcome', 'Welcome'), ('reminder', 'Reminder'), ('promotional', 'Promotional'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description of template purpose and usage'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Share with all users in tenant'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='merge_tags',
            field=models.JSONField(blank=True, default=dict, help_text="Available merge tags for this template, e.g., {'first_name': 'John', 'company': 'Acme Corp'}"),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_content',
            field=models.TextField(blank=True, help_text="Plain text version for email clients that don't support HTML"),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of times this template has been used'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['category', 'is_active'], name='marketing_e_categor_7e53fa_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['tenant_id', 'is_shared'], name='marketing_e_tenant__03c3e6_idx'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['message_type', 'category'], name='marketing_m_message_f88843_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['tenant_id', 'is_shared'], name='marketing_m_tenant__e7511f_idx'),
        ),
    ]
