# Generated by Django 5.2.9 on 2026-01-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty bonus points awarded for this campaign'),
        ),
    ]
