# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0003_initial'),
        ('proposals', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='approvaltemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='approvaltemplatestep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.approvalstep'),
        ),
        migrations.AddField(
            model_name='approvaltemplatestep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.approvaltemplate'),
        ),
        migrations.AddField(
            model_name='approvaltemplatestep',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='approvaltemplate',
            name='steps',
            field=models.ManyToManyField(related_name='approval_templates', through='proposals.ApprovalTemplateStep', to='proposals.approvalstep'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='approval_template',
            field=models.ForeignKey(blank=True, help_text='Optional approval template to use for this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='proposals.approvaltemplate'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proposalapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalapproval',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='proposalapproval',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_approvals', to='proposals.approvalstep'),
        ),
        migrations.AddField(
            model_name='proposalapproval',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proposalemail',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='proposalemail',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proposalevent',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='proposalevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proposalpdf',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalpdf',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='proposalpdf',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proposalsignature',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proposalemail',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.proposaltemplate'),
        ),
    ]
