# Generated by Django 5.2.9 on 2026-01-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('purchasing', '0002_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_capital_commitment',
            field=models.BooleanField(default=False, help_text='Is this a commitment for capital expenditure?'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetcategory'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='is_fixed_asset',
            field=models.BooleanField(default=False, help_text='Mark if this item is a Capital Asset'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('partial', 'Partially Received'), ('received', 'Fully Received'), ('partially_billed', 'Partially Billed'), ('billed', 'Fully Billed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
