# Generated by Django 5.2.9 on 2026-01-30 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_journalentry_exchange_rate_and_more'),
        ('purchasing', '0005_alter_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='is_fixed_asset',
            field=models.BooleanField(default=False),
        ),
    ]
