# Generated by Django 6.0.2 on 2026-02-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_supplierinvoice_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued / Sent'), ('posted', 'Posted'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='draft', max_length=20),
        ),
    ]
