# Generated by Django 5.2.9 on 2026-01-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='accumulated_labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='accumulated_material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='accumulated_overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
