# Generated by Django 6.0.2 on 2026-02-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_adjustmenttype_billingprofile_invoice_and_more'),
        ('projects', '0003_alter_projectmilestone_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='billing.invoice'),
        ),
    ]
