# Generated by Django 5.2.9 on 2026-01-25 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_bankreconciliation'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(choices=[('asset_non_current', 'Non-Current Asset'), ('asset_current', 'Current Asset'), ('liability_non_current', 'Non-Current Liability'), ('liability_current', 'Current Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cost_of_sales', 'Cost of Sales'), ('expense', 'Operating Expense'), ('other_income', 'Other Income'), ('other_expense', 'Other Expense')], max_length=50),
        ),
        migrations.CreateModel(
            name='RecurringJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('lines_data', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_journals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Recurring Journal',
                'verbose_name_plural': 'Recurring Journals',
            },
        ),
        migrations.CreateModel(
            name='AccountingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('invoice_validated', 'Customer Invoice Validated'), ('payment_received', 'Customer Payment Received'), ('pos_sale', 'POS Sale Completed'), ('grn_received', 'Goods Received (GRN)'), ('bill_approved', 'Vendor Bill Approved'), ('payment_sent', 'Vendor Payment Sent'), ('inventory_loss', 'Inventory Loss/Adjustment'), ('inventory_gain', 'Inventory Gain/Adjustment'), ('asset_depreciation', 'Asset Depreciation')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations_credit', to='accounting.chartofaccount')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations_debit', to='accounting.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Accounting Integration Rule',
                'verbose_name_plural': 'Accounting Integration Rules',
                'unique_together': {('tenant', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.chartofaccount')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.fiscalyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['fiscal_year', 'account'],
                'unique_together': {('tenant', 'fiscal_year', 'account')},
            },
        ),
    ]
