# Generated by Django 5.2.9 on 2026-01-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_chartofaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingintegration',
            name='event_type',
            field=models.CharField(choices=[('invoice_validated', 'Customer Invoice Validated'), ('payment_received', 'Customer Payment Received'), ('pos_sale', 'POS Sale Completed'), ('grn_received', 'Goods Received (GRN)'), ('bill_approved', 'Vendor Bill Approved'), ('payment_sent', 'Vendor Payment Sent'), ('inventory_loss', 'Inventory Loss/Adjustment'), ('inventory_gain', 'Inventory Gain/Adjustment'), ('asset_depreciation', 'Asset Depreciation'), ('loyalty_earned', 'Loyalty Points Earned (Revenue Deferral)'), ('loyalty_redeemed', 'Loyalty Points Redeemed'), ('loyalty_breakage', 'Loyalty Points Expired (Breakage)')], max_length=50),
        ),
    ]
