# Generated by Django 5.2.9 on 2026-01-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_accountingintegration_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingintegration',
            name='event_type',
            field=models.CharField(choices=[('invoice_validated', 'Customer Invoice Validated'), ('payment_received', 'Customer Payment Received'), ('pos_sale', 'POS Sale Completed'), ('grn_received', 'Goods Received (GRN)'), ('bill_approved', 'Vendor Bill Approved'), ('payment_sent', 'Vendor Payment Sent'), ('inventory_loss', 'Inventory Loss/Adjustment'), ('inventory_gain', 'Inventory Gain/Adjustment'), ('asset_depreciation', 'Asset Depreciation'), ('asset_acquisition', 'Asset Capitalization (Purchase)'), ('asset_impairment', 'Asset Impairment Loss'), ('asset_revaluation', 'Asset Fair Value Revaluation'), ('asset_disposal', 'Asset Retirement / Disposal'), ('loyalty_earned', 'Loyalty Points Earned (Revenue Deferral)'), ('loyalty_redeemed', 'Loyalty Points Redeemed'), ('loyalty_breakage', 'Loyalty Points Expired (Breakage)'), ('expense_accrual', 'Expense Report Accrual'), ('expense_payment', 'Expense Reimbursement Payment'), ('payroll_accrual', 'Payroll Accrual (Salary Expense)'), ('payroll_payment', 'Payroll Payment Settlement'), ('leave_accrual', 'Leave Liability Provision'), ('benefit_contribution', 'Employer Benefit Contribution')], max_length=50),
        ),
    ]
