# Generated by Django 5.2.9 on 2026-01-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_taxrate_taxrule'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(limit_choices_to={'is_bank_account': True}, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounting.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for deposits, negative for withdrawals', max_digits=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_line', to='accounting.journalentryline')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
