# Generated by Django 5.2.7 on 2025-11-07 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('webhook_url', models.URLField()),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('event_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Link Clicked'), ('proposal_viewed', 'Proposal Viewed'), ('proposal_downloaded', 'Proposal Downloaded'), ('proposal_esg_viewed', 'ESG Section Viewed'), ('case_created', 'Case Created'), ('case_resolved', 'Case Resolved'), ('opportunity_created', 'Opportunity Created'), ('opportunity_stage_changed', 'Opportunity Stage Changed'), ('nps_submitted', 'NPS Submitted'), ('esg_content_viewed', 'ESG Content Viewed'), ('web_visit', 'Website Visit'), ('social_mention', 'Social Media Mention'), ('meeting_scheduled', 'Meeting Scheduled'), ('call_logged', 'Call Logged')], max_length=50)),
                ('description', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('is_important', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='accounts.account')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to='opportunities.opportunity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('last_engaged_at', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_status', to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NextBestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('schedule_call', 'Schedule Call'), ('send_proposal', 'Send Proposal'), ('share_esg_brief', 'Share ESG Brief'), ('check_in', 'Check In'), ('create_task', 'Create Task')], max_length=50)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_actions', to='accounts.account')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.opportunity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
