# Generated by Django 5.2.7 on 2025-12-11 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_organizationmember'),
        ('cases', '0002_initial'),
        ('nps', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementWebhook',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('engagement_webhook_name', models.CharField(max_length=255)),
                ('webhook_url', models.URLField()),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('event_types', models.JSONField(default=list)),
                ('engagement_webhook_is_active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('event_type', models.CharField(choices=[('task_lead_contact_completed', 'Lead Contact Completed'), ('task_lead_review_completed', 'Task Lead Review Completed'), ('task_lead_qualify_completed', 'Lead Qualification Completed'), ('task_opportunity_demo_completed', 'Opportunity Demo Completed'), ('task_case_escalation_completed', 'Case Escalation Completed'), ('task_user_followup_completed', 'User Follow-up Completed'), ('task_proposal_followup_completed', 'Proposal Follow-up Completed'), ('lead_created', 'Lead Created'), ('lead_contacted', 'Lead Contacted'), ('user_followup_completed', 'User Follow-up Completed'), ('demo_completed', 'Demo Completed'), ('case_escalation_handled', 'Case Escalation Handled'), ('detractor_followup_completed', 'Detractor Follow-up Completed'), ('proposal_viewed', 'Proposal Viewed'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('landing_page_visited', 'Landing Page Visited'), ('form_submitted', 'Form Submitted'), ('content_downloaded', 'Content Downloaded'), ('renewal_reminder', 'Renewal Reminder'), ('nps_submitted', 'NPS Submitted')], max_length=50)),
                ('engagement_event_description', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('is_important', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nps_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nps.npsresponse')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to='opportunities.opportunity')),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.CreateModel(
            name='EngagementStatus',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('last_engaged_at', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_status', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.CreateModel(
            name='NextBestAction',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('schedule_call', 'Schedule Call'), ('send_proposal', 'Send Proposal'), ('share_esg_brief', 'Share ESG Brief'), ('check_in', 'Check In'), ('create_task', 'Create Task')], max_length=50)),
                ('next_best_action_description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], max_length=20)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_actions', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact')),
                ('engagement_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engagement.engagementevent')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-due_date', 'priority'],
            },
            bases=('tenants.tenant',),
        ),
    ]
