# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNBARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(choices=[('low_engagement_score', 'Low Engagement Score'), ('no_engagement_7_days', 'No Engagement for 7 Days'), ('proposal_viewed', 'Proposal Viewed'), ('high_engagement_score', 'High Engagement Score'), ('nps_submitted_promoter', 'NPS Promoter (9-10)'), ('nps_submitted_detractor', 'NPS Detractor (0-6)'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked')], max_length=50)),
                ('auto_nba_is_active', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('schedule_call', 'Schedule Call'), ('send_proposal', 'Send Proposal'), ('share_esg_brief', 'Share ESG Brief'), ('check_in', 'Check In'), ('create_task', 'Create Task')], max_length=50)),
                ('description_template', models.TextField()),
                ('due_in_days', models.IntegerField(default=7)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('assigned_to_creator', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('task_lead_contact_completed', 'Lead Contact Completed'), ('task_lead_review_completed', 'Task Lead Review Completed'), ('task_lead_qualify_completed', 'Lead Qualification Completed'), ('task_opportunity_demo_completed', 'Opportunity Demo Completed'), ('task_case_escalation_completed', 'Case Escalation Completed'), ('task_user_followup_completed', 'User Follow-up Completed'), ('task_proposal_followup_completed', 'Proposal Follow-up Completed'), ('lead_created', 'Lead Created'), ('lead_contacted', 'Lead Contacted'), ('user_followup_completed', 'User Follow-up Completed'), ('demo_completed', 'Demo Completed'), ('case_escalation_handled', 'Case Escalation Handled'), ('detractor_followup_completed', 'Detractor Follow-up Completed'), ('proposal_viewed', 'Proposal Viewed'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('landing_page_visited', 'Landing Page Visited'), ('form_submitted', 'Form Submitted'), ('content_downloaded', 'Content Downloaded'), ('renewal_reminder', 'Renewal Reminder'), ('nps_submitted', 'NPS Submitted'), ('social_interaction', 'Social Media Interaction'), ('website_visit', 'Website Visit'), ('document_view', 'Document Viewed'), ('webinar_attended', 'Webinar Attended'), ('support_ticket', 'Support Ticket Created'), ('video_viewed', 'Video Viewed'), ('video_watched_full', 'Video Watched Completely'), ('forum_post_created', 'Forum Post Created'), ('forum_reply_created', 'Forum Reply Created'), ('product_usage_session', 'Product Usage Session'), ('feature_used', 'Specific Feature Used'), ('login_event', 'User Login'), ('page_view_duration', 'Page View Duration'), ('whatsapp_sent', 'WhatsApp Message Sent'), ('linkedin_inmail_tracked', 'LinkedIn InMail Tracked'), ('payment_received', 'Payment Received'), ('course_completed', 'Learning Course Completed'), ('win_probability_update', 'Win Probability Update'), ('task_assigned', 'Task Assigned'), ('opportunity_created', 'Opportunity Created'), ('opportunity_stage_changed', 'Opportunity Stage Changed'), ('opportunity_won', 'Opportunity Won'), ('opportunity_lost', 'Opportunity Lost'), ('lead_qualified', 'Lead Qualified'), ('lead_unqualified', 'Lead Unqualified'), ('lead_converted', 'Lead Converted'), ('case_resolved', 'Case Resolved'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('proposal_sent', 'Proposal Sent'), ('whatsapp_delivered', 'WhatsApp Delivered'), ('whatsapp_read', 'WhatsApp Read'), ('linkedin_message_read', 'LinkedIn Message Read'), ('account_created', 'Account Created'), ('account_owner_changed', 'Account Owner Changed')], max_length=50)),
                ('description', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('is_important', models.BooleanField(default=False)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer_url', models.URLField(blank=True, null=True)),
                ('referring_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementEventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('government', 'Government'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], max_length=50, null=True)),
                ('playbook_type', models.CharField(choices=[('standard', 'Standard'), ('industry_best_practice', 'Industry Best Practice'), ('template', 'Template')], default='standard', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('average_completion_rate', models.FloatField(default=0.0)),
                ('average_effectiveness_score', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EngagementScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('decay_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('decay_period_days', models.IntegerField(default=7)),
                ('inactivity_threshold_days', models.IntegerField(default=14)),
                ('rolling_window_days', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_engaged_at', models.DateTimeField(blank=True, null=True)),
                ('last_decay_calculation', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement_webhook_name', models.CharField(max_length=255)),
                ('webhook_url', models.URLField()),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('event_types', models.JSONField(default=list)),
                ('engagement_webhook_is_active', models.BooleanField(default=True)),
                ('payload_template', models.TextField(blank=True)),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('max_retry_attempts', models.IntegerField(default=3)),
                ('initial_retry_delay', models.IntegerField(default=5)),
                ('retry_backoff_factor', models.FloatField(default=2.0)),
                ('retry_on_status_codes', models.JSONField(blank=True, default=list)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_name', models.CharField(max_length=255)),
                ('workflow_description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('email_sequence', 'Email Sequence'), ('task_creation', 'Task Creation'), ('escalation', 'Escalation Workflow'), ('notification', 'Notification')], max_length=50)),
                ('trigger_condition', models.CharField(choices=[('low_engagement', 'Low Engagement Score'), ('high_engagement', 'High Engagement Score'), ('inactivity', 'Account Inactivity'), ('milestone', 'Engagement Milestone'), ('nps_promoter', 'NPS Promoter'), ('nps_detractor', 'NPS Detractor'), ('high_video_engagement', 'High Video Engagement'), ('forum_activity', 'Forum Activity'), ('product_power_user', 'Product Power User')], max_length=50)),
                ('engagement_work_flow_is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('email_template_ids', models.JSONField(blank=True, default=list)),
                ('delay_between_emails', models.IntegerField(default=1)),
                ('task_title_template', models.CharField(blank=True, max_length=255)),
                ('task_description_template', models.TextField(blank=True)),
                ('task_due_date_offset', models.IntegerField(default=7)),
                ('task_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('escalation_recipients', models.JSONField(blank=True, default=list)),
                ('escalation_delay', models.IntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementWorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NextBestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('schedule_call', 'Schedule Call'), ('send_proposal', 'Send Proposal'), ('share_esg_brief', 'Share ESG Brief'), ('check_in', 'Check In'), ('create_task', 'Create Task')], max_length=50)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NextBestActionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('effectiveness_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaybookStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_offset', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('schedule_call', 'Schedule Call'), ('send_proposal', 'Send Proposal'), ('share_esg_brief', 'Share ESG Brief'), ('check_in', 'Check In'), ('create_task', 'Create Task')], max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('times_completed', models.PositiveIntegerField(default=0)),
                ('times_skipped', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['day_offset'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=50)),
                ('event_type', models.CharField(choices=[('task_lead_contact_completed', 'Lead Contact Completed'), ('task_lead_review_completed', 'Task Lead Review Completed'), ('task_lead_qualify_completed', 'Lead Qualification Completed'), ('task_opportunity_demo_completed', 'Opportunity Demo Completed'), ('task_case_escalation_completed', 'Case Escalation Completed'), ('task_user_followup_completed', 'User Follow-up Completed'), ('task_proposal_followup_completed', 'Proposal Follow-up Completed'), ('lead_created', 'Lead Created'), ('lead_contacted', 'Lead Contacted'), ('user_followup_completed', 'User Follow-up Completed'), ('demo_completed', 'Demo Completed'), ('case_escalation_handled', 'Case Escalation Handled'), ('detractor_followup_completed', 'Detractor Follow-up Completed'), ('proposal_viewed', 'Proposal Viewed'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('landing_page_visited', 'Landing Page Visited'), ('form_submitted', 'Form Submitted'), ('content_downloaded', 'Content Downloaded'), ('renewal_reminder', 'Renewal Reminder'), ('nps_submitted', 'NPS Submitted'), ('social_interaction', 'Social Media Interaction'), ('website_visit', 'Website Visit'), ('document_view', 'Document Viewed'), ('webinar_attended', 'Webinar Attended'), ('support_ticket', 'Support Ticket Created'), ('video_viewed', 'Video Viewed'), ('video_watched_full', 'Video Watched Completely'), ('forum_post_created', 'Forum Post Created'), ('forum_reply_created', 'Forum Reply Created'), ('product_usage_session', 'Product Usage Session'), ('feature_used', 'Specific Feature Used'), ('login_event', 'User Login'), ('page_view_duration', 'Page View Duration'), ('whatsapp_sent', 'WhatsApp Message Sent'), ('linkedin_inmail_tracked', 'LinkedIn InMail Tracked'), ('payment_received', 'Payment Received'), ('course_completed', 'Learning Course Completed'), ('win_probability_update', 'Win Probability Update'), ('task_assigned', 'Task Assigned'), ('opportunity_created', 'Opportunity Created'), ('opportunity_stage_changed', 'Opportunity Stage Changed'), ('opportunity_won', 'Opportunity Won'), ('opportunity_lost', 'Opportunity Lost'), ('lead_qualified', 'Lead Qualified'), ('lead_unqualified', 'Lead Unqualified'), ('lead_converted', 'Lead Converted'), ('case_resolved', 'Case Resolved'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('proposal_sent', 'Proposal Sent'), ('whatsapp_delivered', 'WhatsApp Delivered'), ('whatsapp_read', 'WhatsApp Read'), ('linkedin_message_read', 'LinkedIn Message Read'), ('account_created', 'Account Created'), ('account_owner_changed', 'Account Owner Changed')], max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('rule_is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Scoring Rules',
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('success', models.BooleanField(default=False)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
