# Generated by Django 5.2.7 on 2025-11-13 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('cases', '0001_initial'),
        ('engagement', '0001_initial'),
        ('nps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nextbestaction',
            options={'ordering': ['-due_date', 'priority']},
        ),
        migrations.RenameField(
            model_name='engagementevent',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='nps_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nps.npsresponse'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='assigned_to',
            field=models.ForeignKey(default=-1984, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='engagement_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engagement.engagementevent'),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_contacted', 'Lead Contacted'), ('account_followup_completed', 'Account Follow-up Completed'), ('demo_completed', 'Demo Completed'), ('case_escalation_handled', 'Case Escalation Handled'), ('detractor_followup_completed', 'Detractor Follow-up Completed'), ('proposal_viewed', 'Proposal Viewed'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('landing_page_visited', 'Landing Page Visited'), ('form_submitted', 'Form Submitted'), ('content_downloaded', 'Content Downloaded'), ('renewal_reminder', 'Renewal Reminder'), ('nps_submitted', 'NPS Submitted')], max_length=50),
        ),
    ]
