# Generated by Django 5.2.7 on 2025-12-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('engagement', '0001_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementevent',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='engagementstatus',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='engagement_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engagement.engagementevent'),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.opportunity'),
        ),
    ]
