# Generated by Django 5.2.9 on 2026-01-09 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('cases', '0004_initial'),
        ('engagement', '0001_initial'),
        ('leads', '0001_initial'),
        ('nps', '0001_initial'),
        ('opportunities', '0002_initial'),
        ('proposals', '0001_initial'),
        ('tasks', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autonbarule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='account_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_engagement_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_engagement_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='nps_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nps.npsresponse'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='engagementevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='engagementeventcomment',
            name='engagement_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='engagement.engagementevent'),
        ),
        migrations.AddField(
            model_name='engagementeventcomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='engagementeventcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementplaybook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementplaybook',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='engagementscoresnapshot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementstatus',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementstatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='engagementwebhook',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='engagementworkflow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='engagementworkflowexecution',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementworkflowexecution',
            name='engagement_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engagement.engagementevent'),
        ),
        migrations.AddField(
            model_name='engagementworkflowexecution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='engagementworkflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='engagement.engagementworkflow'),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_nb_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_on_nb_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='nextbestaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nextbestactioncomment',
            name='next_best_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_comments', to='engagement.nextbestaction'),
        ),
        migrations.AddField(
            model_name='nextbestactioncomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nextbestactioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbookexecution',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbookexecution',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.engagementplaybook'),
        ),
        migrations.AddField(
            model_name='playbookexecution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='playbookstep',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='engagement.engagementplaybook'),
        ),
        migrations.AddField(
            model_name='playbookstepexecution',
            name='playbook_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='engagement.playbookexecution'),
        ),
        migrations.AddField(
            model_name='playbookstepexecution',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.playbookstep'),
        ),
        migrations.AddField(
            model_name='playbookstepexecution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='engagement.engagementwebhook'),
        ),
    ]
