# Generated by Django 5.2.7 on 2025-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_alter_nextbestaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('task_lead_contact_completed', 'Lead Contact Completed'), ('task_lead_qualify_completed', 'Lead Qualification Completed'), ('task_opportunity_demo_completed', 'Opportunity Demo Completed'), ('task_case_escalation_completed', 'Case Escalation Completed'), ('task_account_followup_completed', 'Account Follow-up Completed'), ('task_proposal_followup_completed', 'Proposal Follow-up Completed'), ('lead_created', 'Lead Created'), ('lead_contacted', 'Lead Contacted'), ('account_followup_completed', 'Account Follow-up Completed'), ('demo_completed', 'Demo Completed'), ('case_escalation_handled', 'Case Escalation Handled'), ('detractor_followup_completed', 'Detractor Follow-up Completed'), ('proposal_viewed', 'Proposal Viewed'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('landing_page_visited', 'Landing Page Visited'), ('form_submitted', 'Form Submitted'), ('content_downloaded', 'Content Downloaded'), ('renewal_reminder', 'Renewal Reminder'), ('nps_submitted', 'NPS Submitted')], max_length=50),
        ),
    ]
