# Generated by Django 5.2.9 on 2026-01-15 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementscoringconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementscoringconfig',
            name='email_open_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='engagementscoringconfig',
            name='link_click_score',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='engagementscoringconfig',
            name='meeting_score',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='engagementscoringconfig',
            name='reply_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.CreateModel(
            name='EngagementExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('experiment_type', models.CharField(choices=[('email_subject', 'Email Subject Line'), ('email_content', 'Email Content'), ('send_time', 'Send Time'), ('channel', 'Communication Channel'), ('cta', 'Call to Action'), ('workflow_path', 'Workflow Path')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('primary_metric', models.CharField(choices=[('open_rate', 'Open Rate'), ('click_rate', 'Click Rate'), ('reply_rate', 'Reply Rate'), ('conversion_rate', 'Conversion Rate'), ('engagement_score', 'Engagement Score Increase')], max_length=50)),
                ('target_sample_size', models.PositiveIntegerField(help_text='Target number of participants per variant')),
                ('current_sample_size', models.PositiveIntegerField(default=0)),
                ('confidence_level', models.FloatField(default=0.0, help_text='Statistical confidence level of the result')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g., 'Variant A', 'Control Group'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_control', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Specific configuration for this variant (e.g., subject line text)')),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('conversions_count', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='engagement.engagementexperiment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='engagementexperiment',
            name='winner_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_experiments', to='engagement.experimentvariant'),
        ),
    ]
