# Generated by Django 5.2.7 on 2025-12-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementevent',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private notes for internal team'),
        ),
        migrations.AddField(
            model_name='engagementstatus',
            name='last_decay_calculation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('task_lead_contact_completed', 'Lead Contact Completed'), ('task_lead_review_completed', 'Task Lead Review Completed'), ('task_lead_qualify_completed', 'Lead Qualification Completed'), ('task_opportunity_demo_completed', 'Opportunity Demo Completed'), ('task_case_escalation_completed', 'Case Escalation Completed'), ('task_user_followup_completed', 'User Follow-up Completed'), ('task_proposal_followup_completed', 'Proposal Follow-up Completed'), ('lead_created', 'Lead Created'), ('lead_contacted', 'Lead Contacted'), ('user_followup_completed', 'User Follow-up Completed'), ('demo_completed', 'Demo Completed'), ('case_escalation_handled', 'Case Escalation Handled'), ('detractor_followup_completed', 'Detractor Follow-up Completed'), ('proposal_viewed', 'Proposal Viewed'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('landing_page_visited', 'Landing Page Visited'), ('form_submitted', 'Form Submitted'), ('content_downloaded', 'Content Downloaded'), ('renewal_reminder', 'Renewal Reminder'), ('nps_submitted', 'NPS Submitted'), ('social_interaction', 'Social Media Interaction'), ('website_visit', 'Website Visit'), ('document_view', 'Document Viewed'), ('webinar_attended', 'Webinar Attended'), ('support_ticket', 'Support Ticket Created')], max_length=50),
        ),
    ]
