# Generated by Django 5.2.9 on 2026-01-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_price_list'),
        ('engagement', '0003_engagementscoringconfig_created_by_and_more'),
        ('leads', '0004_alter_leadstatus_color'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('interaction_type', models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply'), ('direct_message', 'Direct Message'), ('like', 'Like/Reaction'), ('share', 'Share/Retweet')], max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('author_handle', models.CharField(max_length=100)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_interactions', to='accounts.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_interactions', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('platform', 'external_id')},
            },
        ),
    ]
