"""
Django settings for salescompass project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, you MUST set the SECRET_KEY environment variable
if os.getenv('REPLIT_DEPLOYMENT') == '1':
    SECRET_KEY = os.getenv('SECRET_KEY')
    if not SECRET_KEY:
        raise ValueError("SECRET_KEY environment variable must be set in production")
    DEBUG = False
else:
    # Development only - use env var or insecure default
    SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-f4*r+okok01o^i4+vd1**l+rv1snh10zz*mrbk73kb2_exq=qc')
    DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Configure ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS
if os.getenv('REPLIT_DEPLOYMENT') == '1':
    # Production - use Replit domain
    allowed_hosts = []
    csrf_trusted_origins = []
    
    if os.getenv('REPL_SLUG') and os.getenv('REPL_OWNER'):
        host = f"{os.getenv('REPL_SLUG')}.{os.getenv('REPL_OWNER')}.repl.co"
        allowed_hosts.append(host)
        csrf_trusted_origins.append(f"https://{host}")
    
    if os.getenv('REPLIT_DEV_DOMAIN'):
        host = os.getenv('REPLIT_DEV_DOMAIN')
        allowed_hosts.append(host)
        csrf_trusted_origins.append(f"https://{host}")
    
    # Use localhost as fallback
    if not allowed_hosts:
        allowed_hosts = ['localhost', '127.0.0.1']
        csrf_trusted_origins = ['http://localhost', 'https://localhost', 'http://127.0.0.1', 'https://127.0.0.1']
    
    ALLOWED_HOSTS = allowed_hosts
    CSRF_TRUSTED_ORIGINS = csrf_trusted_origins
    
    # Security settings for production
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development mode
    ALLOWED_HOSTS = ['*']
    CSRF_TRUSTED_ORIGINS = []


# Application definition

INSTALLED_APPS = [
    # Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # --- Platform Foundation ---
    'core',                 # Base users and utils
    'tenants',              # Multi-tenancy isolation
    'dashboard',            # Main UI shell
    'access_control',       # RBAC/ABAC Policies
    'infrastructure',       # Metrics & health
    'audit_logs',           # Compliance logging
    'feature_flags',        # Feature toggles
    'global_alerts',        # System notifications
    'settings_app',         # Tenant config UI
    
    # --- CRM Core 🤝 ---
    'accounts',
    'leads',
    'opportunities',
    'sales',
    
    # --- Finance & Commerce 💰 ---
    'billing',
    'commissions',
    'proposals',
    'products',
    
    # --- Communication & Engagement 💬 ---
    'communication',
    'engagement',
    'marketing',
    'nps',
    'wazo',                # Telephony
    
    # --- Support & Success 🆘 ---
    'cases',
    'learn',               # LMS
    
    # --- Tools & Reporting 🛠️ ---
    'automation',          # Workflow engine
    'reports',             # Analytics engine
    'tasks',               # User tasks
    'developer',           # Dev tools & API introspection

    # --- Third Party ---
    'rest_framework',
    'rest_framework.authtoken',
    'channels',
    'django_celery_beat',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_filters',
    'crispy_forms',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Configure Spectacular settings

SPECTACULAR_SETTINGS = {
    'TITLE': 'SalesCompass API',
    'DESCRIPTION': 'API for SalesCompass CRM',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON': True,
    'SWAGGER_UI_CUSTOM_OPTIONS': {
        'deepLinking': True,
        'displayOperationId': True,
        'defaultModelsExpandDepth': -1,  # Hide default models
    },
    'EXTENSIONS': [
        'drf_spectacular.extensions.OAuth2Extension',
    ],
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ThreadLocalUserMiddleware',
    'core.middleware.DataVisibilityMiddleware',
    'core.middleware.ForbiddenAccessMiddleware',
    'tenants.middleware.CrossTenantAccessLoggingMiddleware',  # Added cross-tenant access logging
    'core.audit_middleware.AuditLoggingMiddleware',
    'core.feature_flag_middleware.FeatureFlagMiddleware',
    'infrastructure.metrics.MetricsMiddleware',
    'tenants.middleware.UsageTrackingMiddleware',  # Add usage tracking middleware
    'tenants.middleware.OverageCheckMiddleware',  # Add overage check middleware
]





ROOT_URLCONF = 'salescompass.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.user_dashboards',
                'core.feature_flag_middleware.feature_flag_context_processor',
                'tenants.context_processor.white_label_context',
                'access_control.context_processors.access_control',
            ],
        },
    },
]


WSGI_APPLICATION = 'salescompass.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Use DATABASE_URL if available (PostgreSQL), otherwise fallback to SQLite for development
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication User settings
AUTH_USER_MODEL = 'core.User'
LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:app_selection'
LOGOUT_REDIRECT_URL = 'core:home'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#################

# added changes 
# Celery configuration - Redis is now deployed
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TASK_ALWAYS_EAGER = False  # Tasks now run asynchronously
CELERY_TASK_EAGER_PROPAGATES = False
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'  # Or your timezone
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Celery Beat periodic tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-due-reports': {
        'task': 'reports.tasks.check_due_reports',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
    'process-drip-enrollments': {
        'task': 'marketing.tasks.process_drip_enrollments',
        'schedule': crontab(minute='*/10'),  # Every 10 minutes
    },
    'calculate-tenant-usage': {
        'task': 'infrastructure.tasks.calculate_usage',
        'schedule': crontab(hour='*/6'),  # Every 6 hours
    },
}

# # ASGI application (replace your current WSGI_APPLICATION)
# ASGI_APPLICATION = 'salescompass.routing.application'
# # Add this at the bottom of the file
# Channels
ASGI_APPLICATION = 'core.asgi.application'
# Channel layer configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
# For production, you might want to use Redis:
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }
# Channels Configuration - Use Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL],
            "capacity": 1500,  # Max messages in channel
            "expiry": 10,      # Message expiry in seconds
        },
    },
}


# Elasticsearch Configuration
ELASTICSEARCH_HOST = os.getenv('ELASTICSEARCH_HOST', 'http://localhost:9200')
ELASTICSEARCH_INDEX_PREFIX = os.getenv('ELASTICSEARCH_INDEX_PREFIX', 'salescompass')

# Optional: Elasticsearch authentication (if using security)
ELASTICSEARCH_USERNAME = os.getenv('ELASTICSEARCH_USERNAME', None)
ELASTICSEARCH_PASSWORD = os.getenv('ELASTICSEARCH_PASSWORD', None)

# Connection pool settings
ELASTICSEARCH_MAX_RETRIES = 3
ELASTICSEARCH_TIMEOUT = 30

# For production with HTTPS
ELASTICSEARCH_USE_SSL = os.getenv('ELASTICSEARCH_USE_SSL', 'False').lower() == 'true'
ELASTICSEARCH_VERIFY_CERTS = os.getenv('ELASTICSEARCH_VERIFY_CERTS', 'True').lower() == 'true'


# =============================================================================
# INTEGRATION CONFIGURATIONS
# =============================================================================

# SendGrid Email Configuration
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', None)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@salescompass.io')

# Email backend (use console for development, sendgrid for production)
if SENDGRID_API_KEY:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Stripe Payment Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', None)
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', None)
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', None)

# Wazo Platform Configuration (for telephony)
WAZO_API_URL = os.getenv('WAZO_API_URL', None)
WAZO_API_KEY = os.getenv('WAZO_API_KEY', None)
WAZO_TENANT_UUID = os.getenv('WAZO_TENANT_UUID', None)

# Wazo Service URLs
WAZO_AUTH_URL = os.getenv('WAZO_AUTH_URL', None)
WAZO_CALLD_URL = os.getenv('WAZO_CALLD_URL', None)
WAZO_CHATD_URL = os.getenv('WAZO_CHATD_URL', None)
WAZO_CONFD_URL = os.getenv('WAZO_CONFD_URL', None)
WAZO_AGENTD_URL = os.getenv('WAZO_AGENTD_URL', None)
WAZO_CALL_LOG_URL = os.getenv('WAZO_CALL_LOG_URL', None)
WAZO_WEBHOOKD_URL = os.getenv('WAZO_WEBHOOKD_URL', None)
WAZO_WEBHOOK_SECRET = os.getenv('WAZO_WEBHOOK_SECRET', None)
WAZO_DEFAULT_SMS_NUMBER = os.getenv('WAZO_DEFAULT_SMS_NUMBER', None)

# =============================================================================
# EVENT BUS CONFIGURATION
# =============================================================================

# Enable async event processing when Redis is available
EVENT_BUS_ASYNC = not CELERY_TASK_ALWAYS_EAGER

# Enable automation async execution when broker is available
AUTOMATION_ASYNC = not CELERY_TASK_ALWAYS_EAGER

# =============================================================================
# FEATURE FLAG CONFIGURATION
# =============================================================================

# URL patterns that require specific feature flags
FEATURE_FLAG_URL_RULES = {
    '/beta/': 'beta_features',
    '/api/v2/': 'api_v2',
    '/new-reports/': 'new_reports',
}

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'automation': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# ML Service Configuration (Decoupled API)
ML_SERVICE_URL = os.getenv('ML_SERVICE_URL', 'http://localhost:8001/api/v1/ml/')
