"""
Django settings for salescompass project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f4*r+okok01o^i4+vd1**l+rv1snh10zz*mrbk73kb2_exq=qc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Core apps
    'core',
    'tenants',
    'accounts',
    'dashboard',
    'billing',
    
    # Feature apps
    'sales',
    'leads',
    'products',
    'opportunities',
    'proposals',
    'cases',
    'communication',
    'engagement',
    'nps',
    'marketing',
    'reports',
    'automation',
    'settings_app',
    'learn',
    'tasks',
    'commissions',
    'developer',
    
    # Control Plane apps
    'infrastructure',
    'audit_logs',
    'feature_flags',
    'global_alerts',

    # Third party
    'rest_framework',
    'rest_framework.authtoken',
    'channels',
    'django_celery_beat',
    # 'drf_spectacular',  # Commented out - not installed
]

REST_FRAMEWORK = {
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Commented out - not installed
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'SalesCompass API',
    'VERSION': '1.0.0',
    'DESCRIPTION': 'Multi-tenant B2B CRM API',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ThreadLocalUserMiddleware',
    'core.middleware.DataVisibilityMiddleware',
]

ROOT_URLCONF = 'salescompass.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.user_dashboards',  # Add user dashboards to all templates
            ],
        },
    },
]

WSGI_APPLICATION = 'salescompass.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication User settings
AUTH_USER_MODEL = 'core.User'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#################

# added changes 
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# Celery Beat periodic tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-due-reports': {
        'task': 'reports.tasks.check_due_reports',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
    'process-drip-enrollments': {
        'task': 'marketing.tasks.process_drip_enrollments',
        'schedule': crontab(minute='*/10'),  # Every 10 minutes
    },
}

# ASGI application (replace your current WSGI_APPLICATION)
ASGI_APPLICATION = 'salescompass.routing.application'

# Channels configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],  # Your Redis host and port
        },
    },
}


# Elasticsearch Configuration
ELASTICSEARCH_HOST = os.getenv('ELASTICSEARCH_HOST', 'http://localhost:9200')
ELASTICSEARCH_INDEX_PREFIX = os.getenv('ELASTICSEARCH_INDEX_PREFIX', 'salescompass')

# Optional: Elasticsearch authentication (if using security)
ELASTICSEARCH_USERNAME = os.getenv('ELASTICSEARCH_USERNAME', None)
ELASTICSEARCH_PASSWORD = os.getenv('ELASTICSEARCH_PASSWORD', None)

# Connection pool settings
ELASTICSEARCH_MAX_RETRIES = 3
ELASTICSEARCH_TIMEOUT = 30

# For production with HTTPS
ELASTICSEARCH_USE_SSL = os.getenv('ELASTICSEARCH_USE_SSL', 'False').lower() == 'true'
ELASTICSEARCH_VERIFY_CERTS = os.getenv('ELASTICSEARCH_VERIFY_CERTS', 'True').lower() == 'true'


