# Generated by Django 5.2.9 on 2026-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the access control', max_length=255)),
                ('key', models.CharField(help_text='Unique identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('access_type', models.CharField(choices=[('permission', 'Permission - User/Role Specific'), ('feature_flag', 'Feature Toggle - On/Off Control'), ('entitlement', 'Feature Entitlement - Plan Based')], max_length=20)),
                ('scope_type', models.CharField(choices=[('user', 'User Specific'), ('role', 'Role Based'), ('tenant', 'Tenant Wide'), ('system', 'System Wide')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('rollout_percentage', models.IntegerField(default=100, help_text='For feature toggles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_data', models.JSONField(default=dict, help_text='Additional configuration options')),
            ],
            options={
                'verbose_name': 'Access Control',
                'verbose_name_plural': 'Access Controls',
            },
        ),
    ]
