# Generated by Django 5.2.9 on 2026-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='key',
            field=models.CharField(help_text='Unique identifier', max_length=255),
        ),
    ]
