# Generated by Django 5.2.9 on 2026-01-12 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_alter_accesscontrol_key'),
        ('accounts', '0004_account_annual_revenue_account_billing_address_line1_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accesscontrol',
            unique_together={('key', 'access_type', 'scope_type', 'role'), ('key', 'access_type', 'scope_type', 'tenant'), ('key', 'access_type', 'scope_type', 'user')},
        ),
    ]
