# Generated by Django 5.2.9 on 2026-01-12 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_role_alter_accesscontrol_role'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accesscontrol',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accesscontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'user')), fields=('key', 'access_type', 'scope_type', 'user'), name='unique_user_access'),
        ),
        migrations.AddConstraint(
            model_name='accesscontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'role')), fields=('key', 'access_type', 'scope_type', 'role', 'tenant'), name='unique_role_access'),
        ),
        migrations.AddConstraint(
            model_name='accesscontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'tenant')), fields=('key', 'access_type', 'scope_type', 'tenant'), name='unique_tenant_access'),
        ),
        migrations.AddConstraint(
            model_name='accesscontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'system')), fields=('key', 'access_type', 'scope_type'), name='unique_system_access'),
        ),
    ]
