# Generated by Django 5.2.9 on 2026-01-14 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_alter_accesscontrol_unique_together_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAccessControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
            },
        ),
        migrations.CreateModel(
            name='TenantAccessControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config_data', models.JSONField(blank=True, default=dict, help_text='Configuration specific to this tenant assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Access Assignment',
                'verbose_name_plural': 'Tenant Access Assignments',
            },
        ),
        migrations.CreateModel(
            name='UserAccessControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'verbose_name': 'Access Control Definition', 'verbose_name_plural': 'Access Control Definitions'},
        ),
        migrations.RemoveConstraint(
            model_name='accesscontrol',
            name='unique_user_access',
        ),
        migrations.RemoveConstraint(
            model_name='accesscontrol',
            name='unique_role_access',
        ),
        migrations.RemoveConstraint(
            model_name='accesscontrol',
            name='unique_tenant_access',
        ),
        migrations.RemoveConstraint(
            model_name='accesscontrol',
            name='unique_system_access',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='config_data',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='role',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='rollout_percentage',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='scope_type',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='accesscontrol',
            name='user',
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='config_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON Schema for config_data validation'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='default_enabled',
            field=models.BooleanField(default=True, help_text='Default state when assigned'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='key',
            field=models.CharField(help_text='Unique identifier', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='roleaccesscontrol',
            name='access_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='access_control.accesscontrol'),
        ),
        migrations.AddField(
            model_name='roleaccesscontrol',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access_control.role'),
        ),
        migrations.AddField(
            model_name='tenantaccesscontrol',
            name='access_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_assignments', to='access_control.accesscontrol'),
        ),
        migrations.AddField(
            model_name='tenantaccesscontrol',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='useraccesscontrol',
            name='access_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='access_control.accesscontrol'),
        ),
        migrations.AddField(
            model_name='useraccesscontrol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='roleaccesscontrol',
            constraint=models.UniqueConstraint(fields=('access_control', 'role'), name='unique_role_access_assignment'),
        ),
        migrations.AddConstraint(
            model_name='tenantaccesscontrol',
            constraint=models.UniqueConstraint(fields=('access_control', 'tenant'), name='unique_tenant_access_assignment'),
        ),
        migrations.AddConstraint(
            model_name='useraccesscontrol',
            constraint=models.UniqueConstraint(fields=('access_control', 'user'), name='unique_user_access_assignment'),
        ),
    ]
