# Generated by Django 5.2.9 on 2026-01-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_roleaccesscontrol_tenantaccesscontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent role from which permissions are inherited.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='access_control.role'),
        ),
        migrations.AddField(
            model_name='roleaccesscontrol',
            name='config_data',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration specific to this role assignment (e.g. field-level permissions)'),
        ),
        migrations.AddField(
            model_name='useraccesscontrol',
            name='config_data',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration specific to this user assignment'),
        ),
    ]
