# Generated by Django 5.2.7 on 2025-11-25 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('rollout_percentage', models.IntegerField(default=0, help_text='0-100: Percentage of users to enable')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user_id', 'Specific User ID'), ('tenant_id', 'Specific Tenant ID'), ('role', 'User Role'), ('plan', 'Subscription Plan'), ('cohort', 'User Cohort')], max_length=50)),
                ('target_value', models.CharField(help_text="e.g., 'admin', 'premium', '123'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='feature_flags.featureflag')),
            ],
            options={
                'ordering': ['feature_flag', 'target_type'],
                'unique_together': {('feature_flag', 'target_type', 'target_value')},
            },
        ),
    ]
