# Generated by Django 5.2.7 on 2025-12-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Unique identifier for the feature flag', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Display name for the feature flag', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what the feature flag controls')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the feature flag is currently active')),
                ('rollout_percentage', models.FloatField(default=0.0, help_text='Percentage of users to whom the feature is rolled out (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_for_all', models.BooleanField(default=False, help_text='Enable for all users regardless of rollout percentage')),
                ('disabled_for_all', models.BooleanField(default=False, help_text='Disable for all users regardless of other settings')),
                ('scheduled_activation', models.DateTimeField(blank=True, help_text='Automatically activate at this time', null=True)),
                ('scheduled_deactivation', models.DateTimeField(blank=True, help_text='Automatically deactivate at this time', null=True)),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Other feature flags that must be enabled for this one')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for organizing feature flags')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the feature flag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flags_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagExperiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('experiment_name', models.CharField(help_text='Name of the experiment', max_length=255)),
                ('hypothesis', models.TextField(help_text='What you expect to happen with this experiment')),
                ('start_date', models.DateTimeField(help_text='Start date of the experiment')),
                ('end_date', models.DateTimeField(help_text='End date of the experiment')),
                ('status', models.CharField(choices=[('design', 'Design'), ('running', 'Running'), ('analysis', 'Analysis'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='design', max_length=20)),
                ('target_metric', models.CharField(help_text='Primary metric to measure', max_length=255)),
                ('success_criteria', models.JSONField(blank=True, default=dict, help_text='Criteria for determining success')),
                ('variant_a_percentage', models.FloatField(default=50.0, help_text='Percentage of users in variant A (0-100)')),
                ('variant_b_percentage', models.FloatField(default=50.0, help_text='Percentage of users in variant B (0-100)')),
                ('minimum_sample_size', models.IntegerField(help_text='Minimum sample size for statistical significance')),
                ('statistical_power', models.FloatField(default=0.8, help_text='Statistical power of the experiment (0-1)')),
                ('significance_level', models.FloatField(default=0.05, help_text='Significance level (alpha) for the experiment (0-1)')),
                ('results', models.JSONField(blank=True, default=dict, help_text='Results of the experiment')),
                ('winner', models.CharField(blank=True, choices=[('variant_a', 'Variant A'), ('variant_b', 'Variant B'), ('tie', 'Tie'), ('inconclusive', 'Inconclusive')], max_length=20, null=True)),
                ('conclusion', models.TextField(blank=True, help_text='Conclusion of the experiment')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations based on results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the experiment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_experiments_created', to=settings.AUTH_USER_MODEL)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='feature_flags.featureflag')),
            ],
            options={
                'verbose_name': 'Feature Flag Experiment',
                'verbose_name_plural': 'Feature Flag Experiments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagImpactAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('performance', 'Performance Impact'), ('user_experience', 'User Experience Impact'), ('conversion_rate', 'Conversion Rate Impact'), ('error_rate', 'Error Rate Impact'), ('load', 'System Load Impact'), ('revenue', 'Revenue Impact'), ('engagement', 'User Engagement Impact'), ('adoption', 'Feature Adoption Rate')], max_length=100)),
                ('metric_name', models.CharField(help_text='Name of the metric being analyzed', max_length=255)),
                ('baseline_value', models.FloatField(help_text='Baseline value before feature activation')),
                ('current_value', models.FloatField(help_text='Current value after feature activation')),
                ('unit', models.CharField(help_text='Unit of measurement for the metric', max_length=50)),
                ('impact_percentage', models.FloatField(help_text='Percentage change in the metric')),
                ('statistical_significance', models.FloatField(help_text='Statistical significance of the change (0-1)')),
                ('sample_size', models.IntegerField(help_text='Number of samples in the analysis')),
                ('start_date', models.DateTimeField(help_text='Start date of the analysis period')),
                ('end_date', models.DateTimeField(help_text='End date of the analysis period')),
                ('is_positive_impact', models.BooleanField(blank=True, help_text='Whether the impact is positive or negative', null=True)),
                ('confidence_level', models.FloatField(help_text='Confidence level in the analysis results (0-1)')),
                ('impact_summary', models.TextField(help_text='Summary of the impact findings')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations based on the analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_impact_analyses', to=settings.AUTH_USER_MODEL)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_analyses', to='feature_flags.featureflag')),
            ],
            options={
                'verbose_name': 'Feature Flag Impact Analysis',
                'verbose_name_plural': 'Feature Flag Impact Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagRolloutSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rollout_phase', models.CharField(choices=[('alpha', 'Alpha Testing'), ('beta', 'Beta Testing'), ('canary', 'Canary Release'), ('gradual', 'Gradual Rollout'), ('full_release', 'Full Release')], max_length=50)),
                ('phase_name', models.CharField(help_text='Descriptive name for this rollout phase', max_length=255)),
                ('target_percentage', models.FloatField(help_text='Target percentage for this rollout phase (0-100)')),
                ('start_date', models.DateTimeField(help_text='When to start this rollout phase')),
                ('end_date', models.DateTimeField(help_text='When to end this rollout phase')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions for this rollout phase')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this rollout phase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollout_schedules_created', to=settings.AUTH_USER_MODEL)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollout_schedules', to='feature_flags.featureflag')),
                ('target_tenants', models.ManyToManyField(blank=True, related_name='feature_rollout_schedules', to='tenants.tenant')),
                ('target_users', models.ManyToManyField(blank=True, related_name='feature_rollout_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag Rollout Schedule',
                'verbose_name_plural': 'Feature Flag Rollout Schedules',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('requires', 'Requires'), ('conflicts_with', 'Conflicts With'), ('prerequisite', 'Prerequisite'), ('alternative', 'Alternative'), ('supersedes', 'Supersedes')], max_length=50)),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Condition for the dependency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this dependency is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this dependency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_dependencies_created', to=settings.AUTH_USER_MODEL)),
                ('dependent_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='feature_flags.featureflag')),
                ('required_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='feature_flags.featureflag')),
            ],
            options={
                'verbose_name': 'Feature Flag Dependency',
                'verbose_name_plural': 'Feature Flag Dependencies',
                'ordering': ['dependent_feature__name'],
                'unique_together': {('dependent_feature', 'required_feature')},
            },
        ),
        migrations.CreateModel(
            name='FeatureTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('tenant', 'Tenant'), ('group', 'Group'), ('role', 'Role'), ('email_domain', 'Email Domain'), ('percentage', 'Percentage Rollout')], max_length=50)),
                ('target_value', models.CharField(help_text='Value to match (e.g., user ID, tenant ID, group name)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='feature_flags.featureflag')),
            ],
            options={
                'verbose_name': 'Feature Target',
                'verbose_name_plural': 'Feature Targets',
                'unique_together': {('feature_flag', 'target_type', 'target_value')},
            },
        ),
    ]
