# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature_flags', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflagrolloutschedule',
            name='target_tenants',
            field=models.ManyToManyField(blank=True, related_name='feature_rollout_schedules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='featureflagrolloutschedule',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='feature_rollout_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuretarget',
            name='feature_flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='feature_flags.featureflag'),
        ),
        migrations.AlterUniqueTogether(
            name='featureflagdependency',
            unique_together={('dependent_feature', 'required_feature')},
        ),
        migrations.AlterUniqueTogether(
            name='featuretarget',
            unique_together={('feature_flag', 'target_type', 'target_value')},
        ),
    ]
