# Generated by Django 5.2.7 on 2025-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='escalation_rules',
            field=models.JSONField(blank=True, default=dict, help_text="Auto-escalation rules, e.g., {'hours_before_escalation': 4, 'escalate_to_role': 'manager'}"),
        ),
        migrations.AddField(
            model_name='case',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='sla_resolution_hours',
            field=models.IntegerField(default=72, help_text='Expected resolution time in hours'),
        ),
        migrations.AddField(
            model_name='case',
            name='sla_response_hours',
            field=models.IntegerField(default=24, help_text='Expected response time in hours'),
        ),
    ]
