# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrule',
            name='rule_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic rule type (replaces rule_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_assignment_rules', to='settings_app.assignmentruletype'),
        ),
    ]
