# Generated by Django 5.2.9 on 2026-01-09 17:38

from django.db import migrations, models


import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
