# Generated by Django 5.2.9 on 2026-01-02 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_ccpa_consent_account_country_and_more'),
        ('cases', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.account'),
        ),
    ]
