# Generated by Django 5.2.9 on 2026-01-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_created_at_case_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeBaseArticle',
        ),
    ]
