# Generated by Django 5.2.9 on 2026-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for bonus, negative for deduction.', max_digits=12)),
                ('adjusted_description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('bonus', 'Bonus'), ('deduction', 'Deduction'), ('draw', 'Draw'), ('clawback', 'Clawback')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_applied', models.DecimalField(decimal_places=2, help_text='The percentage rate used.', max_digits=5)),
                ('date_earned', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('is_split', models.BooleanField(default=False)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before any splits', max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('disputed', 'Disputed'), ('adjusted', 'Adjusted'), ('approved', 'Approved'), ('paid', 'Paid'), ('deleted', 'Deleted')], max_length=20)),
                ('old_values', models.JSONField(blank=True, help_text='JSON of old field values', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='JSON of new field values', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionDispute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('calculation_error', 'Calculation Error'), ('incorrect_rate', 'Incorrect Rate Applied'), ('wrong_user', 'Commission Assigned to Wrong User'), ('duplicate', 'Duplicate Commission'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('date_raised', models.DateTimeField(auto_now_add=True)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid')], default='calculated', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('commission_plan_name', models.CharField(max_length=100)),
                ('commission_plan_description', models.TextField(blank=True)),
                ('commission_plan_is_active', models.BooleanField(default=True)),
                ('basis', models.CharField(choices=[('revenue', 'Total Revenue'), ('margin', 'Gross Margin/Profit'), ('units', 'Units Sold'), ('acv', 'Annual Contract Value (ACV)'), ('mrr', 'Monthly Recurring Revenue (MRR)')], default='revenue', max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPlanTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_data', models.JSONField(help_text='JSON representation of the plan template')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPlanVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Description of changes in this version')),
                ('plan_data', models.JSONField(help_text='JSON representation of the plan at this version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(blank=True, help_text='Category of products this rule applies to.', max_length=100)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat Rate'), ('tiered', 'Tiered Rate'), ('accelerator', 'Accelerator'), ('decelerator', 'Decelerator')], default='flat', max_length=20)),
                ('rate_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10.00 for 10%) or fixed amount.', max_digits=5)),
                ('tier_min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum sales amount for this tier.', max_digits=14)),
                ('tier_max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum sales amount for this tier. Leave blank for infinity.', max_digits=14, null=True)),
                ('performance_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Performance threshold for accelerator/decelerator (e.g., 90 for 90% attainment)', max_digits=5, null=True)),
                ('split_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage of commission to give to the split user (e.g., 50 for 50%)', max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SplitCommission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('split_commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('split_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('split_type', models.CharField(choices=[('team_deal', 'Team Deal'), ('overlay', 'Overlay Commission'), ('referral', 'Referral')], default='team_deal', max_length=20)),
                ('split_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of original commission', max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCommissionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_commission_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
