# Generated by Django 5.2.7 on 2025-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for bonus, negative for deduction.', max_digits=12)),
                ('adjusted_description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('bonus', 'Bonus'), ('deduction', 'Deduction'), ('draw', 'Draw'), ('clawback', 'Clawback')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_applied', models.DecimalField(decimal_places=2, help_text='The percentage rate used.', max_digits=5)),
                ('date_earned', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('commission_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid')], default='calculated', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('commission_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('commission_plan_name', models.CharField(max_length=100)),
                ('commission_plan_description', models.TextField(blank=True)),
                ('commission_plan_is_active', models.BooleanField(default=True)),
                ('basis', models.CharField(choices=[('revenue', 'Total Revenue'), ('margin', 'Gross Margin/Profit'), ('units', 'Units Sold'), ('acv', 'Annual Contract Value (ACV)'), ('mrr', 'Monthly Recurring Revenue (MRR)')], default='revenue', max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('commission_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(blank=True, help_text='Category of products this rule applies to.', max_length=100)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat Rate'), ('tiered', 'Tiered Rate')], default='flat', max_length=20)),
                ('rate_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10.00 for 10%) or fixed amount.', max_digits=5)),
                ('tier_min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum sales amount for this tier.', max_digits=14)),
                ('tier_max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum sales amount for this tier. Leave blank for infinity.', max_digits=14, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('quota_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCommissionPlan',
            fields=[
                ('user_commission_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
