# Generated by Django 5.2.7 on 2025-11-22 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('opportunities', '0003_auto_20251120_1627'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('basis', models.CharField(choices=[('revenue', 'Total Revenue'), ('margin', 'Gross Margin/Profit'), ('units', 'Units Sold'), ('acv', 'Annual Contract Value (ACV)'), ('mrr', 'Monthly Recurring Revenue (MRR)')], default='revenue', max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commissionrule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='commissionrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commissionrule',
            name='percentage',
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Specific product this rule applies to. Leave blank for all.', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='product_category',
            field=models.CharField(blank=True, help_text='Category of products this rule applies to.', max_length=100),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='rate_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('tiered', 'Tiered Rate')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='rate_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage (e.g. 10.00 for 10%) or fixed amount.', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='tier_max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum sales amount for this tier. Leave blank for infinity.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='tier_min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum sales amount for this tier.', max_digits=14),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for bonus, negative for deduction.', max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('bonus', 'Bonus'), ('deduction', 'Deduction'), ('draw', 'Draw'), ('clawback', 'Clawback')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_applied', models.DecimalField(decimal_places=2, help_text='The percentage rate used.', max_digits=5)),
                ('date_earned', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='commissions.commissionplan'),
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.commissionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CommissionLog',
        ),
    ]
