# Generated by Django 5.2.7 on 2025-12-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0002_initial'),
        ('opportunities', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='commission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='payment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.commissionpayment'),
        ),
        migrations.AddField(
            model_name='commissionplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='commission_rule_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='commissions.commissionplan'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Specific product this rule applies to. Leave blank for all.', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='quota',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='quota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercommissionplan',
            name='assigned_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.commissionplan'),
        ),
        migrations.AddField(
            model_name='usercommissionplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usercommissionplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
