# Generated by Django 5.2.9 on 2026-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(max_length=255)),
                ('dashboard_description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict, help_text='Widget layout configuration')),
                ('widgets', models.JSONField(default=list, help_text='List of widgets with their positions and settings')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default dashboard")),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this dashboard is shared with others')),
                ('role_based', models.CharField(blank=True, help_text='Role this dashboard is designed for', max_length=50)),
                ('config_created_at', models.DateTimeField(auto_now_add=True)),
                ('config_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-config_created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type_old', models.CharField(max_length=50, verbose_name='Widget Type (Legacy)')),
                ('widget_name', models.CharField(max_length=255, verbose_name='Widget Name')),
                ('widget_description', models.TextField()),
                ('category_old', models.CharField(default='general', max_length=50, verbose_name='Category (Legacy)')),
                ('template_path', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('main', 'Main'), ('sidebar', 'Sidebar'), ('footer', 'Footer')], default='main', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('widget_is_active', models.BooleanField(default=True)),
                ('widget_created_at', models.DateTimeField(auto_now_add=True)),
                ('widget_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, help_text="e.g., 'leads', 'opportunities'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('widget_category_is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('widget_category_created_at', models.DateTimeField(auto_now_add=True)),
                ('widget_category_updated_at', models.DateTimeField(auto_now=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Widget Categories',
                'ordering': ['order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='WidgetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(db_index=True, help_text="e.g., 'revenue', 'pipeline'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('widget_type_is_active', models.BooleanField(default=True, help_text='Whether this widget type is active')),
                ('widget_type_created_at', models.DateTimeField(auto_now_add=True)),
                ('widget_type_updated_at', models.DateTimeField(auto_now=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Widget Types',
                'ordering': ['order', 'widget_name'],
            },
        ),
    ]
