# Generated by Django 5.2.7 on 2025-11-21 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('revenue', 'Revenue Chart'), ('pipeline', 'Sales Pipeline'), ('tasks', 'Task List'), ('leads', 'Lead Metrics'), ('nps', 'NPS Score'), ('cases', 'Support Cases'), ('activity', 'Recent Activity'), ('leaderboard', 'Sales Leaderboard')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template_path', models.CharField(max_length=255)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('default_span', models.IntegerField(default=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Dashboard name, e.g., 'Sales Overview', 'Manager Dashboard'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default dashboard for this user')),
                ('is_shared', models.BooleanField(default=False, help_text='Share with all users in tenant')),
                ('layout', models.JSONField(default=dict, help_text='Grid layout configuration with widget placements')),
                ('widget_settings', models.JSONField(blank=True, default=dict, help_text='Custom settings per widget')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='dashboard_d_user_id_8d941b_idx'), models.Index(fields=['tenant_id', 'is_shared'], name='dashboard_d_tenant__218e82_idx')],
                'unique_together': {('user', 'name', 'tenant_id')},
            },
        ),
    ]
