# Generated by Django 5.2.7 on 2025-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardwidget',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='category',
            field=models.CharField(choices=[('leads', 'Leads'), ('opportunities', 'Opportunities'), ('revenue', 'Revenue'), ('tasks', 'Tasks'), ('cases', 'Cases'), ('accounts', 'Accounts'), ('analytics', 'Analytics'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
