# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('reports', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.report'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='widgetcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic category (replaces category_old field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_widgets', to='dashboard.widgetcategory'),
        ),
        migrations.AddField(
            model_name='widgettype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='widget_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic widget type (replaces widget_type_old field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_widgets', to='dashboard.widgettype'),
        ),
        migrations.AlterUniqueTogether(
            name='widgetcategory',
            unique_together={('tenant', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='widgettype',
            unique_together={('tenant', 'widget_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidget',
            unique_together={('tenant', 'widget_type_old')},
        ),
    ]
