# Generated by Django 5.2.7 on 2025-11-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboardwidget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='icon',
            field=models.CharField(default='bi-grid-3x3-gap', help_text="Bootstrap icon class (e.g., 'bi-graph-up')", max_length=50),
        ),
    ]
