# Generated by Django 5.2.7 on 2025-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboardwidget_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='category',
            field=models.CharField(choices=[('leads', 'Leads'), ('opportunities', 'Opportunities'), ('revenue', 'Revenue'), ('sales', 'Sales'), ('tasks', 'Tasks'), ('cases', 'Cases'), ('accounts', 'Accounts'), ('products', 'Products'), ('proposals', 'Proposals'), ('communication', 'Communication'), ('engagement', 'Engagement'), ('nps', 'NPS'), ('analytics', 'Analytics'), ('billing', 'Billing'), ('commissions', 'Commissions'), ('infrastructure', 'Infrastructure'), ('tenants', 'Tenants'), ('marketing', 'Marketing'), ('automation', 'Automation'), ('learn', 'Learning'), ('developer', 'Developer'), ('control_plane', 'Control Plane'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('revenue', 'Revenue Chart'), ('pipeline', 'Sales Pipeline'), ('tasks', 'Task List'), ('leads', 'Lead Metrics'), ('accounts', 'Accounts Overview'), ('opportunities', 'Opportunities Overview'), ('cases', 'Support Cases'), ('nps', 'NPS Score'), ('communication', 'Communication Stats'), ('engagement', 'Engagement Metrics'), ('sales', 'Sales Performance'), ('products', 'Product Metrics'), ('proposals', 'Proposal Pipeline'), ('marketing', 'Marketing Campaigns'), ('commissions', 'Commission Tracking'), ('reports', 'Report Dashboard'), ('leaderboard', 'Sales Leaderboard'), ('activity', 'Recent Activity'), ('automation', 'Automation Workflows'), ('settings', 'System Settings'), ('learn', 'Learning Progress'), ('developer', 'Developer Tools'), ('billing', 'Billing Overview'), ('infrastructure', 'Infrastructure Usage'), ('tenants', 'Tenant Management'), ('audit_logs', 'Audit Logs'), ('feature_flags', 'Feature Flags'), ('global_alerts', 'Global Alerts')], max_length=50, unique=True),
        ),
    ]
