# Generated by Django 5.2.9 on 2026-01-24 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_promotion_coupon'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('check_list', models.JSONField(help_text="JSON list of check items (e.g., ['Visual damage', 'Functionality'])")),
                ('is_required_on_receipt', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_rules', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_reference', models.CharField(help_text='PO #, WO #, etc.', max_length=100)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional Pass')], default='passed', max_length=20)),
                ('results_data', models.JSONField(help_text='Responses to the checklist items')),
                ('comments', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_performed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='quality_control.inspectionrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonConformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, choices=[('return_to_vendor', 'Return to Vendor'), ('rework', 'Rework Required'), ('scrap', 'Scrap Asset'), ('accept_as_is', 'Accept as is (Minor)')], max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ncr', to='quality_control.inspectionlog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
