# Generated by Django 5.2.9 on 2026-02-02 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrule',
            name='aql_level',
            field=models.FloatField(blank=True, choices=[(0.65, '0.65'), (1.0, '1.0'), (1.5, '1.5'), (2.5, '2.5'), (4.0, '4.0'), (6.5, '6.5')], help_text='Acceptable Quality Level', null=True),
        ),
        migrations.AddField(
            model_name='inspectionrule',
            name='inspection_level',
            field=models.CharField(blank=True, choices=[('S-1', 'S-1'), ('S-2', 'S-2'), ('S-3', 'S-3'), ('S-4', 'S-4'), ('I', 'General I'), ('II', 'General II'), ('III', 'General III')], default='II', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrule',
            name='sampling_type',
            field=models.CharField(choices=[('100_percent', '100% Inspection'), ('acceptance_sampling', 'Acceptance Sampling (AQL)')], default='100_percent', max_length=20),
        ),
        migrations.AddField(
            model_name='nonconformancereport',
            name='rca_data',
            field=models.JSONField(blank=True, help_text='Structured RCA findings (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='nonconformancereport',
            name='rca_type',
            field=models.CharField(choices=[('5_whys', '5 Whys'), ('fishbone', 'Fishbone Diagram'), ('other', 'Other/None')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionrule',
            name='check_list',
            field=models.JSONField(help_text='JSON list of check items. Each item should be a dict with keys: id, label, type (bool, number, photo, text), required.'),
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capa_type', models.CharField(choices=[('corrective', 'Corrective Action'), ('preventive', 'Preventive Action')], default='corrective', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('action_plan', models.TextField()),
                ('verification_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('in_progress', 'In Progress'), ('verification', 'Verification'), ('closed', 'Closed')], default='proposed', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_capas', to=settings.AUTH_USER_MODEL)),
                ('source_ncr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='quality_control.nonconformancereport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_capas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='quality_control/attachments/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('item_id', models.CharField(blank=True, help_text='ID of the checklist item this attachment relates to', max_length=50)),
                ('inspection_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quality_control.inspectionlog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
