# Generated by Django 5.2.9 on 2026-02-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_inspectionrule_aql_level_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheckLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='The question or check item text', max_length=255)),
                ('check_type', models.CharField(choices=[('bool', 'Pass/Fail'), ('number', 'Value Range'), ('text', 'Observations'), ('photo', 'Visual Evidence')], default='bool', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Optional category for grouping (e.g., Safety, Packaging)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional instructions for the inspector')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Quality Check',
                'verbose_name_plural': 'Quality Check Library',
                'ordering': ['category', 'label'],
            },
        ),
    ]
