# Generated by Django 5.2.7 on 2025-11-25 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('maintenance', 'Scheduled Maintenance'), ('outage', 'Critical Outage'), ('announcement', 'New Feature Announcement'), ('security', 'Security Alert'), ('general', 'General Notice')], default='general', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=True, help_text='Show to all tenants')),
                ('target_tenant_ids', models.JSONField(blank=True, default=list, help_text='Specific tenant IDs if not global')),
                ('is_dismissible', models.BooleanField(default=True)),
                ('show_on_all_pages', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['is_active', '-start_time'], name='global_aler_is_acti_9b9deb_idx'), models.Index(fields=['severity', '-start_time'], name='global_aler_severit_612890_idx')],
            },
        ),
    ]
