# Generated by Django 5.2.9 on 2026-01-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_payrollrun_payrollline'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Required for termination benefit forecasting', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension_scheme',
            field=models.CharField(blank=True, help_text='Standard Pension or Retirement plan', max_length=100),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='pension_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='tax_withheld',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='accrual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='is_accrued',
            field=models.BooleanField(default=False, help_text='Recognized as expense in GL'),
        ),
    ]
