# Generated by Django 5.2.9 on 2026-01-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_attendance_created_at_attendance_updated_at_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tenant_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='tenants.tenantmember'),
        ),
    ]
