# Generated by Django 5.2.9 on 2026-01-30 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_tenant_member'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('maternity', 'Maternity/Paternity')], max_length=20)),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remaining_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('year', models.IntegerField(default=2026)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
