# Generated by Django 5.2.9 on 2026-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_leavepolicy_performancegoal_goalreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='biometric_ref',
            field=models.CharField(blank=True, help_text='Reference ID from biometric device', max_length=100, null=True),
        ),
    ]
