# Generated by Django 5.2.9 on 2026-02-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_journalentry_exchange_rate_and_more'),
        ('hr', '0008_attendance_biometric_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='accounting.journalentry'),
        ),
    ]
