# Generated by Django 5.2.7 on 2025-11-06 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('account.created', 'Account Created'), ('account.health_changed', 'Account Health Changed'), ('lead.created', 'Lead Created'), ('lead.qualified', 'Lead Qualified'), ('opportunity.created', 'Opportunity Created'), ('opportunity.stage_changed', 'Opportunity Stage Changed'), ('proposal.viewed', 'Proposal Viewed'), ('proposal.esg_viewed', 'ESG Section Viewed'), ('case.created', 'Case Created'), ('case.sla_breached', 'SLA Breached'), ('case.csat_submitted', 'CSAT Submitted'), ('nps.submitted', 'NPS Submitted'), ('nps.detractor_alert', 'NPS Detractor Alert'), ('custom_status.changed', 'Custom Status Changed'), ('crm_setting.changed', 'CRM Setting Changed'), ('team.member_onboarded', 'Team Member Onboarded'), ('web_to_lead.submitted', 'Web-to-Lead Submitted')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('create_task', 'Create Task'), ('update_field', 'Update Field'), ('run_function', 'Run Function'), ('create_case', 'Create Case'), ('assign_owner', 'Assign Owner'), ('send_slack_message', 'Send Slack Message'), ('webhook', 'Webhook')], max_length=50)),
                ('config', models.JSONField(help_text='Action configuration (JSON)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.automation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('field_path', models.CharField(help_text="Dot notation path (e.g., 'account.industry')", max_length=100)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal'), ('in', 'In List'), ('contains', 'Contains'), ('regex', 'Matches Regex')], max_length=20)),
                ('value', models.JSONField(help_text='Value to compare against')),
                ('is_active', models.BooleanField(default=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automation.automation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('trigger_payload', models.JSONField()),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('conditions_evaluated', 'Conditions Evaluated'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='triggered', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automation')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['trigger_type', 'is_active'], name='automation__trigger_ea1b06_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['tenant_id', 'is_active'], name='automation__tenant__8d88b3_idx'),
        ),
    ]
