# Generated by Django 5.2.7 on 2025-11-24 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('account.created', 'Account Created'), ('account.health_changed', 'Account Health Changed'), ('lead.created', 'Lead Created'), ('lead.qualified', 'Lead Qualified'), ('opportunity.created', 'Opportunity Created'), ('opportunity.stage_changed', 'Opportunity Stage Changed'), ('proposal.viewed', 'Proposal Viewed'), ('proposal.esg_viewed', 'ESG Section Viewed'), ('case.created', 'Case Created'), ('case.sla_breached', 'SLA Breached'), ('case.csat_submitted', 'CSAT Submitted'), ('nps.submitted', 'NPS Submitted'), ('nps.detractor_alert', 'NPS Detractor Alert'), ('custom_status.changed', 'Custom Status Changed'), ('crm_setting.changed', 'CRM Setting Changed'), ('team.member_onboarded', 'Team Member Onboarded'), ('web_to_lead.submitted', 'Web-to-Lead Submitted')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('create_task', 'Create Task'), ('update_field', 'Update Field'), ('run_function', 'Run Function'), ('create_case', 'Create Case'), ('assign_owner', 'Assign Owner'), ('send_slack_message', 'Send Slack Message'), ('webhook', 'Webhook')], max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters for the action (JSON)')),
                ('order', models.IntegerField(default=0, help_text='Execution order (lower executes first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='automation.workflow')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('trigger_payload', models.JSONField(help_text='Data that triggered the workflow')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.workflow')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('trigger_event', models.CharField(help_text='Event that triggers this workflow', max_length=100)),
                ('conditions', models.JSONField(default=dict, help_text='Conditions that must be met for the trigger to fire (JSON)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='automation.workflow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['trigger_type', 'is_active'], name='automation__trigger_7d5d87_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['tenant_id', 'is_active'], name='automation__tenant__c8aa27_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', 'status'], name='automation__workflo_2bbb85_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['tenant_id', 'executed_at'], name='automation__tenant__127911_idx'),
        ),
    ]
