# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.automation'),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='automationalert',
            name='alert_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_alerts_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationalert',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='automation.automation'),
        ),
        migrations.AddField(
            model_name='automationalert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='automationcondition',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automation.automation'),
        ),
        migrations.AddField(
            model_name='automationcondition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='automation.automation'),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='automationalert',
            name='execution_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.automationexecutionlog'),
        ),
        migrations.AddField(
            model_name='automationnotificationpreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='automationnotificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customcodeexecutionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customcodesnippet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcodesnippet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customcodeexecutionlog',
            name='custom_code_snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='automation.customcodesnippet'),
        ),
        migrations.AddField(
            model_name='qualitycheckschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_check_schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheckschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_check_schedules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='webhook_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='automation.webhookendpoint'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='automationalert',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='automation.workflow'),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='automation.workflow'),
        ),
        migrations.AddField(
            model_name='workflowanalyticssnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workflowanalyticssnapshot',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='automation.workflow'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='approval_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='approval_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_responded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='requested_approvers',
            field=models.ManyToManyField(blank=True, related_name='pending_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='workflow_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.workflowaction'),
        ),
        migrations.AddField(
            model_name='workflowbranch',
            name='parent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_branches', to='automation.workflowbranch'),
        ),
        migrations.AddField(
            model_name='workflowbranch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workflowbranch',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_branches', to='automation.workflow'),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_actions', to='automation.workflowbranch'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='original_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='automation.workflowexecution'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.workflow'),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='workflow_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='automation.workflowexecution'),
        ),
        migrations.AddField(
            model_name='customcodeexecutionlog',
            name='workflow_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_code_logs', to='automation.workflowexecution'),
        ),
        migrations.AddField(
            model_name='automationalert',
            name='workflow_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.workflowexecution'),
        ),
        migrations.AddField(
            model_name='workflowscheduledexecution',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.workflowaction'),
        ),
        migrations.AddField(
            model_name='workflowscheduledexecution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workflowscheduledexecution',
            name='workflow_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='automation.workflowexecution'),
        ),
        migrations.AddField(
            model_name='workflowtrigger',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workflowtrigger',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='automation.workflow'),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='automation.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='automationnotificationpreference',
            unique_together={('user', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowanalyticssnapshot',
            unique_together={('workflow', 'snapshot_date', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowversion',
            unique_together={('workflow', 'version_number')},
        ),
    ]
