# Generated by Django 5.2.7 on 2025-11-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_workflow_workflowaction_workflowexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='builder_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw data from visual builder'),
        ),
    ]
