# Generated by Django 5.2.7 on 2025-11-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_workflow_builder_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('account.created', 'Account Created'), ('account.health_changed', 'Account Health Changed'), ('lead.created', 'Lead Created'), ('lead.qualified', 'Lead Qualified'), ('opportunity.created', 'Opportunity Created'), ('opportunity.stage_changed', 'Opportunity Stage Changed'), ('proposal.viewed', 'Proposal Viewed'), ('proposal.esg_viewed', 'ESG Section Viewed'), ('case.created', 'Case Created'), ('case.sla_breached', 'SLA Breached'), ('case.csat_submitted', 'CSAT Submitted'), ('nps.submitted', 'NPS Submitted'), ('nps.detractor_alert', 'NPS Detractor Alert'), ('custom_status.changed', 'Custom Status Changed'), ('crm_setting.changed', 'CRM Setting Changed'), ('team.member_onboarded', 'Team Member Onboarded'), ('web_to_lead.submitted', 'Web-to-Lead Submitted')], max_length=50)),
                ('builder_data', models.JSONField(help_text='Drawflow JSON structure')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
