# Generated by Django 5.2.7 on 2025-12-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(db_index=True, help_text="e.g., 'tech', 'finance'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('industry_is_active', models.BooleanField(default=True, help_text='Whether this industry is active')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['order', 'industry_name'],
                'unique_together': {('tenant_id', 'industry_name')},
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, help_text="e.g., 'web', 'event'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('source_is_active', models.BooleanField(default=True, help_text='Whether this source is active')),
                ('is_system', models.BooleanField(default=False)),
                ('conversion_rate_target', models.FloatField(default=0.0, help_text='Target conversion rate (0-100)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Lead Sources',
                'ordering': ['order', 'source_name'],
                'unique_together': {('tenant_id', 'source_name')},
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(db_index=True, help_text="e.g., 'new', 'qualified'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('status_is_active', models.BooleanField(default=True, help_text='Whether this status is active')),
                ('is_system', models.BooleanField(default=False)),
                ('is_qualified', models.BooleanField(default=False, help_text='Indicates lead is qualified')),
                ('is_closed', models.BooleanField(default=False, help_text='Indicates lead is closed (won/lost)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Lead Statuses',
                'ordering': ['order', 'status_name'],
                'unique_together': {('tenant_id', 'status_name')},
            },
        ),
        migrations.CreateModel(
            name='MarketingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(db_index=True, help_text="e.g., 'email', 'social'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('channel_is_active', models.BooleanField(default=True, help_text='Whether this channel is active')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Marketing Channels',
                'ordering': ['order', 'channel_name'],
                'unique_together': {('tenant_id', 'channel_name')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('manufacturing', 'Manufacturing'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('energy', 'Energy'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('lead_description', models.TextField(blank=True, help_text='Additional notes about the lead')),
                ('title', models.CharField(blank=True, help_text='Custom title for the lead', max_length=255)),
                ('lead_source', models.CharField(choices=[('web', 'Web Form'), ('event', 'Event'), ('referral', 'Referral'), ('ads', 'Paid Ads'), ('manual', 'Manual Entry')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], default='new', max_length=20)),
                ('lead_score', models.IntegerField(default=0)),
                ('company_size', models.IntegerField(blank=True, help_text='Number of employees at the company', null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Annual revenue of the company', max_digits=12, null=True)),
                ('funding_stage', models.CharField(blank=True, help_text='Funding stage of the company (e.g., Series A, IPO)', max_length=50)),
                ('business_type', models.CharField(blank=True, default='B2B', help_text='Business type (B2B, B2C, etc.)', max_length=50)),
                ('cac_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Customer acquisition cost for this lead', max_digits=10, null=True)),
                ('marketing_channel', models.CharField(blank=True, choices=[('email', 'Email Marketing'), ('social', 'Social Media'), ('paid_ads', 'Paid Ads'), ('content', 'Content Marketing'), ('seo', 'SEO'), ('referral', 'Referral'), ('event', 'Events'), ('direct', 'Direct Traffic'), ('other', 'Other')], help_text='Marketing channel that brought this lead (legacy field)', max_length=20)),
                ('campaign_source', models.CharField(blank=True, help_text='Specific campaign that generated this lead', max_length=100)),
                ('lead_acquisition_date', models.DateTimeField(blank=True, help_text='Date when the lead was acquired', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('converted_to_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='accounts.account')),
                ('industry_ref', models.ForeignKey(blank=True, db_constraint=False, help_text='Dynamic industry (replaces industry field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.industry')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('source_ref', models.ForeignKey(blank=True, help_text='Dynamic lead source (replaces lead_source field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadsource')),
                ('status_ref', models.ForeignKey(blank=True, help_text='Dynamic lead status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstatus')),
                ('marketing_channel_ref', models.ForeignKey(blank=True, db_constraint=False, help_text='Dynamic marketing channel (replaces marketing_channel field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.marketingchannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebToLeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(help_text='Name of the web-to-lead form', max_length=255)),
                ('form_description', models.TextField(blank=True, help_text='Description of the form')),
                ('form_is_active', models.BooleanField(default=True, help_text='Whether this form is active')),
                ('success_redirect_url', models.URLField(default='/thank-you/')),
                ('include_first_name', models.BooleanField(default=True)),
                ('include_last_name', models.BooleanField(default=True)),
                ('include_email', models.BooleanField(default=True)),
                ('include_phone', models.BooleanField(default=False)),
                ('include_company', models.BooleanField(default=True)),
                ('include_job_title', models.BooleanField(default=False)),
                ('include_industry', models.BooleanField(default=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('assign_to_role', models.CharField(blank=True, max_length=100)),
                ('form_submissions', models.IntegerField(default=0)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadSourceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('web', 'Web Form'), ('event', 'Event'), ('referral', 'Referral'), ('ads', 'Paid Ads'), ('manual', 'Manual Entry')], max_length=20)),
                ('lead_count', models.IntegerField(default=0)),
                ('qualified_count', models.IntegerField(default=0)),
                ('converted_count', models.IntegerField(default=0)),
                ('avg_lead_score', models.FloatField(default=0.0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('date', 'source', 'tenant')},
            },
        ),
    ]
