# Generated by Django 5.2.7 on 2025-11-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('manufacturing', 'Manufacturing'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('energy', 'Energy'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('web', 'Web Form'), ('event', 'Event'), ('referral', 'Referral'), ('ads', 'Paid Ads'), ('manual', 'Manual Entry')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], default='new', max_length=20)),
                ('lead_score', models.IntegerField(default=0)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('converted_to_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='accounts.account')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadSourceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('web', 'Web Form'), ('event', 'Event'), ('referral', 'Referral'), ('ads', 'Paid Ads'), ('manual', 'Manual Entry')], max_length=20)),
                ('lead_count', models.IntegerField(default=0)),
                ('qualified_count', models.IntegerField(default=0)),
                ('converted_count', models.IntegerField(default=0)),
                ('avg_lead_score', models.FloatField(default=0.0)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('date', 'source', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='WebToLeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('success_redirect_url', models.URLField(default='/thank-you/')),
                ('include_first_name', models.BooleanField(default=True)),
                ('include_last_name', models.BooleanField(default=True)),
                ('include_email', models.BooleanField(default=True)),
                ('include_phone', models.BooleanField(default=False)),
                ('include_company', models.BooleanField(default=True)),
                ('include_job_title', models.BooleanField(default=False)),
                ('include_industry', models.BooleanField(default=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('assign_to_role', models.CharField(blank=True, max_length=100)),
                ('form_submissions', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
