# Generated by Django 5.2.7 on 2025-12-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('leads', '0001_initial'),
        ('marketing', '0001_initial'),
        ('settings_app', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrule',
            name='rule_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic rule type (replaces rule_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignment_rules', to='settings_app.assignmentruletype'),
        ),
        migrations.AddField(
            model_name='assignmentrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignment_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='behavioralscoringrule',
            name='action_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic action type (replaces action_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='behavioral_scoring_rules', to='leads.actiontype'),
        ),
        migrations.AddField(
            model_name='behavioralscoringrule',
            name='business_impact_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic business impact (replaces business_impact field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavioral_scoring_rules_by_impact', to='leads.behavioralscoringrule'),
        ),
        migrations.AddField(
            model_name='behavioralscoringrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_behavioral_scoring_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='demographicscoringrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_demographic_scoring_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='industry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign_ref',
            field=models.ForeignKey(blank=True, help_text='Internal Campaign reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dynamic industry (replaces industry field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.industry'),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic lead source (replaces lead_source field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadsource'),
        ),
        migrations.AddField(
            model_name='leadsourceanalytics',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic lead status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstatus'),
        ),
        migrations.AddField(
            model_name='marketingchannel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='marketing_channel_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dynamic marketing channel (replaces marketing_channel field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.marketingchannel'),
        ),
        migrations.AddField(
            model_name='operatortype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_operator_types', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='demographicscoringrule',
            name='operator_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic operator (replaces operator field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demographic_scoring_rules', to='leads.operatortype'),
        ),
        migrations.AddField(
            model_name='webtoleadform',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webtoleadform',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='actiontype',
            unique_together={('tenant', 'action_type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('tenant_id', 'industry_name')},
        ),
        migrations.AlterUniqueTogether(
            name='leadsource',
            unique_together={('tenant_id', 'source_name')},
        ),
        migrations.AlterUniqueTogether(
            name='leadsourceanalytics',
            unique_together={('date', 'source', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='leadstatus',
            unique_together={('tenant_id', 'status_name')},
        ),
        migrations.AlterUniqueTogether(
            name='marketingchannel',
            unique_together={('tenant_id', 'channel_name')},
        ),
        migrations.AlterUniqueTogether(
            name='operatortype',
            unique_together={('tenant', 'operator_name')},
        ),
    ]
