# Generated by Django 5.2.7 on 2025-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='source',
            new_name='lead_source',
        ),
        migrations.RemoveField(
            model_name='webtoleadform',
            name='conversion_rate',
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes about the lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, help_text='Custom title for the lead', max_length=255),
        ),
    ]
