# Generated by Django 5.2.7 on 2025-11-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('leads', '0002_rename_source_lead_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.account'),
        ),
    ]
