# Generated by Django 5.2.7 on 2025-11-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('conversion_rate_target', models.FloatField(default=0.0, help_text='Target conversion rate (0-100)')),
            ],
            options={
                'verbose_name_plural': 'Lead Sources',
                'ordering': ['order', 'name'],
                'unique_together': {('tenant_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='ID of the tenant (organization) this record belongs to', max_length=50, null=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_qualified', models.BooleanField(default=False, help_text='Indicates lead is qualified')),
                ('is_closed', models.BooleanField(default=False, help_text='Indicates lead is closed (won/lost)')),
            ],
            options={
                'verbose_name_plural': 'Lead Statuses',
                'ordering': ['order', 'name'],
                'unique_together': {('tenant_id', 'name')},
            },
        ),
    ]
