# Generated by Django 5.2.9 on 2026-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_created_at_lead_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatus',
            name='color',
            field=models.CharField(default='#0e86ef', help_text='Hex color code', max_length=7),
        ),
    ]
