# Generated by Django 5.2.7 on 2025-11-21 04:14

from django.db import migrations


def seed_lead_sources(apps, schema_editor):
    """Seed default lead source values."""
    LeadSource = apps.get_model('leads', 'LeadSource')
    
    sources = [
        {
            'name': 'web',
            'label': 'Web Form',
            'order': 1,
            'color': '#007bff',  # Blue
            'icon': 'bi-globe',
            'is_system': True,
            'is_active': True,
            'conversion_rate_target': 15.0,
        },
        {
            'name': 'event',
            'label': 'Event',
            'order': 2,
            'color': '#6f42c1',  # Purple
            'icon': 'bi-calendar-event',
            'is_system': True,
            'is_active': True,
            'conversion_rate_target': 25.0,
        },
        {
            'name': 'referral',
            'label': 'Referral',
            'order': 3,
            'color': '#28a745',  # Green
            'icon': 'bi-people',
            'is_system': True,
            'is_active': True,
            'conversion_rate_target': 35.0,
        },
        {
            'name': 'ads',
            'label': 'Paid Ads',
            'order': 4,
            'color': '#fd7e14',  # Orange
            'icon': 'bi-megaphone',
            'is_system': True,
            'is_active': True,
            'conversion_rate_target': 10.0,
        },
        {
            'name': 'manual',
            'label': 'Manual Entry',
            'order': 5,
            'color': '#6c757d',  # Gray
            'icon': 'bi-pencil',
            'is_system': True,
            'is_active': True,
            'conversion_rate_target': 20.0,
        },
    ]
    
    for source in sources:
        LeadSource.objects.get_or_create(
            name=source['name'],
            tenant_id=None,  # Global/system sources
            defaults=source
        )


def seed_lead_statuses(apps, schema_editor):
    """Seed default lead status values."""
    LeadStatus = apps.get_model('leads', 'LeadStatus')
    
    statuses = [
        {
            'name': 'new',
            'label': 'New',
            'order': 1,
            'color': '#17a2b8',  # Cyan
            'icon': 'bi-star',
            'is_system': True,
            'is_active': True,
            'is_qualified': False,
            'is_closed': False,
        },
        {
            'name': 'contacted',
            'label': 'Contacted',
            'order': 2,
            'color': '#007bff',  # Blue
            'icon': 'bi-telephone',
            'is_system': True,
            'is_active': True,
            'is_qualified': False,
            'is_closed': False,
        },
        {
            'name': 'qualified',
            'label': 'Qualified',
            'order': 3,
            'color': '#28a745',  # Green
            'icon': 'bi-check2-circle',
            'is_system': True,
            'is_active': True,
            'is_qualified': True,
            'is_closed': False,
        },
        {
            'name': 'unqualified',
            'label': 'Unqualified',
            'order': 4,
            'color': '#dc3545',  # Red
            'icon': 'bi-x-circle',
            'is_system': True,
            'is_active': True,
            'is_qualified': False,
            'is_closed': True,
        },
        {
            'name': 'converted',
            'label': 'Converted',
            'order': 5,
            'color': '#6f42c1',  # Purple
            'icon': 'bi-trophy',
            'is_system': True,
            'is_active': True,
            'is_qualified': True,
            'is_closed': True,
        },
    ]
    
    for status in statuses:
        LeadStatus.objects.get_or_create(
            name=status['name'],
            tenant_id=None,  # Global/system statuses
            defaults=status
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded data on rollback."""
    LeadSource = apps.get_model('leads', 'LeadSource')
    LeadStatus = apps.get_model('leads', 'LeadStatus')
    
    LeadSource.objects.filter(is_system=True).delete()
    LeadStatus.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadsource_leadstatus'),
    ]

    operations = [
        migrations.RunPython(seed_lead_sources, reverse_seed),
        migrations.RunPython(seed_lead_statuses, migrations.RunPython.noop),
    ]
