# Generated by Django 5.2.7 on 2025-11-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_seed_lead_sources_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic lead source (replaces lead_source field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadsource'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic lead status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstatus'),
        ),
    ]
