# Generated by Django 5.2.7 on 2025-11-21 04:20

from django.db import migrations


def migrate_lead_sources_statuses(apps, schema_editor):
    """Populate source_ref and status_ref from legacy choice fields."""
    Lead = apps.get_model('leads', 'Lead')
    LeadSource = apps.get_model('leads', 'LeadSource')
    LeadStatus = apps.get_model('leads', 'LeadStatus')
    
    # Get all leads
    leads = Lead.objects.all()
    
    for lead in leads:
        # Migrate source
        if lead.lead_source:
            try:
                source_obj = LeadSource.objects.get(name=lead.lead_source)
                lead.source_ref = source_obj
            except LeadSource.DoesNotExist:
                # If custom value exists, create it or log warning
                pass
        
        # Migrate status
        if lead.status:
            try:
                status_obj = LeadStatus.objects.get(name=lead.status)
                lead.status_ref = status_obj
            except LeadStatus.DoesNotExist:
                # If custom value exists, create it or log warning
                pass
        
        lead.save(update_fields=['source_ref', 'status_ref'])


def reverse_migration(apps, schema_editor):
    """Clear the ref fields on rollback."""
    Lead = apps.get_model('leads', 'Lead')
    Lead.objects.all().update(source_ref=None, status_ref=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_source_ref_lead_status_ref'),
    ]

    operations = [
        migrations.RunPython(migrate_lead_sources_statuses, reverse_migration),
    ]
