# Generated by Django 5.2.7 on 2025-11-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'monday': '9:00-17:00', ...}"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_format',
            field=models.CharField(default='%Y-%m-%d', help_text='Python date format string', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#6f42c1', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#e3e6f3', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
