# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.utils.timezone
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern_name', models.CharField(db_index=True, help_text="e.g., 'daily', 'weekly'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('pattern_is_active', models.BooleanField(default=True, help_text='Whether this pattern is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Recurrence Patterns',
                'ordering': ['order', 'pattern_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, help_text='Description of the task')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='todo', max_length=20)),
                ('task_type', models.CharField(choices=[('lead_review', 'Lead Review'), ('lead_contact', 'Lead Contact'), ('lead_qualify', 'Lead Qualification'), ('account_followup', 'Account Follow-up'), ('opportunity_demo', 'Opportunity Demo'), ('proposal_followup', 'Proposal Follow-up'), ('renewal_reminder', 'Renewal Reminder'), ('csat_followup', 'CSAT Follow-up'), ('case_escalation', 'Case Escalation'), ('nps_detractor', 'NPS Detractor Follow-up'), ('esg_engagement', 'ESG Engagement'), ('custom', 'Custom Task')], max_length=50)),
                ('due_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='none', max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comment_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('created', 'Task Created'), ('updated', 'Task Updated'), ('completed', 'Task Completed'), ('assigned', 'Task Assigned'), ('commented', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('dependency_added', 'Dependency Added')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=tasks.models.get_task_attachment_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_type', models.CharField(choices=[('finish_start', 'Finish-Start'), ('start_start', 'Start-Start'), ('finish_finish', 'Finish-Finish'), ('start_finish', 'Start-Finish')], default='finish_start', help_text='Type of dependency relationship', max_length=20)),
                ('lag_time', models.DurationField(blank=True, help_text='Time delay between predecessor completion and successor start', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority_name', models.CharField(db_index=True, help_text="e.g., 'low', 'high'", max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('priority_is_active', models.BooleanField(default=True, help_text='Whether this priority is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Task Priorities',
                'ordering': ['order', 'priority_name'],
            },
        ),
        migrations.CreateModel(
            name='TaskSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_level', models.CharField(choices=[('view', 'View Only'), ('comment', 'View and Comment'), ('edit', 'View, Comment and Edit')], default='view', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('can_reassign', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_name', models.CharField(db_index=True, help_text="e.g., 'todo', 'completed'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('status_is_active', models.BooleanField(default=True, help_text='Whether this status is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Task Statuses',
                'ordering': ['order', 'status_name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(help_text='Name of the task template', max_length=255)),
                ('template_description', models.TextField(blank=True, help_text='Description of the template')),
                ('title_template', models.CharField(help_text='Template for task title with placeholders', max_length=255)),
                ('description_template', models.TextField(help_text='Template for task description with placeholders')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('task_type', models.CharField(choices=[('lead_review', 'Lead Review'), ('lead_contact', 'Lead Contact'), ('lead_qualify', 'Lead Qualification'), ('account_followup', 'Account Follow-up'), ('opportunity_demo', 'Opportunity Demo'), ('proposal_followup', 'Proposal Follow-up'), ('renewal_reminder', 'Renewal Reminder'), ('csat_followup', 'CSAT Follow-up'), ('case_escalation', 'Case Escalation'), ('nps_detractor', 'NPS Detractor Follow-up'), ('esg_engagement', 'ESG Engagement'), ('custom', 'Custom Task')], max_length=50)),
                ('due_date_offset_days', models.IntegerField(default=0, help_text='Number of days from creation to due date')),
                ('template_is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
                ('hours_spent', models.DecimalField(decimal_places=2, help_text='Hours spent on the task', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Description of work done')),
                ('is_billable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(db_index=True, help_text="e.g., 'lead_review', 'custom'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('type_is_active', models.BooleanField(default=True, help_text='Whether this type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Task Types',
                'ordering': ['order', 'type_name'],
            },
        ),
    ]
