# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('leads', '0002_initial'),
        ('opportunities', '0003_initial'),
        ('tasks', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencepattern',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='task',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cases.case'),
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='task',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_pattern_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic recurrence pattern (replaces recurrence_pattern field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.recurrencepattern'),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, help_text='Users mentioned in this comment', related_name='mentioned_in_task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='predecessor',
            field=models.ForeignKey(help_text='The task that must be completed first', on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='successor',
            field=models.ForeignKey(help_text='The task that depends on the predecessor', on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic priority (replaces priority field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskpriority'),
        ),
        migrations.AddField(
            model_name='tasksharing',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksharing',
            name='shared_with_team',
            field=models.ForeignKey(blank=True, help_text='Team member to share with', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenantmember'),
        ),
        migrations.AddField(
            model_name='tasksharing',
            name='shared_with_user',
            field=models.ForeignKey(blank=True, help_text='Specific user to share with', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksharing',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='tasksharing',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskstatus'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='priority_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic priority (replaces priority field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', to='tasks.taskpriority'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tasktimeentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='tasktimeentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tasktimeentry',
            name='user',
            field=models.ForeignKey(help_text='User who logged the time', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='task_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic task type (replaces task_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', to='tasks.tasktype'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic task type (replaces task_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.tasktype'),
        ),
        migrations.AlterUniqueTogether(
            name='recurrencepattern',
            unique_together={('tenant_id', 'pattern_name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('predecessor', 'successor')},
        ),
        migrations.AlterUniqueTogether(
            name='taskpriority',
            unique_together={('tenant_id', 'priority_name')},
        ),
        migrations.AlterUniqueTogether(
            name='tasksharing',
            unique_together={('task', 'shared_with_team'), ('task', 'shared_with_user')},
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('tenant_id', 'status_name')},
        ),
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('tenant_id', 'type_name')},
        ),
    ]
