# Generated by Django 5.2.7 on 2025-11-21 04:05

from django.db import migrations


def seed_task_priorities(apps, schema_editor):
    """Seed default task priority values."""
    TaskPriority = apps.get_model('tasks', 'TaskPriority')
    
    priorities = [
        {
            'name': 'low',
            'label': 'Low',
            'order': 1,
            'color': '#28a745',  # Green
            'icon': 'bi-arrow-down',
            'is_system': True,
            'is_active': True,
        },
        {
            'name': 'medium',
            'label': 'Medium',
            'order': 2,
            'color': '#ffc107',  # Yellow
            'icon': 'bi-dash',
            'is_system': True,
            'is_active': True,
        },
        {
            'name': 'high',
            'label': 'High',
            'order': 3,
            'color': '#fd7e14',  # Orange
            'icon': 'bi-arrow-up',
            'is_system': True,
            'is_active': True,
        },
        {
            'name': 'critical',
            'label': 'Critical',
            'order': 4,
            'color': '#dc3545',  # Red
            'icon': 'bi-exclamation-triangle',
            'is_system': True,
            'is_active': True,
        },
    ]
    
    for priority in priorities:
        TaskPriority.objects.get_or_create(
            name=priority['name'],
            tenant_id=None,  # Global/system priorities
            defaults=priority
        )


def seed_task_statuses(apps, schema_editor):
    """Seed default task status values."""
    TaskStatus = apps.get_model('tasks', 'TaskStatus')
    
    statuses = [
        {
            'name': 'todo',
            'label': 'To Do',
            'order': 1,
            'color': '#6c757d',  # Gray
            'icon': 'bi-circle',
            'is_system': True,
            'is_active': True,
            'is_closed': False,
        },
        {
            'name': 'in_progress',
            'label': 'In Progress',
            'order': 2,
            'color': '#007bff',  # Blue
            'icon': 'bi-arrow-repeat',
            'is_system': True,
            'is_active': True,
            'is_closed': False,
        },
        {
            'name': 'completed',
            'label': 'Completed',
            'order': 3,
            'color': '#28a745',  # Green
            'icon': 'bi-check-circle',
            'is_system': True,
            'is_active': True,
            'is_closed': True,
        },
        {
            'name': 'cancelled',
            'label': 'Cancelled',
            'order': 4,
            'color': '#dc3545',  # Red
            'icon': 'bi-x-circle',
            'is_system': True,
            'is_active': True,
            'is_closed': True,
        },
        {
            'name': 'overdue',
            'label': 'Overdue',
            'order': 5,
            'color': '#fd7e14',  # Orange
            'icon': 'bi-clock-history',
            'is_system': True,
            'is_active': True,
            'is_closed': False,
        },
    ]
    
    for status in statuses:
        TaskStatus.objects.get_or_create(
            name=status['name'],
            tenant_id=None,  # Global/system statuses
            defaults=status
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded data on rollback."""
    TaskPriority = apps.get_model('tasks', 'TaskPriority')
    TaskStatus = apps.get_model('tasks', 'TaskStatus')
    
    TaskPriority.objects.filter(is_system=True).delete()
    TaskStatus.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskpriority_taskstatus'),
    ]

    operations = [
        migrations.RunPython(seed_task_priorities, reverse_seed),
        migrations.RunPython(seed_task_statuses, migrations.RunPython.noop),
    ]
