# Generated by Django 5.2.7 on 2025-11-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_seed_task_priorities_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic task priority (replaces priority field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskpriority'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic task status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskstatus'),
        ),
    ]
