# Generated by Django 5.2.7 on 2025-11-21 04:20

from django.db import migrations


def migrate_task_priorities_statuses(apps, schema_editor):
    """Populate priority_ref and status_ref from legacy choice fields."""
    Task = apps.get_model('tasks', 'Task')
    TaskPriority = apps.get_model('tasks', 'TaskPriority')
    TaskStatus = apps.get_model('tasks', 'TaskStatus')
    
    # Get all tasks
    tasks = Task.objects.all()
    
    for task in tasks:
        # Migrate priority
        if task.priority:
            try:
                priority_obj = TaskPriority.objects.get(name=task.priority)
                task.priority_ref = priority_obj
            except TaskPriority.DoesNotExist:
                # If custom value exists, create it or log warning
                pass
        
        # Migrate status
        if task.status:
            try:
                status_obj = TaskStatus.objects.get(name=task.status)
                task.status_ref = status_obj
            except TaskStatus.DoesNotExist:
                # If custom value exists, create it or log warning
                pass
        
        task.save(update_fields=['priority_ref', 'status_ref'])


def reverse_migration(apps, schema_editor):
    """Clear the ref fields on rollback."""
    Task = apps.get_model('tasks', 'Task')
    Task.objects.all().update(priority_ref=None, status_ref=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_priority_ref_task_status_ref'),
    ]

    operations = [
        migrations.RunPython(migrate_task_priorities_statuses, reverse_migration),
    ]
