# Generated by Django 5.2.7 on 2025-12-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('settings_app', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_rule_name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('territory', 'Territory-Based'), ('load_balanced', 'Load Balanced'), ('criteria', 'Criteria-Based')], max_length=50)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text="Matching criteria, e.g., {'stage': 'negotiation', 'value_gt': 10000}")),
                ('rule_is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('priority', models.IntegerField(default=1, help_text='Priority of the rule (lower numbers = higher priority)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_assigned_rules', to=settings.AUTH_USER_MODEL)),
                ('rule_type_ref', models.ForeignKey(blank=True, help_text='Dynamic rule type (replaces rule_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_assignment_rules', to='settings_app.assignmentruletype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_assignment_rules', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealSizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, help_text="e.g., 'small', 'medium'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('category_is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Deal Size Categories',
                'ordering': ['order', 'category_name'],
                'unique_together': {('tenant', 'category_name')},
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('close_date', models.DateField()),
                ('expected_closing_date', models.DateField(blank=True, help_text='Expected closing date for more accurate forecasting', null=True)),
                ('probability', models.FloatField(default=0.0)),
                ('sales_cycle_length', models.PositiveIntegerField(blank=True, help_text='Length of the sales cycle in days', null=True)),
                ('deal_size_category', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('enterprise', 'Enterprise')], default='medium', help_text='Size category of the deal (small, medium, large, enterprise) (legacy field)', max_length=20)),
                ('customer_acquisition_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Customer acquisition cost for this opportunity', max_digits=14, null=True)),
                ('expected_clv', models.DecimalField(blank=True, decimal_places=2, help_text='Expected customer lifetime value', max_digits=14, null=True)),
                ('esg_tagged', models.BooleanField(default=False)),
                ('esg_impact_description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('deal_size_category_ref', models.ForeignKey(blank=True, help_text='Dynamic deal size category (replaces deal_size_category field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.dealsizecategory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.FloatField(default=0.0)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='products',
            field=models.ManyToManyField(through='opportunities.OpportunityProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='OpportunityStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(choices=[('sales', 'Sales Pipeline'), ('support', 'Support Pipeline'), ('onboarding', 'Customer Onboarding'), ('renewal', 'Renewal Process')], default='sales', max_length=50)),
                ('opportunity_stage_name', models.CharField(max_length=100)),
                ('stage_description', models.TextField(blank=True, help_text='Description of the pipeline stage')),
                ('order', models.IntegerField(default=0)),
                ('probability', models.DecimalField(decimal_places=2, default=0.0, help_text='Default probability (0-100)', max_digits=5)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.opportunitystage'),
        ),
        migrations.CreateModel(
            name='PipelineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type_name', models.CharField(db_index=True, help_text="e.g., 'sales', 'support'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('pipeline_type_is_active', models.BooleanField(default=True, help_text='Whether this pipeline type is active')),
                ('is_system', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_pipeline_types', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Pipeline Types',
                'ordering': ['order', 'pipeline_type_name'],
                'unique_together': {('tenant', 'pipeline_type_name')},
            },
        ),
        migrations.AddField(
            model_name='opportunitystage',
            name='pipeline_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic pipeline type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='opportunities.pipelinetype'),
        ),
        migrations.CreateModel(
            name='WinLossAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_won', models.BooleanField()),
                ('win_reason', models.TextField(blank=True)),
                ('loss_reason', models.TextField(blank=True)),
                ('competitor_name', models.CharField(blank=True, max_length=255)),
                ('sales_cycle_days', models.IntegerField(default=0)),
                ('deal_size_category', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('enterprise', 'Enterprise')], default='medium', max_length=20)),
                ('deal_size_category_ref', models.ForeignKey(blank=True, help_text='Dynamic deal size category (replaces deal_size_category field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='win_loss_analyses', to='opportunities.dealsizecategory')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_pipeline_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('weighted_forecast', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('date', 'tenant')},
            },
        ),
    ]
