# Generated by Django 5.2.7 on 2025-12-15 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
        ('settings_app', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_rule_name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('territory', 'Territory-Based'), ('load_balanced', 'Load Balanced'), ('criteria', 'Criteria-Based')], max_length=50)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text="Matching criteria, e.g., {'stage': 'negotiation', 'value_gt': 10000}")),
                ('rule_is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('priority', models.IntegerField(default=1, help_text='Priority of the rule (lower numbers = higher priority)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_assigned_rules', to=settings.AUTH_USER_MODEL)),
                ('rule_type_ref', models.ForeignKey(blank=True, help_text='Dynamic rule type (replaces rule_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_assignment_rules', to='settings_app.assignmentruletype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_assignment_rules', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
