# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('opportunities', '0002_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_assignment_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dealsizecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='forecastsnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deal_size_category_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic deal size category (replaces deal_size_category field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.dealsizecategory'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='products',
            field=models.ManyToManyField(through='opportunities.OpportunityProduct', to='products.product'),
        ),
        migrations.AddField(
            model_name='opportunitystage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.opportunitystage'),
        ),
        migrations.AddField(
            model_name='pipelinetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_pipeline_types', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='opportunitystage',
            name='pipeline_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic pipeline type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='opportunities.pipelinetype'),
        ),
        migrations.AddField(
            model_name='winlossanalysis',
            name='deal_size_category_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic deal size category (replaces deal_size_category field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='win_loss_analyses', to='opportunities.dealsizecategory'),
        ),
        migrations.AddField(
            model_name='winlossanalysis',
            name='opportunity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='winlossanalysis',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='dealsizecategory',
            unique_together={('tenant', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='forecastsnapshot',
            unique_together={('date', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='pipelinetype',
            unique_together={('tenant', 'pipeline_type_name')},
        ),
    ]
