# Generated by Django 5.2.9 on 2026-01-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_account_price_list'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1.0, help_text='Points earned per 1 unit of currency spent', max_digits=10)),
                ('redemption_conversion_rate', models.DecimalField(decimal_places=4, default=0.01, help_text='Currency value of 1 point (e.g., 0.01 = 1 point is $0.01)', max_digits=10)),
                ('min_redemption_points', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'unique_together': {('tenant', 'program_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('current_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='accounts.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='loyalty.loyaltyprogram')),
            ],
            options={
                'verbose_name': 'Customer Loyalty Profile',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn Points'), ('redeem', 'Redeem Points'), ('adjust', 'Manual Adjustment'), ('expire', 'Points Expiration'), ('refund', 'Refund Reversal')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earn, negative for redeem')),
                ('reference_number', models.CharField(blank=True, help_text='POS Transaction ID or External Ref', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customerloyalty')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
