# Generated by Django 5.2.9 on 2026-01-25 18:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_accountingintegration_event_type'),
        ('loyalty', '0002_customerloyalty_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='breakage_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Estimated percentage of points that will never be redeemed (for breakage recognition)', max_digits=5),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='default_expiry_days',
            field=models.IntegerField(default=365, help_text='Default points validity in days'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='deferred_revenue_account',
            field=models.ForeignKey(blank=True, help_text='Liability account for point values (IFRS 15 Performance Obligation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_programs', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='allocated_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deferred revenue allocated to this transaction (IFRS 15)', max_digits=12),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
