# Generated by Django 5.2.9 on 2026-01-09 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(db_index=True, help_text="e.g., 'csv', 'xlsx'", max_length=10)),
                ('label', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('format_is_active', models.BooleanField(default=True, help_text='Whether this format is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Export Formats',
                'ordering': ['order', 'format_name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(db_index=True, help_text="e.g., 'email', 'web'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('channel_is_active', models.BooleanField(default=True, help_text='Whether this channel is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Notification Channels',
                'ordering': ['order', 'channel_name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(help_text='Name of the report', max_length=255)),
                ('report_description', models.TextField(blank=True, help_text='Description of the report')),
                ('report_type', models.CharField(choices=[('sales_performance', 'Sales Performance'), ('esg_impact', 'ESG Impact'), ('pipeline_forecast', 'Pipeline Forecast'), ('csrd_compliance', 'CSRD Compliance'), ('leads_recent', 'Leads (Last 7 Days)'), ('cases_recent', 'Cases (Last 3 Months)'), ('custom', 'Custom')], max_length=50)),
                ('query_config', models.JSONField(blank=True, default=dict, help_text='Configuration for the report query')),
                ('report_is_active', models.BooleanField(default=True)),
                ('is_scheduled', models.BooleanField(default=False, help_text='Whether this report runs on a schedule')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=50)),
                ('last_run', models.DateTimeField(blank=True, help_text='When the report was last generated', null=True)),
                ('last_run_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('report_created_at', models.DateTimeField(auto_now_add=True)),
                ('report_updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this report is accessible via a public link')),
                ('public_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(db_index=True, help_text="e.g., 'viewed', 'downloaded'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('action_is_active', models.BooleanField(default=True, help_text='Whether this action is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Report Actions',
                'ordering': ['order', 'action_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('shared', 'Shared'), ('scheduled', 'Scheduled')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('file', models.FileField(upload_to='report_exports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('export_created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(db_index=True, help_text="e.g., 'web', 'email'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('format_is_active', models.BooleanField(default=True, help_text='Whether this format is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Report Formats',
                'ordering': ['order', 'format_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notification_channel', models.CharField(choices=[('email', 'Email'), ('web', 'Web Notification'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], max_length=50)),
                ('notification_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(help_text='Name of the report schedule', max_length=255)),
                ('schedule_description', models.TextField(blank=True, help_text='Description of the schedule')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('schedule_is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('schedule_created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportScheduleFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_name', models.CharField(db_index=True, help_text="e.g., 'daily', 'weekly'", max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('frequency_is_active', models.BooleanField(default=True, help_text='Whether this frequency is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Report Schedule Frequencies',
                'ordering': ['order', 'frequency_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_data', models.JSONField(help_text='Historical data of the report at a specific time')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Email to send the report to (can be different from user's email)", max_length=254)),
                ('subscription_type', models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled'), ('on_demand', 'On Demand')], max_length=50)),
                ('report_format', models.CharField(choices=[('web', 'Web View'), ('email', 'Email Report'), ('pdf', 'PDF Export'), ('dashboard', 'Dashboard Widget')], default='email', max_length=20)),
                ('subscriber_is_active', models.BooleanField(default=True)),
                ('subscriber_created_at', models.DateTimeField(auto_now_add=True)),
                ('next_scheduled_send', models.DateTimeField(blank=True, help_text='When the report is next scheduled to be sent', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Name of the report template', max_length=255)),
                ('template_description', models.TextField(blank=True, help_text='Description of the report template')),
                ('template_type', models.CharField(choices=[('financial', 'Financial'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('customer', 'Customer'), ('operational', 'Operational')], max_length=100)),
                ('template_content', models.TextField(help_text='Template content (HTML, Markdown, etc.)')),
                ('template_format', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('json', 'JSON'), ('xml', 'XML')], max_length=20)),
                ('template_is_active', models.BooleanField(default=True)),
                ('template_created_at', models.DateTimeField(auto_now_add=True)),
                ('template_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, help_text="e.g., 'sales_performance', 'custom'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('type_is_active', models.BooleanField(default=True, help_text='Whether this type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Report Types',
                'ordering': ['order', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type_name', models.CharField(db_index=True, help_text="e.g., 'instant', 'scheduled'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('subscription_type_is_active', models.BooleanField(default=True, help_text='Whether this subscription type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Subscription Types',
                'ordering': ['order', 'subscription_type_name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(db_index=True, help_text="e.g., 'html', 'markdown'", max_length=20)),
                ('label', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('format_is_active', models.BooleanField(default=True, help_text='Whether this format is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Template Formats',
                'ordering': ['order', 'format_name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type_name', models.CharField(db_index=True, help_text="e.g., 'financial', 'sales'", max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('template_type_is_active', models.BooleanField(default=True, help_text='Whether this template type is active')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Template Types',
                'ordering': ['order', 'template_type_name'],
            },
        ),
    ]
