# Generated by Django 5.2.7 on 2025-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales_performance', 'Sales Performance'), ('esg_impact', 'ESG Impact'), ('pipeline_forecast', 'Pipeline Forecast'), ('csrd_compliance', 'CSRD Compliance'), ('leads_recent', 'Leads (Last 7 Days)'), ('cases_recent', 'Cases (Last 3 Months)'), ('custom', 'Custom')], max_length=50),
        ),
    ]
