# Generated by Django 5.2.9 on 2026-01-09 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportformat',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportanalytics',
            name='action_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic action (replaces action field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_analytics', to='reports.reportaction'),
        ),
        migrations.AddField(
            model_name='reportanalytics',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportanalytics',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='export_format_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic export format (replaces export_format field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to='reports.exportformat'),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportformat',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportnotification',
            name='notification_channel_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic notification channel (replaces notification_channel field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_notifications', to='reports.notificationchannel'),
        ),
        migrations.AddField(
            model_name='reportnotification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='export_format_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic export format', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_exports', to='reports.exportformat'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportnotification',
            name='report_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.reportschedule'),
        ),
        migrations.AddField(
            model_name='reportschedulefrequency',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='frequency_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic frequency (replaces frequency field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_schedules', to='reports.reportschedulefrequency'),
        ),
        migrations.AddField(
            model_name='report',
            name='schedule_frequency_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic schedule frequency (replaces schedule_frequency field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reportschedulefrequency'),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportsubscriber',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportsubscriber',
            name='report_format_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic report format (replaces report_format field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_subscribers', to='reports.reportformat'),
        ),
        migrations.AddField(
            model_name='reportsubscriber',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportsubscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsubscription',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportsubscription',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='reports.reportschedule'),
        ),
        migrations.AddField(
            model_name='reportsubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic report type (replaces report_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reporttype'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reportsubscriber',
            name='subscription_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic subscription type (replaces subscription_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_subscribers', to='reports.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='templateformat',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='template_format_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic template format (replaces template_format field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='reports.templateformat'),
        ),
        migrations.AddField(
            model_name='templatetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='template_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic template type (replaces template_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='reports.templatetype'),
        ),
        migrations.AlterUniqueTogether(
            name='exportformat',
            unique_together={('tenant', 'format_name')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationchannel',
            unique_together={('tenant', 'channel_name')},
        ),
        migrations.AlterUniqueTogether(
            name='reportaction',
            unique_together={('tenant', 'action_name')},
        ),
        migrations.AlterUniqueTogether(
            name='reportformat',
            unique_together={('tenant', 'format_name')},
        ),
        migrations.AlterUniqueTogether(
            name='reportschedulefrequency',
            unique_together={('tenant', 'frequency_name')},
        ),
        migrations.AlterUniqueTogether(
            name='reportsubscription',
            unique_together={('report', 'user', 'schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='reporttype',
            unique_together={('tenant', 'type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontype',
            unique_together={('tenant', 'subscription_type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='templateformat',
            unique_together={('tenant', 'format_name')},
        ),
        migrations.AlterUniqueTogether(
            name='templatetype',
            unique_together={('tenant', 'template_type_name')},
        ),
    ]
