# Generated by Django 5.2.7 on 2025-12-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='dynamicchoiceauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancewindow',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancewindow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancewindow',
            name='maintenance_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic maintenance type (replaces maintenance_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.maintenancetype'),
        ),
        migrations.AddField(
            model_name='maintenancewindow',
            name='notified_users',
            field=models.ManyToManyField(blank=True, related_name='maintenance_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancewindow',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.maintenancestatus'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='environment_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic environment (replaces environment field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.performanceenvironment'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='metric_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic metric type (replaces metric_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.performancemetrictype'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic category (replaces category field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.systemconfigcategory'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='data_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic data type (replaces data_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.systemconfigtype'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemeventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemeventlog',
            name='severity_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic severity (replaces severity field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.systemeventseverity'),
        ),
        migrations.AddField(
            model_name='systemeventlog',
            name='event_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic event type (replaces event_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.systemeventtype'),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='check_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic check type (replaces check_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.healthchecktype'),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='status_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic status (replaces status field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.healthcheckstatus'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='affected_tenants',
            field=models.ManyToManyField(blank=True, related_name='system_notifications', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='affected_users',
            field=models.ManyToManyField(blank=True, related_name='system_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='notification_type_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic notification type (replaces notification_type field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.notificationtype'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='priority_ref',
            field=models.ForeignKey(blank=True, help_text='Dynamic priority (replaces priority field)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.notificationpriority'),
        ),
        migrations.AddIndex(
            model_name='dynamicchoiceauditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='core_dynami_model_n_f6fd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicchoiceauditlog',
            index=models.Index(fields=['user'], name='core_dynami_user_id_65db0c_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicchoiceauditlog',
            index=models.Index(fields=['tenant_id'], name='core_dynami_tenant__af2a00_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicchoiceauditlog',
            index=models.Index(fields=['timestamp'], name='core_dynami_timesta_74fda6_idx'),
        ),
    ]
