# Generated by Django 5.2.7 on 2025-11-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data_visibility_rules',
            field=models.JSONField(blank=True, default=dict, help_text="Record-level visibility rules, e.g., {'accounts': 'own_only', 'leads': 'team_only'}"),
        ),
    ]
