# Generated by Django 6.0.2 on 2026-02-17 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_price_list'),
        ('invoicing', '0001_initial'),
        ('products', '0018_product_has_serial_numbers'),
        ('sales', '0005_sale_is_recognized_performanceobligation_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditadjustment',
            name='adjustment_type_ref',
        ),
        migrations.RemoveField(
            model_name='creditadjustment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='creditadjustment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='creditadjustment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='type_ref',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='paymentprovider',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymentprovider',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='paymentproviderconfig',
            name='name_ref',
        ),
        migrations.RemoveField(
            model_name='paymentproviderconfig',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='paymenttype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='tenant',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_updated_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_is_active',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_updated_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_is_active',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=632, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_invoices', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_invoices', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_payments', to='invoicing.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_payments', to='tenants.tenant'),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='invoicing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='invoicing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AdjustmentType',
        ),
        migrations.DeleteModel(
            name='CreditAdjustment',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentProvider',
        ),
        migrations.DeleteModel(
            name='PaymentProviderConfig',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
