# Generated by Django 6.0.2 on 2026-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_remove_creditadjustment_adjustment_type_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
