# Generated by Django 5.2.9 on 2026-01-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransactionline',
            name='is_tax_inclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postransactionline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
