# Generated by Django 5.2.9 on 2026-01-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_postransactionline_is_tax_inclusive_and_more'),
        ('products', '0010_promotion_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_transactions', to='products.coupon'),
        ),
    ]
