# Generated by Django 5.2.9 on 2026-01-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_postransaction_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterminal',
            name='customer_display_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='customer_display_port',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='printer_ip',
            field=models.GenericIPAddressField(blank=True, help_text='For network printers', null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='printer_port',
            field=models.CharField(blank=True, help_text='For USB/Serial ports', max_length=100),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='printer_type',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('network', 'Network (TCP/IP)'), ('usb', 'USB'), ('serial', 'Serial (COM/TTY)')], default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='printer_width',
            field=models.IntegerField(choices=[(32, '32 Characters'), (42, '42 Characters'), (48, '48 Characters')], default=48),
        ),
    ]
