# Generated by Django 5.2.9 on 2026-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_posterminal_customer_display_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
