# Generated by Django 5.2.9 on 2026-01-30 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='classification',
            field=models.CharField(choices=[('strategic', 'Strategic'), ('preferred', 'Preferred'), ('transactional', 'Transactional'), ('approved', 'Approved'), ('probation', 'Probation')], default='transactional', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='responsiveness_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.00 to 5.00', max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='SupplierPerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('delivery_rating', models.DecimalField(decimal_places=2, help_text='Rate 1-5', max_digits=3)),
                ('quality_rating', models.DecimalField(decimal_places=2, help_text='Rate 1-5', max_digits=3)),
                ('responsiveness_rating', models.DecimalField(decimal_places=2, help_text='Rate 1-5', max_digits=3)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
