# Generated by Django 5.2.7 on 2025-12-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NpsAbTest',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('nps_abtest_name', models.CharField(max_length=255)),
                ('nps_abtest_is_active', models.BooleanField(default=True)),
                ('auto_winner', models.BooleanField(default=True)),
                ('min_responses', models.IntegerField(default=100)),
                ('confidence_level', models.FloatField(default=0.95)),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.CreateModel(
            name='NpsSurvey',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('nps_survey_name', models.CharField(max_length=255)),
                ('nps_survey_description', models.TextField(blank=True)),
                ('nps_survey_is_active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('question_text', models.TextField(default='How likely are you to recommend us to a friend or colleague?')),
                ('follow_up_question', models.TextField(default="What's the most important reason for your score?")),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS')], default='email', max_length=20)),
                ('trigger_event', models.CharField(choices=[('user.onboarded', 'User Onboarded'), ('case.closed', 'Case Closed'), ('renewal.completed', 'Renewal Completed'), ('manual', 'Manual')], default='manual', max_length=50)),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.CreateModel(
            name='NpsAbVariant',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('variant', models.CharField(choices=[('A', 'Variant A'), ('B', 'Variant B')], max_length=1)),
                ('question_text', models.TextField(blank=True)),
                ('follow_up_question', models.TextField(blank=True)),
                ('delivery_delay_hours', models.IntegerField(default=0)),
                ('assignment_rate', models.FloatField(default=0.5)),
                ('ab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='nps.npsabtest')),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.AddField(
            model_name='npsabtest',
            name='winner_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.npsabvariant'),
        ),
        migrations.CreateModel(
            name='NpsResponse',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('delivery_id', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='nps.npssurvey')),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.CreateModel(
            name='NpsDetractorAlert',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nps.npsresponse')),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.CreateModel(
            name='NpsAbResponse',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('ab_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.npsabvariant')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nps.npsresponse')),
            ],
            bases=('tenants.tenant',),
        ),
        migrations.AddField(
            model_name='npsabtest',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='nps.npssurvey'),
        ),
        migrations.CreateModel(
            name='NpsTrendSnapshot',
            fields=[
                ('tenant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenant')),
                ('date', models.DateField()),
                ('nps_score', models.FloatField()),
                ('total_responses', models.IntegerField()),
                ('promoters', models.IntegerField()),
                ('passives', models.IntegerField()),
                ('detractors', models.IntegerField()),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('date', 'tenant_id')},
            },
            bases=('tenants.tenant',),
        ),
    ]
