# Generated by Django 5.2.9 on 2026-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NpsAbResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NpsAbTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps_abtest_name', models.CharField(max_length=255)),
                ('nps_abtest_is_active', models.BooleanField(default=True)),
                ('auto_winner', models.BooleanField(default=True)),
                ('min_responses', models.IntegerField(default=100)),
                ('confidence_level', models.FloatField(default=0.95)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NpsAbVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('A', 'Variant A'), ('B', 'Variant B')], max_length=1)),
                ('question_text', models.TextField(blank=True)),
                ('follow_up_question', models.TextField(blank=True)),
                ('delivery_delay_hours', models.IntegerField(default=0)),
                ('assignment_rate', models.FloatField(default=0.5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NpsConditionalFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_threshold', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Show this question when score is greater than or equal to this value')),
                ('conditional_question_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['score_threshold', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NpsDetractorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NpsEscalationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('create_case', 'Create Case'), ('assign_task', 'Assign Task'), ('send_notification', 'Send Notification'), ('trigger_workflow', 'Trigger Workflow'), ('send_email', 'Send Email'), ('update_field', 'Update Field'), ('assign_owner', 'Assign Owner')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('action_parameters', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NpsEscalationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NpsEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('response_type', models.CharField(choices=[('detractor', 'Detractor'), ('passive', 'Passive'), ('promoter', 'Promoter'), ('all', 'All Responses')], default='detractor', max_length=20)),
                ('min_score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('requires_comment', models.BooleanField(default=False)),
                ('auto_escalate_after_hours', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NpsEscalationRuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NpsPromoterReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_contact_name', models.CharField(blank=True, max_length=255)),
                ('referred_contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('not_interested', 'Not Interested'), ('closed', 'Closed')], default='requested', max_length=20)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NpsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('delivery_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NpsSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps_survey_name', models.CharField(max_length=255)),
                ('nps_survey_description', models.TextField(blank=True)),
                ('nps_survey_is_active', models.BooleanField(default=True)),
                ('question_text', models.TextField(default='How likely are you to recommend us to a friend or colleague?')),
                ('follow_up_question', models.TextField(default="What's the most important reason for your score?")),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS')], default='email', max_length=20)),
                ('trigger_event', models.CharField(choices=[('user.onboarded', 'User Onboarded'), ('case.closed', 'Case Closed'), ('renewal.completed', 'Renewal Completed'), ('manual', 'Manual')], default='manual', max_length=50)),
                ('scheduled_start_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_date', models.DateTimeField(blank=True, null=True)),
                ('enable_follow_up_logic', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NpsTrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nps_score', models.FloatField()),
                ('total_responses', models.IntegerField()),
                ('promoters', models.IntegerField()),
                ('passives', models.IntegerField()),
                ('detractors', models.IntegerField()),
            ],
        ),
    ]
