# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nps', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='npsabresponse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsabtest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsabvariant',
            name='ab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='nps.npsabtest'),
        ),
        migrations.AddField(
            model_name='npsabvariant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsabtest',
            name='winner_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps.npsabvariant'),
        ),
        migrations.AddField(
            model_name='npsabresponse',
            name='ab_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.npsabvariant'),
        ),
        migrations.AddField(
            model_name='npsconditionalfollowup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsdetractoralert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npsdetractoralert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsescalationaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsescalationactionlog',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='nps.npsescalationaction'),
        ),
        migrations.AddField(
            model_name='npsescalationactionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsescalationrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsescalationactionlog',
            name='escalation_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='nps.npsescalationrule'),
        ),
        migrations.AddField(
            model_name='npsescalationruleaction',
            name='escalation_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.npsescalationaction'),
        ),
        migrations.AddField(
            model_name='npsescalationruleaction',
            name='escalation_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.npsescalationrule'),
        ),
        migrations.AddField(
            model_name='npsescalationruleaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsescalationrule',
            name='actions',
            field=models.ManyToManyField(related_name='escalation_rules', through='nps.NpsEscalationRuleAction', to='nps.npsescalationaction'),
        ),
        migrations.AddField(
            model_name='npspromoterreferral',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npspromoterreferral',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsresponse',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npsresponse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npspromoterreferral',
            name='promoter_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_request', to='nps.npsresponse'),
        ),
        migrations.AddField(
            model_name='npsescalationactionlog',
            name='nps_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_actions', to='nps.npsresponse'),
        ),
        migrations.AddField(
            model_name='npsdetractoralert',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nps.npsresponse'),
        ),
        migrations.AddField(
            model_name='npsabresponse',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nps.npsresponse'),
        ),
        migrations.AddField(
            model_name='npssurvey',
            name='target_roles',
            field=models.ManyToManyField(blank=True, to='tenants.tenantrole'),
        ),
        migrations.AddField(
            model_name='npssurvey',
            name='target_territories',
            field=models.ManyToManyField(blank=True, to='tenants.tenantterritory'),
        ),
        migrations.AddField(
            model_name='npssurvey',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='npsresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='nps.npssurvey'),
        ),
        migrations.AddField(
            model_name='npsconditionalfollowup',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_follow_ups', to='nps.npssurvey'),
        ),
        migrations.AddField(
            model_name='npsabtest',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='nps.npssurvey'),
        ),
        migrations.AddField(
            model_name='npstrendsnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='npsescalationruleaction',
            unique_together={('escalation_rule', 'escalation_action')},
        ),
        migrations.AlterUniqueTogether(
            name='npsconditionalfollowup',
            unique_together={('survey', 'score_threshold')},
        ),
        migrations.AlterUniqueTogether(
            name='npstrendsnapshot',
            unique_together={('date', 'tenant')},
        ),
    ]
