# Generated by Django 5.2.7 on 2025-12-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('hardware', 'Hardware Installation'), ('ship', 'Product Shipment'), ('software', 'Software License')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(blank=True, choices=[('hardware', 'Hardware Installation'), ('ship', 'Product Shipment'), ('software', 'Software License')], help_text='Apply to all products of this type', max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage (e.g. 10.0 for 10%)', max_digits=5)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat commission amount', max_digits=10)),
                ('min_sales_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum sale amount required', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specific_product', models.ForeignKey(blank=True, help_text='Apply to specific product (overrides type)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('hardware', 'Hardware Installation'), ('ship', 'Product Shipment'), ('software', 'Software License')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.product')),
                ('sales_rep', models.ForeignKey(help_text='User credited with this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('rule_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.commissionrule')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberTerritoryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Personal revenue generated in assigned territory', max_digits=12)),
                ('personal_deals', models.IntegerField(default=0, help_text='Number of deals closed personally')),
                ('personal_quota', models.DecimalField(decimal_places=2, default=0.0, help_text='Personal quota for the territory', max_digits=12)),
                ('quota_attainment', models.DecimalField(decimal_places=2, default=0.0, help_text='Personal quota attainment (%)', max_digits=5)),
                ('territory_revenue_contribution', models.DecimalField(decimal_places=2, default=0.0, help_text='Contribution to overall territory revenue', max_digits=12)),
                ('territory_performance_rank', models.IntegerField(default=0, help_text='Rank within territory (1 is best performer)')),
                ('leads_handled', models.IntegerField(default=0, help_text='Number of leads handled in territory')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Personal conversion rate (%)', max_digits=5)),
                ('avg_sales_cycle', models.DecimalField(decimal_places=2, default=0.0, help_text='Average sales cycle in days', max_digits=5)),
                ('territory_capacity_utilization', models.DecimalField(decimal_places=2, default=0.0, help_text='Utilization of territory capacity (%)', max_digits=5)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall performance score (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='territory_metrics', to='settings_app.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryAssignmentOptimizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_date', models.DateTimeField(auto_now_add=True)),
                ('optimization_type', models.CharField(choices=[('load_balancing', 'Load Balancing'), ('performance_based', 'Performance Based'), ('geographic', 'Geographic'), ('capacity_based', 'Capacity Based')], default='load_balancing', max_length=50)),
                ('current_load', models.IntegerField(default=0, help_text='Current workload in the territory')),
                ('optimal_load', models.IntegerField(default=0, help_text='Optimal workload for the territory')),
                ('load_balance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score representing how balanced the load is (0-100)', max_digits=5)),
                ('territory_performance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall performance score (0-100)', max_digits=5)),
                ('resource_utilization', models.DecimalField(decimal_places=2, default=0.0, help_text='Resource utilization percentage (0-100)', max_digits=5)),
                ('recommended_team_size', models.IntegerField(default=0, help_text='Recommended team size for this territory')),
                ('recommended_adjustments', models.TextField(blank=True, help_text='Text description of recommended adjustments')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=2, help_text='Time taken to run optimization in seconds', max_digits=8, null=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_optimizations', to='settings_app.territory')),
            ],
            options={
                'ordering': ['-optimization_date'],
            },
        ),
        migrations.CreateModel(
            name='TerritoryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start date of the performance period')),
                ('period_end', models.DateField(help_text='End date of the performance period')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue generated in this territory', max_digits=12)),
                ('total_deals', models.IntegerField(default=0, help_text='Total number of deals closed in this territory')),
                ('average_deal_size', models.DecimalField(decimal_places=2, default=0.0, help_text='Average deal size in this territory', max_digits=10)),
                ('total_leads', models.IntegerField(default=0, help_text='Total leads in this territory')),
                ('qualified_leads', models.IntegerField(default=0, help_text='Number of qualified leads in this territory')),
                ('converted_leads', models.IntegerField(default=0, help_text='Number of converted leads in this territory')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Lead to opportunity conversion rate (%)', max_digits=5)),
                ('total_opportunities', models.IntegerField(default=0, help_text='Total opportunities in this territory')),
                ('won_opportunities', models.IntegerField(default=0, help_text='Number of won opportunities in this territory')),
                ('lost_opportunities', models.IntegerField(default=0, help_text='Number of lost opportunities in this territory')),
                ('opportunity_win_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Opportunity win rate (%)', max_digits=5)),
                ('team_member_count', models.IntegerField(default=0, help_text='Number of team members in this territory')),
                ('active_sales_reps', models.IntegerField(default=0, help_text='Number of active sales representatives in this territory')),
                ('territory_quota', models.DecimalField(decimal_places=2, default=0.0, help_text='Territory quota for the period', max_digits=12)),
                ('quota_attainment', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of quota attainment (%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='settings_app.territory')),
            ],
            options={
                'ordering': ['-period_end', 'territory__label'],
                'unique_together': {('territory', 'period_start', 'period_end')},
            },
        ),
    ]
