# Generated by Django 5.2.9 on 2026-01-09 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperformancemetric',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='team_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenantmember'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='territory_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenantterritory'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='user_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammemberterritorymetrics',
            name='team_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='territory_metrics', to='tenants.tenantmember'),
        ),
        migrations.AddField(
            model_name='territoryassignmentoptimizer',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_optimizations', to='tenants.tenantterritory'),
        ),
        migrations.AddField(
            model_name='territoryperformance',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='tenants.tenantterritory'),
        ),
        migrations.AddIndex(
            model_name='salesperformancemetric',
            index=models.Index(fields=['date', 'metric_name', 'dimension'], name='sales_sales_date_d822be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='territoryperformance',
            unique_together={('territory', 'period_start', 'period_end')},
        ),
    ]
