# Generated by Django 5.2.7 on 2025-11-20 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_rep',
            field=models.ForeignKey(help_text='User credited with this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(blank=True, choices=[('hardware', 'Hardware Installation'), ('ship', 'Product Shipment'), ('software', 'Software License')], help_text='Apply to all products of this type', max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage (e.g. 10.0 for 10%)', max_digits=5)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat commission amount', max_digits=10)),
                ('min_sales_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum sale amount required', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specific_product', models.ForeignKey(blank=True, help_text='Apply to specific product (overrides type)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.sale')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('rule_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.commissionrule')),
            ],
        ),
    ]
