# Generated by Django 5.2.9 on 2026-01-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_csr_ready_account_esg_certified_and_more'),
        ('sales', '0003_sale_created_at_sale_tenant_sale_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.account'),
        ),
    ]
