# Generated by Django 5.2.9 on 2026-01-26 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_accountingintegration_event_type'),
        ('accounts', '0007_account_price_list'),
        ('proposals', '0003_proposalline'),
        ('sales', '0004_alter_sale_account'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_recognized',
            field=models.BooleanField(default=False, help_text='True if revenue has been earned/recognized'),
        ),
        migrations.CreateModel(
            name='PerformanceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Transaction price allocated per IFRS 15 Step 4', max_digits=12)),
                ('recognized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recognition_method', models.CharField(choices=[('point_in_time', 'Point in Time (e.g., Delivery)'), ('over_time', 'Over Time (e.g., Service Subscription)'), ('milestone', 'Milestone Based')], default='point_in_time', max_length=20)),
                ('status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled')], default='unfulfilled', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deferred_revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_liabilities', to='accounting.chartofaccount')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_revenue', to='accounting.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='obligation',
            field=models.ForeignKey(blank=True, help_text='The fulfillment obligation this sale satisfies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.performanceobligation'),
        ),
        migrations.CreateModel(
            name='RevenueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_recognized', models.BooleanField(default=False)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sales.performanceobligation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contracts', to='accounts.account')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.proposal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='performanceobligation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='sales.salescontract'),
        ),
    ]
