# Generated by Django 5.2.9 on 2026-01-09 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('leads', '0001_initial'),
        ('opportunities', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WazoCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('from_number', models.CharField(max_length=50)),
                ('to_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('completed', 'Completed'), ('failed', 'Failed'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail')], default='initiated', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('wazo_data', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wazo_calls', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wazo_calls', to='accounts.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wazo_calls', to='leads.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wazo_calls', to='opportunities.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wazo_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tenant', 'started_at'], name='wazo_wazoca_tenant__162438_idx'), models.Index(fields=['from_number'], name='wazo_wazoca_from_nu_364f6c_idx'), models.Index(fields=['to_number'], name='wazo_wazoca_to_numb_49e3e2_idx'), models.Index(fields=['status'], name='wazo_wazoca_status_4660c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='WazoExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='Wazo extension number (e.g., 1001)', max_length=20)),
                ('caller_id', models.CharField(blank=True, help_text='Outbound caller ID', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('wazo_user_uuid', models.CharField(blank=True, help_text='Wazo user UUID', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wazo_extension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'extension')},
            },
        ),
        migrations.CreateModel(
            name='WazoSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('from_number', models.CharField(max_length=50)),
                ('to_number', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('wazo_data', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wazo_sms', to='accounts.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wazo_sms', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wazo_sms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['tenant', 'sent_at'], name='wazo_wazosm_tenant__cce131_idx'), models.Index(fields=['from_number'], name='wazo_wazosm_from_nu_3e12d9_idx'), models.Index(fields=['to_number'], name='wazo_wazosm_to_numb_eb3c9e_idx')],
            },
        ),
    ]
