# Generated by Django 5.2.9 on 2026-01-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('wazo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicemailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, help_text='Upload audio file (MP3/WAV)', null=True, upload_to='voicemail_templates/')),
                ('audio_url', models.URLField(blank=True, help_text='Or provide external audio URL', max_length=500)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
