# Generated by Django 5.2.7 on 2025-11-25 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('action_type', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('state_before', models.JSONField(blank=True, null=True)),
                ('state_after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_id', '-timestamp'], name='audit_logs__tenant__323b09_idx'), models.Index(fields=['action_type', '-timestamp'], name='audit_logs__action__a03129_idx'), models.Index(fields=['severity', '-timestamp'], name='audit_logs__severit_96a515_idx'), models.Index(fields=['user_id', '-timestamp'], name='audit_logs__user_id_64dfe5_idx')],
            },
        ),
    ]
