# Generated by Django 5.2.7 on 2025-12-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_logs', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspatternanalysis',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_patterns_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesspatternanalysis',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_patterns', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='accesspatternanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalydetectionresult',
            name='analyzed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_analysis_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalydetectionresult',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detections', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='anomalydetectionresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='complianceaudittrail',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_audits_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceaudittrail',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_audits', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='complianceaudittrail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='affected_tenants',
            field=models.ManyToManyField(blank=True, related_name='security_incidents_affected', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='affected_users',
            field=models.ManyToManyField(blank=True, related_name='security_incidents_affected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'audit_log_created_at'], name='audit_logs__user_id_184550_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'audit_log_created_at'], name='audit_logs__action_b676eb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_logs__resourc_760a22_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant_id', 'audit_log_created_at'], name='audit_logs__tenant__cbe93b_idx'),
        ),
    ]
