# Generated by Django 5.2.9 on 2026-01-02 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('communication', '0002_initial'),
        ('leads', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='communicationhistory',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationhistory',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationhistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customersupportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customersupportticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customersupportticket',
            name='first_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_first_responded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customersupportticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customersupportticket',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customersupportticket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='email',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='email',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailsignature',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='emailsignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsmsserviceconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_configs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsmsserviceconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_configurations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='communicationhistory',
            name='service_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_sent', to='communication.emailsmsserviceconfiguration'),
        ),
        migrations.AddField(
            model_name='feedbackandsurvey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackandsurvey',
            name='tenant_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_forms', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_organized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='communicationhistory',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_sent', to='communication.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='sms',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='sms',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='sms',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='sms',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sms',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='customersupportticket',
            index=models.Index(fields=['status'], name='communicati_status_076750_idx'),
        ),
        migrations.AddIndex(
            model_name='customersupportticket',
            index=models.Index(fields=['priority'], name='communicati_priorit_23836b_idx'),
        ),
        migrations.AddIndex(
            model_name='customersupportticket',
            index=models.Index(fields=['tenant'], name='communicati_tenant__2199e7_idx'),
        ),
        migrations.AddIndex(
            model_name='customersupportticket',
            index=models.Index(fields=['created_at'], name='communicati_created_df2437_idx'),
        ),
        migrations.AddIndex(
            model_name='customersupportticket',
            index=models.Index(fields=['status', 'priority'], name='communicati_status_7ba1fd_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationhistory',
            index=models.Index(fields=['recipient'], name='communicati_recipie_5a29ca_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationhistory',
            index=models.Index(fields=['status'], name='communicati_status_28ba45_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationhistory',
            index=models.Index(fields=['tenant'], name='communicati_tenant__d725f0_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationhistory',
            index=models.Index(fields=['created_at'], name='communicati_created_33dcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationhistory',
            index=models.Index(fields=['communication_type', 'status'], name='communicati_communi_3741fc_idx'),
        ),
    ]
