# Generated by Django 5.2.9 on 2026-01-08 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_ccpa_consent_account_country_and_more'),
        ('communication', '0003_initial'),
        ('leads', '0002_initial'),
        ('opportunities', '0003_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Main Business Line')", max_length=100)),
                ('phone_number', models.CharField(help_text='WhatsApp Business phone number with country code', max_length=20)),
                ('phone_number_id', models.CharField(blank=True, help_text='WhatsApp Phone Number ID from Meta', max_length=50)),
                ('business_account_id', models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=50)),
                ('api_token', models.TextField(blank=True, help_text='Encrypted API access token')),
                ('webhook_verify_token', models.CharField(blank=True, help_text='Webhook verification token', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary number for outbound messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configurations',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='WhatsApp message ID (wamid)', max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('location', 'Location'), ('contact', 'Contact'), ('interactive', 'Interactive')], default='text', max_length=20)),
                ('from_number', models.CharField(db_index=True, max_length=20)),
                ('to_number', models.CharField(db_index=True, max_length=20)),
                ('body', models.TextField(blank=True, help_text='Message text content')),
                ('caption', models.TextField(blank=True, help_text='Media caption if applicable')),
                ('media_url', models.URLField(blank=True, help_text='URL to media file', max_length=500)),
                ('media_mime_type', models.CharField(blank=True, max_length=100)),
                ('template_name', models.CharField(blank=True, help_text='WhatsApp template name if template message', max_length=100)),
                ('template_language', models.CharField(blank=True, default='en', max_length=10)),
                ('template_variables', models.JSONField(blank=True, default=list, help_text='Template variable values')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('wazo_data', models.JSONField(blank=True, default=dict, help_text='Raw Wazo/WhatsApp API response')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='accounts.account')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communication.whatsappconfiguration')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='accounts.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='leads.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='opportunities.opportunity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='User who sent/handled this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='communicati_tenant__18b89b_idx'), models.Index(fields=['from_number'], name='communicati_from_nu_7f9e81_idx'), models.Index(fields=['to_number'], name='communicati_to_numb_684d67_idx'), models.Index(fields=['status'], name='communicati_status_7e5811_idx'), models.Index(fields=['direction', 'status'], name='communicati_directi_b58166_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text="Template name (must match Meta's template name)", max_length=100)),
                ('template_id', models.CharField(blank=True, help_text='Meta template ID', max_length=50)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], default='utility', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('header_text', models.TextField(blank=True, help_text='Template header text')),
                ('body_text', models.TextField(help_text='Template body text with {{1}}, {{2}} placeholders')),
                ('footer_text', models.TextField(blank=True, help_text='Template footer text')),
                ('buttons', models.JSONField(blank=True, default=list, help_text='Button configurations')),
                ('variable_count', models.IntegerField(default=0, help_text='Number of variables in template')),
                ('variable_examples', models.JSONField(blank=True, default=list, help_text='Example values for variables')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['category', 'template_name'],
                'unique_together': {('tenant', 'template_name', 'language')},
            },
        ),
    ]
